### ISSUE TITLE
triage the Unfuddle TODO list

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#10]
From https://github.com/phetsims/gas-properties/issues/8#issuecomment-357065247:
> I'll triage the TODO list:
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/333

**Comment by pixelzoom** [comment]
Here's the TODO list, so I don't have to keep consulting Unfuddle https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/333.

-Bug Report (6-25-2007)
I just found a new bug in Gas Properties.  If you pump in a bunch of molecules, say, more than 300, the number of molecules in the box fluctuates, and if you try to select the number of heavy molecules in the textbox to change it, the cursor automatically moves to the textbox for the number of light molecules, so you can't edit the number of heavy molecules.
Balloons and Buoyancy has the same problem, but Reversible Reactions does not.
In Version 3.02.02 and earlier, the number of molecules still fluctuates, but at least when you try to select the number the cursor remains in the same box, rather than moving to a different one. v3r25 seems to be the last version where the number of molecules doesn't fluctuate.

-Bug Report (6-25-2007)
Also, if I open the lid to let particles out, the number of particles in the textbox starts decreasing as particles leave the box, but then as soon as I close the lid, the number of particles jumps back up to a much higher number than it was the instant before when the lid was open.
I've checked it out with low numbers of particles, and it looks like particles are actually suddenly appearing in the box when you close the lid.

Here are the bugs that Alex always sees:
1.	When there are a lot of molecules in the tank, some will escape out the sides.
2.	When the temperature is at 0K, the molecules continue to twitch.  Even if the ice is left on for a long time.
3.	If you keep cooling the take after it has reached 0K, then when you try to warm it up, it takes as long to warm it up to 1 K as you spent cooling it after it reached 0K.
4.	When I let all the molecules out, there were still two heavy species and the counters said 2 heavy and 12 light but there were no light species in the tank.
5.	When on constant temperature, the fire and ice go up and down on their own even if there is no gravity and nothing is being done to the simulation. To keep constant temperature?
6.	If the lid flies off during constant temperature, the fire turns on full blast but when I switch to none under constant parameter the fire does not go off.
7.	When the lid is barely open, molecules can get out even though the space is much smaller than the molecules.

6-25-2007
-demote from gold star to beta

- Hot air balloon stove resets when reset button is hit
- Changed color of wiggle me and help



- Put color L&F on panels
- Enable reset for all modules
- Look in to moving wall collisions
- ScalarDataRecorder should computeDataStatistics everytime a datum is added if it isn't a clocked recorder. When I
do it, then make computeDataStatistics() private.
- make needle on dial gauge triangular
- Test setting locale via command line parameter, not property
- Put pump, box and mannequin on common baseline
- consolidate MoleculePanel classes in RigidHollowSphere and HeliumBalloon
- set default energy so kinetic energy is never < 0
- make more versatile & robust collision detection system that works heirarchically with object types
- when hot air balloon is putting in heat, the whole system heats up, but only when gravity is on
- rename and consolidate collision expert/detector classes
- Sam, clockStateListeners
- Make the stove a model element and move IdealGasModel.addHeatFromStove() to Stove.stepInTime()
- check CollidableBody.stepInTimeNoNotify()
- pressure slice graphic overlays mannequin
- scalarDataRecorder should be re-written so it doesn't need a clock, but rather observes an ScalarReporter
- clean up constraints. In particular, there is a lot of duplication in HollowSphereMustContain and
HollowSphereMustNotContain
- hierarchy of Body/.../IdealGasParticle is way too big. Clean it up!


......

this time when I opened the sliding door on top, the blue atoms just went above the door and stopped, piled up there.
 
reseting did not get rid of these blue atoms on top of door and atom number reset to 198, the number that I let out the top  

the little man does not lean no matter how much pressure I put in

 
minimizing the Ideal Gas does not reduce the task-processing amount (remains at ~98%)  


with no atoms bouncing around (but 198 "lost-in-space" ) the task-processing is at ~98%  


with just the "pump-the-handle" sign moving, task-processsing is at ~90%.	might be able to address, but I'm not sure that it's worth the effort

pause drops task-processing to essentially 0 under all cases  
 
when I go to full screen on the ideal gas, the resolution of the atoms and some of the other objects on the screen is poor ... I don't know if this is a saver for drawing time or not?	The images have to be interpolated up when the screen goes to full size, and they are getting aliased. I'll have to think about how to address this.


the little man jerks a bit when being repainted on full-screen view. Same as above


on the start-up size of the sim, the controls are cut off ... why not start up full screen?	I don't see any cutoff of controls in the current simulation. Simulation performance goes down as the size of the display goes up, so I'd prefer not to start it up full-screen.

On the rigid hollow sphere, typing in a second value in the number of particles in the inner balloon does not work, the particles go to zero no matter what I type.  


Even after reset, cannot add particles to balloon anymore.For some reason "reset" also reset the default temp to 37K even though I had never adjusted the temperature, so now pumping in atoms is like molasses.  


The helium balloon panel needs work .... the balloon needs to respond to the pressure of the atoms inside it so that we can get it to fall. Right now, I cannot get it to sink with gravity on so it cannot be used to teach the learning goals. It will be tricky ... hopefully it can be done. But if we (Carl, really) chooses not to work on it right now, I think this panel will need to be removed/hidden until the physics is right.  


the ruler does not display/undisplay properly .. does not redraw.  
 
flames and ice jump to left of screen when the stove is adjusted  

Help on left of screen doesn't show unless you move the wall

**Comment by pixelzoom** [comment]
@arouinfar @ariel-phet Perhaps one of you should specify a date for when I should address this issue. It will probably take me a full day, and I've been slammed with other things. so I've been treating it as low priority.

**Comment by arouinfar** [comment]
Great question @pixelzoom, but I think this is @ariel-phet's call.

**Comment by ariel-phet** [comment]
@pixelzoom officially marking as priority-deferred.

Let's check back in on this around April 15th and see where are things are.

**Comment by pixelzoom** [comment]
My only concern about deferring is if there are things in the TODO list that need to inform design.  But may design is happening until after April 15.

**Comment by ariel-phet** [comment]
@pixelzoom I think we are safe through March. This sim is still in lots of brain storming.

**Comment by pixelzoom** [comment]
Oops. We're way past April 15, and this sim is now well into development.   

@ariel-phet @arouinfar how do you want to proceed with triaging the TODO list?

**Comment by arouinfar** [comment]
@pixelzoom a lot of these seem irrelevant to Gas Properties HTML5, especially since you are not directly porting the Java model. There may be a few items that may require some design discussion. Can you review and see which of these items merits further discussion? The only thing that sticks out to me is the behavior around 0 K. 

> When the temperature is at 0K, the molecules continue to twitch. Even if the ice is left on for a long time.

>If you keep cooling the take after it has reached 0K, then when you try to warm it up, it takes as long to warm it up to 1 K as you spent cooling it after it reached 0K.

I do not think we need to allow the system to be cooled to 0 K. The behavior of matter at 0 K is strange, and there will be a lot of weird edge cases we'll need to work out (which is what happened for States of Matter). The learning goals of this sim do not require 0 K, so I would be fine with limiting the HeaterCoolerNode so that the system cannot be cooled beyond a certain limit, say 5 K.

**Comment by pixelzoom** [comment]
Discussion of behavior at absolute zero is moved to #36.

**Comment by pixelzoom** [comment]
TODO items that I'll need to watch out for in the Java model have been consolidated in #37.

**Comment by arouinfar** [comment]
Looks good to me. Thanks @pixelzoom!
