### ISSUE TITLE
add a scale to Diffusion screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#101]
In https://github.com/phetsims/gas-properties/issues/100#issuecomment-497886651, @kathy-phet suggested a new feature:

> Team - Diffusion looks great as a single sim! My only question about Diffusion screen is if a teacher might want a scale on the box, to help somehow have students take data and graph the center of mass marker positions away from center versus time. Not sure what this would look like - small ticks or something. (This would apply to it in the other sim too). Thoughts?

**Comment by pixelzoom** [comment]
@kathy-phet Could you clarify what you mean by "scale"?  Do you mean a width indicator, like what is shown via the "Width" checkbox in the _Ideal_ screen?

**Comment by pixelzoom** [comment]
If the tick marks are labeled with values...  Unfortunately the container is 15 nm wide, so the divider (center) is at 7.5 nm, instead of a nice integer value.

**Comment by pixelzoom** [comment]
If it would be advantageous to have the center at an integer value, we have some options:

* Increase the container width to 16nm. It looks like there's enough space on either side of the container to do this.
* Reduce the container width to 14 nm.

In both cases, we could also change the scale factor in the model-view transform to make the container appear to be the same size (pixel width) that it is now.  But changing that scale factor will also affect the size of particles.  And the scale won't match the first 3 screens.    At this late point, I'm a little nervous about messing with the model-view transform, and would prefer not to do that.

**Comment by arouinfar** [comment]
@kathy-phet were you thinking about something like this? I think tick marks like these could be helpful for plotting the center of mass position vs. time, though a `MeasuringTapeNode` would be more precise. Personally, I'd rather add a `MeasuringTapeNode`.

![image](https://user-images.githubusercontent.com/8419308/58839711-1cb1ca80-8620-11e9-82c6-5040ce91aa4d.png)
![image](https://user-images.githubusercontent.com/8419308/58839727-2cc9aa00-8620-11e9-8206-e8a6fad176f5.png)

> Increase the container width to 16 nm. It looks like there's enough space on either side of the container to do this.

If we do add tick marks, I think a 16 nm container would be preferable, as there would be an even number of tick marks on either side of the center.

> In both cases, I could also change the scale factor in the model-view transform to make the container appear to be the same size (pixel width & height) that it is now. 

That sounds like way more trouble than it'd be worth. Let's not go there.

**Comment by pixelzoom** [comment]
I prefer the scale indicators in @arouinfar's mockup because a scale will be a lot less work than a measuring tape :)  


We haven't discussed whether this is always on, but I'm guessing not, and we'll probably want a checkbox.  It's going to be tight, but it looks like we have room for a "Scale" or "Measuring Tape" checkbox in the control panel, below the "Stopwatch" checkbox. 



Anyway, that's my 4 cents

**Comment by pixelzoom** [comment]
I prefer the scale indicators in @arouinfar's mockup because a scale will be a lot less work than a measuring tape :)  

If we went with the top mockup (0 at center), then a measuring tape might be a little problematic if you wanted to take measurements for both center-of-mass indicators at the same time. 

We haven't discussed whether this is always on, but I'm guessing not, and we'll probably want a checkbox.  It's going to be tight, but it looks like we have room for a "Scale" or "Measuring Tape" checkbox in the control panel, below the "Stopwatch" checkbox. 

Anyway, that's my 6 cents.

**Comment by arouinfar** [comment]
After some discussion with @kathy-phet, I'm also thinking scale indicators are the way to go. We iterated on the design a bit, and added a 1 nm scale bar instead of tick mark labels. This cleans things up a bit while still conveying the necessary information. How does this look @pixelzoom?

![image](https://user-images.githubusercontent.com/8419308/58841813-c7c68200-8628-11e9-9e7b-e9416d9d589d.png)

> We haven't discussed whether this feature is always on, but I'm guessing not, and we'll probably want a checkbox. It's going to be tight, but it looks like we have room for a "Scale"

Let's add a "Scale" checkbox below the stopwatch, default off.

**Comment by pixelzoom** [comment]
Discussed with @arouinfar on Slack, and she added:

* `rgb(220,220,220)` in normal mode
* `black` or a dark gray in projector mode

**Comment by pixelzoom** [comment]
@arouinfar ready for review in master or [1.0.0-dev.34](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.34/phet/gas-properties_en_phet.html).  Screenshot with `?dev` below.

A few notes:
* I added an icon to the "Scale" checkbox, easy to remove or modify the icon.
* I placed the "Scale" checkbox _above_ the "Stopwatch" checkbox so that all options related to the container are grouped together.  Easy to change if you'd prefer it below the "Stopwatch" checkbox.
* I adjusted overall vertical spacing so that the flow-rate indicators wouldn't feel crowded.
* Scale and icon colors are default:`rgb(220,220,220)` and projector:`rgb(100,100,100)`

<img width="1020" alt="screenshot_1227" src="https://user-images.githubusercontent.com/3046552/58885221-0ac33c80-869f-11e9-9eb3-dc918c74ed98.png">

**Comment by pixelzoom** [comment]
Part of me wants to put the "Scale" checkbox above the "Particle Flow Rate" checkbox, so the vertical layout of the checkboxes matches the vertical layout of the things that they control.  But maybe that's overthinking it.

**Comment by ariel-phet** [comment]
Just jumping in with an opinion here...Perhaps consider putting the scale on the top of the box? on the bottom I feel there is quite a bit going on, and the numerical position of the center of mass is not so important as the qualitative nature of it. If we really like it on the bottom, I am fine with that, but I think things might be cleaner with it on top.

**Comment by pixelzoom** [comment]
I may not have this correct.  But the use case for this feature (as explained to me by @arouinfar) is that students would observer how far the center of mass is from the center of the box (1 tick, 2 ticks, 2.5 ticks, etc.)   So that's why it's on the bottom of the container.

**Comment by arouinfar** [comment]
@pixelzoom the Scale icon, colors, and placement are all looking good to me. @ariel-phet I think it's pretty critical to keep the Scale and COM markers close together, since the goal is provide a way for students to quantify COM position vs. time.

> Part of me wants to put the "Scale" checkbox above the "Particle Flow Rate" checkbox, so the vertical layout of the checkboxes matches the vertical layout of the things that they control. But maybe that's overthinking it.

I do like the idea of grouping Center of Mass and Scale, since those are meant to be used together. However, the goals for the Scale checkbox are a bit more advanced/quantitative, so we may want students exploring this option later in the flow. I think it's better to keep the checkbox location where it is. Plus, its current proximity to the Stopwatch is also a good fit.

Since there isn't any further action to be taken here, I'm going to go ahead and close.
