### ISSUE TITLE
Different image for "Oops" dialog possibly?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gas-properties#102]
This is extremely minor, and I have no qualms if we don't squeeze it in, but I was thinking the Oops dialog with PhET girl in shorts seems a little out of place.

@pixelzoom is the image used in the Oops dialog optional (as in could we set that up to have a few different image possibilities or image supplied)?

@arouinfar I was thinking PhET girl in a lab coat would be more appropriate, I know Mariah made several version like that in the past. I just feel having her in chemistry garb (lab coat and safety glasses with finger wagging) would be more appropriate cute for this sim.

**Comment by pixelzoom** [comment]
> ... is the image used in the Oops dialog optional...

The image in the `OopsDialog` is currently not optional.  Relatively straightforward to do so, < 2 hours.

**Comment by pixelzoom** [comment]
FYI, the current image is scenery-phet/images/phet-girl-wagging-finger.png, size 125x275, and it's scaled down to a height of 132 by `OopsDialog`.  If we provide an option to supply an alternate image (e.g. `options.image`), we could handle the scaling in `OopsDialog`, or make the client responsible for the scaling. I'm inclined to do the latter, so that we don't have an explosion of options for `OopsDialog`.

**Comment by ariel-phet** [comment]
@pixelzoom I would say go ahead and at least make the image optional, then we at least have, well, the option. I could see in future Math sims or such giving her a "mathy" look.

**Comment by pixelzoom** [comment]
I've added `options.iconNode` to `OopsDialog`, so it's all set to use a different "icon". 

Here's an example of its usage in scenery-phet's demo app:

<img width="673" alt="screenshot_1228" src="https://user-images.githubusercontent.com/3046552/58892501-94790700-86ab-11e9-895c-67b7e41d6fd7.png">

**Comment by ariel-phet** [comment]
Sweet!

**Comment by pixelzoom** [comment]
@arouinfar You can email me .ai and .png files for the new images when you have them. I'll take care of putting them in GitHub, setting up the license file, etc.

**Comment by arouinfar** [comment]
> @arouinfar I was thinking PhET girl in a lab coat would be more appropriate, I know Mariah made several version like that in the past. I just feel having her in chemistry garb (lab coat and safety glasses with finger wagging) would be more appropriate cute for this sim.

I was able Frankenstein together lab coat-wearing PhET girl with the wagging finger PhET girl. I combined the art fairly quickly, so the underlying layer isn't so pretty. However, the image itself looks reasonable to me.

![oops-dialog](https://user-images.githubusercontent.com/8419308/58969224-94910980-8774-11e9-86d1-adab0fdbe069.png)

@pixelzoom here are the assets. The original artwork was created by Mariah Hermsmeyer.
[oops-dialog.zip](https://github.com/phetsims/gas-properties/files/3257859/oops-dialog.zip)

**Comment by pixelzoom** [comment]
Love the new image.  I've integrated into master, see screenshot below.  

Here's the license file entry:

```
  "phet-girl-lab-coat.png": {
    "text": [
      "Copyright 2019 University of Colorado Boulder"
    ],
    "projectURL": "http://phet.colorado.edu",
    "license": "contact phethelp@colorado.edu",
    "notes": "created by Mariah Hermsmeyer, adapted by Amy Rouinfar"
  }
```

Back to @arouinfar for review.

<img width="1018" alt="screenshot_1232" src="https://user-images.githubusercontent.com/3046552/58972464-dcb32a80-877a-11e9-8562-2f52163524f3.png">

**Comment by arouinfar** [comment]
Looks awesome, thanks @pixelzoom!
