### ISSUE TITLE
test for memory leaks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#103]
Do memory profiling, similar to what was done in phetsims/equality-explorer#64.

Use a built version.

**Comment by pixelzoom** [comment]
| Minutes | Heap Size (MB) |
| --- | --- |
| 0 | XX |
| 5 | XX |
| 10 | XX |
| 15 | XX |
| 20 | XX |
| 25 | XX |
| 30 | XX |
| 45 | XX |
| 60 | XX |

**Comment by pixelzoom** [comment]
I asked @KatieWoe if the results in https://github.com/phetsims/gas-properties/issues/103#issuecomment-499545462 looked reasonable.  She said that the memory usage actually looks lower than expected, which is great. 

@arouinfar @ariel-phet @kathy-phet FYI, memory testing is done, no issues, closing.

**Comment by veillette** [comment]
While reviewing the simulation, we build the simulation with 
grunt --minify.mangle=false --brands=phet

on Windows 10, with fuzz test, we find that the heap size does not increase over time

![image](https://user-images.githubusercontent.com/7633344/59208692-98a79780-8b77-11e9-84ef-6d1970030612.png)
