### ISSUE TITLE
wallSpeedLimit looks incorrect

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#115]
In reviewing the performance for #98, I noticed that the wallSpeedLimit for compression looks incorrect in [dev.36](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.36/phet/gas-properties_en_phet.html). It appears quite a bit faster than [dev.32](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.32/phet/gas-properties_en_phet.html) which had the appropriate speed limit. Not sure if the compression speed limit was correct when I reviewed https://github.com/phetsims/gas-properties/issues/90#issuecomment-498418128 in master, but I believe it was.

**Comment by pixelzoom** [comment]
I'll investigate.  dev.32 and dev.36 should both have `wallSpeedLimit: 800` (decision in https://github.com/phetsims/gas-properties/issues/90#issuecomment-497461559), and that's what it's currently set to in master:

```js
    // Speed limit for the container's left movable wall, in pm/ps. Relevant when reducing the container size.
    // For internal use only.
    wallSpeedLimit: {
      type: 'number',
      isValidValue: value => ( value > 0 ),
      defaultValue: 800
    }
```

**Comment by pixelzoom** [comment]
Verified that dev.36 and master are indeed faster than dev.32. dev.35 looks correct, so something changed between dev.35 and dev.36.

**Comment by pixelzoom** [comment]
There's only one relevant changeset between dev.35 and dev.36: https://github.com/phetsims/gas-properties/commit/a7c7a54ad47f674b205e1075ab091cbe4c03e159

**Comment by pixelzoom** [comment]
Fixed in the above commit.  There were some ofter changes, and it looks like perhaps the container was getting stepped twice, sorry about that.   @arouinfar please verify in master or [1.0.0-dev.37](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.37/phet/gas-properties_en_phet.html).

**Comment by arouinfar** [comment]
Looking good in dev.37, thanks @pixelzoom!
