### ISSUE TITLE
BaseModel.selectFor does not return expected list

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#12]
From the [SwingJS Note](https://docs.google.com/document/d/1aGmLksuZrlVZf6GgeSJdIm4CcHHofqICzP5V4PNKhCQ/edit)s in #5:

> In phetcommon.model.BaseModel, the method selectFor(Class[])  only returns the list for the last class in the array, not all of them. 

```
public List selectFor( Class[] classes ) {
    	List elements = new ArrayList( modelElements );
    	for ( int i = 0; i < classes.length; i++ ) {
        		Class c = classes[i];
        		elements = selectFor( elements, c );
    	}
    	return elements;
}
```

@samreid commented:
> Yes, this is a logic bug.  I wonder if it is being exhibited in any of our published sims, or if it is a “latent” bug.

Sounds like a legacy bug for @pixelzoom to address.

**Comment by pixelzoom** [comment]
There nothing similar to BaseModel in HTML5 sims, so this is sort of irrelevant.  But I'll leave it open until we start the port.

**Comment by pixelzoom** [comment]
Now that I've started on Gas Properties...  This most definitely will not be a direct port, and nothing like BaseModel will exist in HMTL5.   So this issue is irrelevant and can be closed.
