### ISSUE TITLE
update copyright dates of modules

### ISSUE THREAD

**Issue by veillette** [phetsims/gas-properties#121]
The are a few modules that, although strictly speaking not under the purview of this code review  (#109), will need to be updated via grunt-copyright-dates.

**Comment by pixelzoom** [comment]
Thanks @veillette.  I will certainly update the copyright dates before the final code review.  And it's good to have this issue to remind me.  Unassigning until that time.

**Comment by pixelzoom** [comment]
I ran `grunt update-copyright-dates` and pushed the changes.  I'm going to go ahead and close this issue.  I always for a "self review" with the code-review checklist (#122) that will remind me to run `grunt update-copyright-dates` again.
