### ISSUE TITLE
Negative pressures and assertions failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#124]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/342
When there is a small number of particles it is possible for the pressure reading to be negative.  I was unable to find a physical reason for this.  When looking at the debug version I do not see this negative pressure, but an assertion failed error shows up at about the same consistency as the negative pressure did.  The error looks like:
```
gas-properties_all_phet_debug.html:28583 Uncaught Error: Assertion failed: value failed isValidValue: -10.787170841022018
    at window.assertions.assertFunction (gas-properties_all_phet_debug.html:28583)
    at Object.isValueValid (gas-properties_all_phet_debug.html:31906)
    at validate (gas-properties_all_phet_debug.html:32151)
    at NumberProperty.Property.validate (gas-properties_all_phet_debug.html:34674)
    at NumberProperty.set (gas-properties_all_phet_debug.html:34742)
    at NumberProperty.set (gas-properties_all_phet_debug.html:44169)
    at NumberProperty.set value [as value] (gas-properties_all_phet_debug.html:34906)
    at PressureGauge.step (gas-properties_all_phet_debug.html:107679)
    at PressureModel.update (gas-properties_all_phet_debug.html:115666)
    at IdealModel.updateModel (gas-properties_all_phet_debug.html:116174)
```
**Steps to reproduce:**
1. Go to the ideal screen
2. Open the Particles accordion box
3. Add a single red particle
4. Watch the pressure

**Screenshots:**
![negativepressure](https://user-images.githubusercontent.com/41024075/59365103-35dc0a80-8cf5-11e9-8e19-87529c2fde32.gif)
![debugsame](https://user-images.githubusercontent.com/41024075/59365109-38d6fb00-8cf5-11e9-9180-bf29a3ccfabe.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Gas Properties‬
URL: https://bayes.colorado.edu/dev/html/gas-properties/1.0.0-dev.38/phet/gas-properties_all_phet.html
Version: 1.0.0-dev.38 2019-06-11 17:16:28 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.  This is a duplicate of https://github.com/phetsims/gas-properties/issues/123, which was created this morning.  If you disagree, feel free to reopen.

**Comment by pixelzoom** [comment]
Actually...  This issue is more useful than #123, because it includes steps to reproduce manually (thanks @KatieWoe!)   So I'm going to close #123 and track the problem in this issue.

**Comment by pixelzoom** [comment]
Removing @arouinfar assignment because this is an implementation bug, nothing wrong with design.

**Comment by pixelzoom** [comment]
Fixed in above commit.  @KatieWoe please verify in master.

**Comment by KatieWoe** [comment]
This looks good in master

**Comment by KatieWoe** [comment]
Looks good
