### ISSUE TITLE
container width in Ideal screen should not be updated until endDrag

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#125]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/342
If there is a code reason for this, or it has already been discussed, feel free to close.  When the wall is being moved in the Ideal screen, all of the particles freeze, and move to new positions when you let the wall go.  However, if you drag the wall past a place where the pressure is too much, the wall is dropped without input.
**Steps to reproduce:**
1. Turn off pressure noise
2. Go to ideal screen
3. Make box large and pump full of red particles
4. Heat until pressure is about 3/4 of max
5. Start to drag the wall in

**Screenshots:**
https://drive.google.com/file/d/19v-hsFMgl6BaL4XD-aEYc16_is7WI9bc/view?usp=sharing

Troubleshooting information (do not edit):

<details>

Name: ‪Gas Properties‬
URL: https://bayes.colorado.edu/dev/html/gas-properties/1.0.0-dev.38/phet/gas-properties_all_phet.html
Version: 1.0.0-dev.38 2019-06-11 17:16:28 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
Looks like a bug to me.

**Comment by arouinfar** [comment]
@pixelzoom it looks the the pressure is being updated in the model while container handle is being moved. Perhaps the pressure should instead be updated on `endDrag`?


![pressureneedle](https://user-images.githubusercontent.com/8419308/59385295-44401b80-8d21-11e9-85aa-ac0d91015df0.gif)

**Comment by pixelzoom** [comment]
@arouinfar I don't think that's the cause of this problem, sounds more like a different requirement for when paused.  OK to move https://github.com/phetsims/gas-properties/issues/125#issuecomment-501484679 to its own issue?

**Comment by arouinfar** [comment]
> OK to move #125 (comment) to its own issue?

Sure, please do!

**Comment by pixelzoom** [comment]
@KatieWoe I'm not clear on what you mean by "the wall is dropped without input".  Do you mean the interaction with the wall's resize handle is canceled when the lid blows off?  If so...

That is the desired behavior; when the lid blows off, any interaction with the container (resize handle or lid) is canceled.  @arouinfar do you agree, or do want to change this?

**Comment by pixelzoom** [comment]
@KatieWoe I'm not clear on what you mean by "the wall is dropped without input". Do you mean the interaction with the wall's resize handle is canceled when the lid blows off? If so...

That is the desired behavior; when the lid blows off, any interaction with the container (resize handle or lid) is canceled. @arouinfar do you agree, or do want to change this?

@pixelzoom edit: FYI, it would be trivial to cancel interaction with the lid only, and allow interaction with the resize handle to continue when the lid blows off.

**Comment by KatieWoe** [comment]
Interaction is canceled when the lid blows off.  The thing that seemed like a bug to me was the lid blowing off before you'd decided what size the container should be and let go.  Since the gas basically pauses and restarts in a slightly new configuration when the wall is dropped and not before I thought this behavior was inconsistent.

**Comment by pixelzoom** [comment]
Thanks for the clarification @KatieWoe.

**Comment by pixelzoom** [comment]
Thanks for the clarification @KatieWoe.  Now I see that this is in fact related to #132.

**Comment by pixelzoom** [comment]
Moving #132 back into this issue.

@arouinfar said:
> @pixelzoom it looks the the pressure is being updated in the model while container handle is being moved. Perhaps the pressure should instead be updated on `endDrag`?

![pressureneedle](https://user-images.githubusercontent.com/8419308/59385295-44401b80-8d21-11e9-85aa-ac0d91015df0.gif)

**Comment by pixelzoom** [comment]
So... What we want to do here is not as simple as "pressure should instead be updated on `endDrag`.  What we want to do is wait until `endDrag` to update the container width in the model.    And I do think that's the right thing to do.  Based on an initial investigation, this is going to require a significant code change.

**Comment by pixelzoom** [comment]
@arouinfar The lid handle is currently disabled while dragging the container's resize handle.  But I think we'll also need to disable the "Return Lid" button while the resize handle is being dragged, since the container being shown is the proposed container, not the actual container.  Does that sound acceptable?

**Comment by arouinfar** [comment]
Yes, that sounds reasonable to me @pixelzoom.

**Comment by pixelzoom** [comment]
When the user adjusts the container width while the sim is paused, the model no longer updates.  This has been addressed in master and [1.0.0-dev.41](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.41/phet/gas-properties_en_phet.html).  @arouinfar and @KatieWoe please verify.  The last one to verify can please label this issue as "fixed-awaiting-deploy".

**Comment by KatieWoe** [comment]
Intro screen behavior in this case looks good on master to me.  Not sure why, but it did seem like the particles were a bit more jumpy/laggy than before.

**Comment by pixelzoom** [comment]
Yes, PhET-iO instrumentation seems to have negatively impacted behavior.  I thought it might just be my imagination, but good to know that someone else has noticed it who wasn't aware that instrumentation had occurred.  I will open an issue.

**Comment by pixelzoom** [comment]
Also 1.0.0-dev.41 still has a problem.  If you pause the sim, then resize the container, things don't update when your release the container's handle.  That is addressed in [1.0.0-dev.42](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.42/phet/gas-properties_en_phet.html).

**Comment by arouinfar** [comment]
@pixelzoom looking good in dev.42!

**Comment by KatieWoe** [comment]
Looks good 1.0.0-rc.1
