### ISSUE TITLE
Too short  max width for scale and stopwatch checkbox labels

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#127]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/342
The scale and stopwatch strings seem to have max widths that are too small on the diffusion screen.
**Steps to reproduce:**
1. Go to diffusion screen with stringTest=long

**Screenshots:**
![veryshort](https://user-images.githubusercontent.com/41024075/59380712-f0303980-8d16-11e9-8dee-5f4270f939a1.png)

Troubleshooting information (do not edit):

<details>

Name: 12345678901234567890123456789012345678901234567890
URL: https://bayes.colorado.edu/dev/html/gas-properties/1.0.0-dev.38/phet/gas-properties_all_phet.html?stringTest=long
Version: 1.0.0-dev.38 2019-06-11 17:16:28 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
@pixelzoom can you increase the `maxWidth` of "Scale" and "Stopwatch" to match the other strings?

**Comment by pixelzoom** [comment]
Yep, planning on it.

**Comment by pixelzoom** [comment]
Fixed in master, see screenshot below. @KatieWoe please verify in master.

<img width="349" alt="screenshot_1245" src="https://user-images.githubusercontent.com/3046552/59452472-05ff3680-8dcb-11e9-9eb2-5ccaa845ccf4.png">

**Comment by KatieWoe** [comment]
Looks good.  But I did notice the other three screens might have a similar issue:
![maybeheretoo](https://user-images.githubusercontent.com/41024075/59457542-d86bba80-8dd5-11e9-9e42-31a18c673413.png)
@arouinfar to decide

**Comment by pixelzoom** [comment]
I don't think this will be an issue in practicer. But I'll use uniform maxWidth in the other screens too.  Self-assigning.

**Comment by pixelzoom** [comment]
Each screen now uses a uniform `maxWidth` for checkbox text labels, see screenshots below with `?stringTest=long`.  @KatieWoe please review in master.

Ideal:

<img width="231" alt="screenshot_1246" src="https://user-images.githubusercontent.com/3046552/59458716-4618e600-8dd8-11e9-9eb3-8ca2dce1ea61.png">

Explore:

<img width="234" alt="screenshot_1247" src="https://user-images.githubusercontent.com/3046552/59458728-49ac6d00-8dd8-11e9-8663-8968e4c5e1e6.png">

Energy:

<img width="234" alt="screenshot_1248" src="https://user-images.githubusercontent.com/3046552/59458739-4fa24e00-8dd8-11e9-85c6-7c929a269157.png">

Diffusion:

<img width="288" alt="screenshot_1249" src="https://user-images.githubusercontent.com/3046552/59458745-55982f00-8dd8-11e9-8414-a1166c000209.png">

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by KatieWoe** [comment]
Looks good 1.0.0-rc.1
