### ISSUE TITLE
update histograms and Average Speed when container is emptied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#129]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Firefox (and chrome)
**Problem description:**
For https://github.com/phetsims/QA/issues/342
I noticed that the speed histogram stays present longer than anything else after the Energy screen is restarted.
**Steps to reproduce:**
1. Go to Energy screen
2. Release particles
3. Hit orange reset button

**Screenshots:**
![abitlate](https://user-images.githubusercontent.com/41024075/59386884-0513c980-8d25-11e9-8643-528df5668ccb.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Gas Properties‬
URL: https://bayes.colorado.edu/dev/html/gas-properties/1.0.0-dev.38/phet/gas-properties_all_phet.html
Version: 1.0.0-dev.38 2019-06-11 17:16:28 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
If the Kinetic Energy histogram stayed expanded, you'd see that it clears at the same time as the Speed histogram.  This is because while the sim is running (not paused), the histograms update on a refresh interval.   @arouinfar shall we leave "as is", or should I change that so that the histograms update immediately whenever container becomes empty?

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

@pixelzoom I think it looks a bit strange for the histograms to linger. If it's a straightforward change, please update them immediately when the container is emptied.

**Comment by pixelzoom** [comment]
Will do. Not straightforward, but relatively easy.  And it feels like a good change.

**Comment by pixelzoom** [comment]
Changed in master.  When the container becomes empty, the histograms now update immediately.  @KatieWoe please verify in master.  If OK, change this issue to "status:fixed-awaiting-deploy".

**Comment by KatieWoe** [comment]
Looks good

**Comment by KatieWoe** [comment]
Somewhat related for https://github.com/phetsims/QA/issues/386.  I noticed that the average speed numbers stay around for a bit when you use the erase button.  Harder to see, and a bit less of an issue.  Up to you @pixelzoom @arouinfar if this issue can be closed or still needs work.
(Can be hard to see on screen recording)
![hardtoseespeedstays](https://user-images.githubusercontent.com/41024075/62148727-81537380-b2b7-11e9-9f94-a1e4b11df539.gif)

**Comment by arouinfar** [comment]
Good catch @KatieWoe. It looks like the Average Speed resets about a time step after the histograms. @pixelzoom could you extend https://github.com/phetsims/gas-properties/commit/1b1ac3bbdb31cf66ee961b357bb859f586d2c05e to the Average Speed readout, as well?

**Comment by pixelzoom** [comment]
I will investigate.

**Comment by pixelzoom** [comment]
Fixed in master and 1.0 branches. @KatieWoe please review in master.

**Comment by pixelzoom** [comment]
I updated the title of this issue, here and in phetsims/QA#386.

**Comment by KatieWoe** [comment]
Looks good on master @pixelzoom

**Comment by pixelzoom** [comment]
👍 To be verified in 1.0.0-rc.2.

**Comment by KatieWoe** [comment]
Looks good
