### ISSUE TITLE
Particles do not collide with right or bottom wall

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#13]
From the [SwingJS Notes](https://docs.google.com/document/d/1aGmLksuZrlVZf6GgeSJdIm4CcHHofqICzP5V4PNKhCQ/edit) in #5:

> Particles are offset up and to the left. This causes them to penetrate walls on the top and left and never actually hit the walls on the right and bottom. This was partially due to pixel rounding. 
![image](https://user-images.githubusercontent.com/8419308/36701060-175b851c-1b0f-11e8-82e7-bf2582e9c2c2.png)

Sounds like a legacy bug to me, so assigning @pixelzoom so he's aware.

**Comment by pixelzoom** [comment]
This was probably due to treating particles as points, and not taking particle diameter into account in the collision model.   Unlikely that this bug would be ported, but I'll leave this open just in case.

**Comment by pixelzoom** [comment]
This is not going to be a direct port, and unlikely that this wouldn't be noticed in the HTML5 version if I happened to make the same error.   So closing this issue.
