### ISSUE TITLE
Button spacing too close on iOS

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/gas-properties#130]
For https://github.com/phetsims/QA/issues/342.

The spacing for the radio buttons and the pause/play button looks too close. Can the spacing be changed?

![issue](https://user-images.githubusercontent.com/31285590/59389557-d77e4e80-8d2b-11e9-97e1-28adfc4546f7.PNG)

**Comment by pixelzoom** [comment]
I'm see much more vertical space on the platforms that I'm testing on, see macOS + Chrome screenshot below.  @lmulhall-phet please provide troubleshooting info that identifies OS and browser.  I suspect that this is on a platform where the fonts  sizes are taller, making the entire panel taller. 

Note to self: The solution for this is to set `maxHeight` for the control panel.

<img width="980" alt="screenshot_1244" src="https://user-images.githubusercontent.com/3046552/59391005-2d54f580-8d30-11e9-9426-a9c26dff9f3d.png">

**Comment by arouinfar** [comment]
Oh joy, looks like another case of https://github.com/phetsims/wave-interference/issues/326.

@pixelzoom you'll probably end up needing to reduce the vertical padding between the UI components in the panel. I trust your judgement, but happy to advise which pixels to cut out if you'd prefer to go that route.

**Comment by arouinfar** [comment]
Interestingly, I didn't notice any layout issues when testing on iPad/Chromebook in https://github.com/phetsims/gas-properties/issues/98#issuecomment-500497481.

**Comment by pixelzoom** [comment]
There's no need (in general) to reduce the vertical spacing, font sizes, or anything else.  If we just set `maxHeight` on panels, then those panels (and everything in them) will be uniformly scaled.  Fonts will become effective the same height as on other platforms.  Everything else will scale down, but negligibly.

**Comment by pixelzoom** [comment]
@arouinfar said:
> Interestingly, I didn't notice any layout issues when testing on iPad/Chromebook ...

@lmulhall-phet is this indeed on Chromebook?  (Useful to have the troubleshooting info regardless.)

**Comment by arouinfar** [comment]
@pixelzoom the issue title says iOS (the `wave-interfernce` issue was Chromebook) but it would be good to know which device(s) @lmulhall-phet.

**Comment by pixelzoom** [comment]
Ah sorry, I missed the "iOS" in the issue title. I'm used to looking for specifics in the Troubleshooting info (which should be part of any QA issue).

**Comment by pixelzoom** [comment]
Fixed in the above commit. @lmulhall-phet please verify in master.  If it looks OK, please change this issue to "status:fixed-awaiting-deloy".

**Comment by pixelzoom** [comment]
@lmulhall-phet or @KatieWoe ping.

**Comment by pixelzoom** [comment]
@lmulhall-phet or @KatieWoe ping.

**Comment by KatieWoe** [comment]
Sorry @pixelzoom I think this got lost in my email last time.  On it.

**Comment by KatieWoe** [comment]
Checked on iPad iOS 11.4.1 and iPhone 7 iOS 12.3.1.
Looks good on both.

**Comment by KatieWoe** [comment]
looks good 1.0.0-rc.1
