### ISSUE TITLE
Does the lid come off too early

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#131]
For https://github.com/phetsims/QA/issues/342
Very small design issue.  Seems like it would be more difficult than it is worth to fix.  Sometimes the lid comes off when no particles are near said lid.  Pressure is registered as enough to blow the lid off, but particles haven't reached that point.  This can look a bit odd in some situations.
To Reproduce:
1. Go to the first screen
2. Make container small
3. Pause the sim
4. Add all the red particles
5. Start to step through the sim slowly

![nocause](https://user-images.githubusercontent.com/41024075/59389714-45c31100-8d2c-11e9-8515-fbc66b9e99dc.gif)

**Comment by pixelzoom** [comment]
The lid blowing off is related to pressure, no where the particles are located.  If we want it to blow off only when there are particle collisions, that's very problematic.  @arouinfar please advise.

**Comment by arouinfar** [comment]
Thanks for reporting @KatieWoe, but there's nothing to be done here. The lid blows when the pressure gauge maxes out, and the pressure gauge doesn't know anything about the distribution of the particles throughout the container.
