### ISSUE TITLE
Inconsistent layering of the stopwatch

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#133]
**Device**
Chadwick
**OS**
ChromeOS (and others)
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/QA/issues/342
What the stopwatch is in front of and behind varies by screen and some of the results can look quite odd.  On the Ideal and Explore screens it is in front of everything.  On the Energy screen it is behind the tool and accordion boxes.  On the Diffusion screen it is behind the pause/step through and speed controls.
**Steps to Reproduce**
1. Drag the timer around all the screens and observe behavior

**Screenshots**
![incosistantstopwatch](https://user-images.githubusercontent.com/41024075/59447667-da774e80-8dc0-11e9-8093-4c0f6683c135.gif)

**Comment by pixelzoom** [comment]
Thanks, should be easy to adjust.

**Comment by pixelzoom** [comment]
This is fix in master, @KatieWoe please review.  If it looks OK, please change issue status to "fixed-awaiting-deploy".

**Comment by KatieWoe** [comment]
Looks good

**Comment by KatieWoe** [comment]
Aside from https://github.com/phetsims/gas-properties/issues/148, this looks good for 1.0.0-rc.1
