### ISSUE TITLE
Particles outside of box remain when erase button is used

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#134]
**Device**
Chadwick
**OS**
ChromeOS
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/QA/issues/342
Less of a full bug and more of a graphical oddity.  When particles leave the box the become non-interactive (they don't bump into each other etc.) and this prevents them from falling back into the box.  However, when you click the erase button, only the particles in the box disappear.  Any on the outside are unaffected and continue floating away.  This can look a bit odd.
**Steps to reproduce**
1. Go to one of the first three screens
2. Pump in some of the blue particles
3. (optional) You may want to cool the gas down a bit to slow down particles
4. Open the hatch
5. When some, but not all, of the particles leave, but are still on the screen, hit the eraser button

**Screenshots**
![notallerased](https://user-images.githubusercontent.com/41024075/59461607-01447d80-8ddf-11e9-9e66-c64a7b48632e.gif)

**Comment by pixelzoom** [comment]
This is behaving as specified, see https://github.com/phetsims/gas-properties/issues/91:
> ... an eraser button to clear particles from the container would be useful on the first 3 screens. 

@arouinfar would you like to change this so that it deletes _all_ particles, not just those in the container?  It will be < 30 minutes of work.

**Comment by arouinfar** [comment]
> @arouinfar would you like to change this so that it deletes all particles, not just those in the container? It will be < 30 minutes of work.

I think it would look cleaner to delete all of the particles, and the time estimate seems reasonable, so please make this change @pixelzoom.

**Comment by pixelzoom** [comment]
The erase button now removes all particles, both inside and outside the container. @KatieWoe @arouinfar please verify in master.

**Comment by KatieWoe** [comment]
Looks good in master to me.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.

@arouinfar if it looks good to you, please unassign and change label to "status:fixed-awaiting-deploy".

**Comment by arouinfar** [comment]
Looks good to me too, thanks @pixelzoom.

**Comment by pixelzoom** [comment]
@KatieWoe This was checked off as verified in https://github.com/phetsims/QA/issues/386, so I'm going to go ahead and close it.
