### ISSUE TITLE
performance degrades with ?ea&brand=phet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#135]
Related to dev test phetsims/QA#342

@etwa4650 reported on Slack:

Ethan Ward [11:58 AM]
I noticed that the performance in master seemed to be noticably worse, but when I removed the query parameter ?ea&brand=phet it performed like normal. Is that expected?

Chris Malley [5:34 PM]
Not expected, thanks for reporting that. I’ll create an issue.

**Comment by pixelzoom** [comment]
@etwa4650 did you notice this on a specific platform, or all platforms?

**Comment by pixelzoom** [comment]
@etwa4650 could you also try removing `?ea` and `?brand=phet` separately, to determine which one is responsible for performance degradation?  I suspect it's `?ea` that cause things to run slower, since there are many assertions enabled, some of which involve additional iterations over the entire set of particles to do validation.

**Comment by etwa4650** [comment]
@pixelzoom 
Looks like it is ?ea. Heres a video of what I am seeing, I am also on macOS 10.14.5 and Chrome 75.

https://drive.google.com/open?id=1eMjCpRj3klcXfRN8CGZyyrg5ebESMTxM

**Comment by pixelzoom** [comment]
@etwa4650 Thanks for the video.  I'm not going to worry about this if it's only with `?ea`, because the sim is doing a lot of extra "verification" work while assertions are enabled.  

But I do find it odd that you're seeing this on macOS 10.14.5 with Chrome 75, because that's my primary test platform, and I see no problem with `?ea` (which I run with all the time).  So a couple of questions:

* What is the test machine?  
* Can you check with all Chrome extensions disabled? URL chrome://extensions

**Comment by etwa4650** [comment]
@pixelzoom 
Its not one of our test machines it's my personal device. 

<img width="584" alt="Screen Shot 2019-06-17 at 11 45 12 AM" src="https://user-images.githubusercontent.com/26493147/59624982-6e188a00-90f5-11e9-856c-beb6ac03a2e8.png">

I tried testing with all my chrome extensions disabled and did not notice any improvment.

**Comment by pixelzoom** [comment]
Thanks @etwa4650.  Still can't explain why you and I see different `?ea` performance on similar platforms.  But I'm not going to spend more time on this since it's with `?ea`.  Thanks for reporting, closing.

**Comment by pixelzoom** [comment]
@etwa4650 My MacBook Pro is the latest model, with a bit faster processor, more RAM, and faster graphics card than yours (see below). So perhaps that's why I don't see a performance issue with `?ea`. 

![screenshot_1257](https://user-images.githubusercontent.com/3046552/59645681-793cdb80-9130-11e9-85c7-6f2b71a627aa.jpg)
