### ISSUE TITLE
lid gets out of sync with container width

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#136]
Related to dev test phetsims/QA#342. 

Here's a little weirdness that I came across in while working on #128.  Discovered on macOS 10.14.5 + Chrome 75, but it's certainly the same on all platforms. 

1. Start the sim, go to _Ideal_ screen.
2. Add 1000 heavy particles to the container.
3. Add 650 light particles to the container. (Do not blow lid off!)
3. Pause the sim.
4. Drag the container resize handle to the right.  This blows the lid off and interrupts the drag. 
5. With the sim still paused, grab the resize handle and drag it to the right.  The lid width gets out of sync with the container width, as in the screenshot below.

This happens in master and [1.0.0-dev.39](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.39/phet/gas-properties_en_phet.html), but not in [1.0.0-dev.38](https://bayes.colorado.edu/dev/html/gas-properties/1.0.0-dev.38/phet/gas-properties_en_phet.html) (the dev test version).  Something that was changed for some other issue must have introduced this.

<img width="1087" alt="screenshot_1254" src="https://user-images.githubusercontent.com/3046552/59575772-0a04b000-907a-11e9-9162-126e0d99deef.png">

**Comment by pixelzoom** [comment]
https://github.com/phetsims/gas-properties/commit/326c66273d52dcc09adbb1eea16262f8f724589b for #126 looks like a likely suspect.

**Comment by pixelzoom** [comment]
In this case, the lid is actually NOT out of sync with the container.  It has been blown off (hence the "Return Lid" button), but hasn't moved because the sim is paused.   And while the lid is off the container, it is independent of the container width.  So while it looks odd, it's correct.   

This belongs in the same category as what we discussed in https://github.com/phetsims/gas-properties/issues/118, which we closed as "won't fix".  So I'm inclined to also close this as "won't fix", unless @arouinfar thinks there's something to be done here.

**Comment by arouinfar** [comment]
> This belongs in the same category as what we discussed in #118, which we closed as "won't fix". So I'm inclined to also close this as "won't fix", unless @arouinfar thinks there's something to be done here.

Agreed @pixelzoom. I'll go ahead and close as `type:wontfix`.
