### ISSUE TITLE
CT invalid dt:0

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#138]
```
diffusion : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas
Uncaught Error: Assertion failed: invalid dt: 0
Error: Assertion failed: invalid dt: 0
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1561528310946/assert/js/assert.js:22:13)
    at DiffusionScreenView.step (https://bayes.colorado.edu/continuous-testing/snapshot-1561528310946/gas-properties/js/common/view/BaseScreenView.js?bust=1561551561107:97:17)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1561528310946/joist/js/Sim.js?bust=1561551561107:232:21
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1561528310946/axon/js/Action.js?bust=1561551561107:177:20)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1561528310946/joist/js/Sim.js?bust=1561551561107:934:33)
    at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1561528310946/joist/js/Sim.js?bust=1561551561107:915:14)
    at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1561528310946/joist/js/Sim.js?bust=1561551561107:898:14)
id: Bayes Chrome
Approximately 6/25/2019, 11:51:50 PM
```

**Comment by samreid** [comment]
I recall leaving `stepSimulation(0)` open as a possibility in case some simulation needs to run initialization via `stepSimulation(0)` before time starts passing.  In retrospect, it seems odd that a simulation may need that facility and I would recommend investigating putting `dt > 0`.  For me, this would mean checking `dt > 0` instead of `dt >= 0` and checking through sims to see if any of them have incorrect startup configurations (hopefully not).  We should also check if any simulation is explicitly calling `step(0)` or equivalent and see if it needs to be dealt with.

**Comment by pixelzoom** [comment]
That sounds reasonable.  

This will need to be resolved before gas-properties begins RC testing.  Shooting for week of July 8.

**Comment by samreid** [comment]
@jonathanolson remarked that `step( 0 )` is called a few places in our code and seems reasonable.  Therefore we will change Sim.js to send out strictly >0, but we will allow sims to internally `step(0)` if necessary.

**Comment by samreid** [comment]
Leaving self-assigned to make the change in Sim.js

**Comment by samreid** [comment]
Proposed fix committed, @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/gas-properties/issues/138#issuecomment-506416605, @samreid said:
> ... For me, this would mean checking `dt > 0` instead of `dt >= 0` and checking through sims to see if any of them have incorrect startup configurations (hopefully not). We should also check if any simulation is explicitly calling `step(0)` or equivalent and see if it needs to be dealt with.

From https://github.com/phetsims/gas-properties/issues/138#issuecomment-506479347, it looks like the check for `step(0)` was done.  But was anything done to check for sim with "incorrect startup configurations"?

**Comment by samreid** [comment]
Testing on Mac Chrome, I'm seeing the first call to `stepOneFrame` passing through `dt` approximately equal to 1/60, as expected.  I'm no longer sure we need to check initial configurations.  I can't see how `stepSimulation(0)` may be happening on some platforms and somehow correcting the initial configuration (but not on others).  I'm happy to close the issue if there's nothing else, or let me know if I'm misunderstanding something.

**Comment by pixelzoom** [comment]
Thanks for the clarification. Closing.
