### ISSUE TITLE
Escaped particles are inappropriately returned to the container

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#14]
From the [SwingJS Notes](https://docs.google.com/document/d/1aGmLksuZrlVZf6GgeSJdIm4CcHHofqICzP5V4PNKhCQ/edit) in #5:

> Escaped molecules are returned to box if they escape through the side of the opening rectangle. Fixed in SphereBoxExpert.areInContact by adding a maximum for how far away the particle can be from the box:

```
// Hitting top wall?
(y = c.getY() - r) <= (by = box.getMinY()) && y > by - 20 && sphere.getVelocity().getY() < 0
```

@samreid commented:
> I’m not sure whether that was a bug or a workaround.

I've tried to reproduce this issue in two ways:
* Open the top of the container, let some particles out, then close the lid. Nothing looks fishy.
* Blow the lid and use Return Lid button. All remaining particles in the container will be removed. While this seems like an odd design choice, it doesn't match the issue described.

Kicking this one to @pixelzoom.

**Comment by pixelzoom** [comment]
Noted. Unassigning until development begins.

**Comment by pixelzoom** [comment]
This is safe to close.  The initial collision detection in 1.0.0-dev.4 indicates that no particles are leaking from the container.  And since there is no gravity, particles that leave the container will never return to the container; they will float up and away.
