### ISSUE TITLE
change class name prefix from "GasProperties" to "IdealGasLaw"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#140]
Over in https://github.com/phetsims/gas-properties/issues/111#issuecomment-508812061 and https://github.com/phetsims/gas-properties/issues/111#issuecomment-508856201, @jbphet and I decided that prefix "IdealGasLaw" would be an improvement over "GasProperties" (e.g. `IdealGasLawModel` vs `GasPropertiesModel`).   I will make that change. 

Rename:
- [x] `GasPropertiesModel`
- [x] `GasPropertiesContainer`
- [x] `GasPropertiesScreenView`
- [x] `GasPropertiesContainerNode`
- [x] `GasPropertiesParticleSystemNode`
- [x] `GasPropertiesViewProperties`

- [x] ... and remember to update implementation-notes.md

**Comment by pixelzoom** [comment]
Done in above commit.  Below is a list of the remaining files that have "GasProperties" as a prefix.  None of these are specific to the Ideal Gas Law, and they are all specializations for the sim as a whole (even though some of them are not used in the Diffusion screen).

<img width="666" alt="screenshot_1271" src="https://user-images.githubusercontent.com/3046552/60746336-7b2dd980-9f3b-11e9-955f-c8535844fa83.png">

**Comment by pixelzoom** [comment]
@jbphet ready for review as part of #111.

**Comment by jbphet** [comment]
I verified that all files in the list above have been renamed, looked through the documentation updates, and scanned to code for references to the old file names.  It all looks good.  Closing.
