### ISSUE TITLE
touchAreas for AccordionBox ExpandCollapseButtons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#141]
_@pixelzoom note: This comment from @jbphet was moved here from https://github.com/phetsims/gas-properties/issues/111#issuecomment-508877355, since I think it warrants its own issue._

@jbphet said:

In regard to the checklist item "Are pointer areas optimized, especially for touch?", @arouinfar approved the pointer areas in #97, but I'm a bit skeptical because in the past I've been asked to expand the touch areas for the open/close buttons on accordion boxes.  Here is what they look like for the current master version of "Gas Properties":

![image](https://user-images.githubusercontent.com/3082831/60748030-23956b00-9f47-11e9-86de-4e764f70954f.png)

In "Build an Atom" the pointer areas for the accordion boxes look like this:
![image](https://user-images.githubusercontent.com/3082831/60747968-92be8f80-9f46-11e9-907f-5147d514e7ae.png)

Perhaps the standards have changed for this, but I thought I'd point it out just in case.

**Comment by pixelzoom** [comment]
Wow, those are some extremely dilated buttons touchAreas for the ExpandCollapseButtons in "Build An Atom".  I've never been asked to do anything like that. And my understanding is that the "standard" is the default in AccordionBox.  And if it's not, shouldn't it be? Why should every client have to change the default?

That said... @arouinfar Your call on this.

**Comment by pixelzoom** [comment]
If we apply the same touchArea proportions used in BAA to Gas Properties, that would be `touchAreaXDilation: 15` and `touchAreaYDilation: 15`.  There will be problems with overlap, for example:

<img width="1089" alt="screenshot_1273" src="https://user-images.githubusercontent.com/3046552/60749321-59415080-9f55-11e9-8c8c-5f039d745cbe.png">

If you want to dilate a bit more than the default, then I recommend ``touchAreaXDilation:6` and `touchAreaYDilation:6`.  For example:

<img width="1089" alt="screenshot_1272" src="https://user-images.githubusercontent.com/3046552/60749338-b9d08d80-9f55-11e9-8339-bd4af0b6e757.png">

**Comment by pixelzoom** [comment]
I said:
> If you want to dilate a bit more than the default, then I recommend `touchAreaXDilation:6` and `touchAreaYDilation:6`. For example: ...

Since I made this code change to generate the above screenshot, I took a chance that this would be OK and committed it.   @arouinfar please have a look at master, let me know if you want this reverted or changed.

**Comment by arouinfar** [comment]
The extremely dilated touch areas in BAA stemmed from https://github.com/phetsims/QA/issues/295. At the time, AccordionBox titles were not interactive (see https://github.com/phetsims/sun/issues/502). Since the titles are now again interactive, I don't see a need to greatly dilate the touch areas of the ExpandCollapseButton, but a dilation of 6 looks good to me.
