### ISSUE TITLE
PhET-iO instrumentation has negatively impacted performance

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#144]
While verifying an unrelated issue, @KatieWoe commented in https://github.com/phetsims/gas-properties/issues/125#issuecomment-512514473
> Intro screen behavior in this case looks good on master to me. Not sure why, but it did seem like the particles were a bit more jumpy/laggy than before.

I thought it might just be my imagination - after I added tandems and some metadata for #30 yesterday, it seems like things are not running as smoothly.  Good to know that someone else has noticed it who wasn't aware that instrumentation had occurred.  

The first dev version with PhET-iO instrumentation is 1.0.0-dev.40.

This is a big problem, and I'm not sure how to proceed. We will discuss at Thursday 7/18 design meeting.  Mentioning Gas Properties team and PhET-iO team: @arouinfar @ariel-phet @kathy-phet @samreid @zepumph @chrisklus.

**Comment by pixelzoom** [comment]
@KatieWoe can you verify whether performance appear to be impacted in the built version?  You can compare [1.0.0-dev.39](https://bayes.colorado.edu/dev/html/gas-properties/1.0.0-dev.39/phet/gas-properties_en_phet.html) (before instrumentation) to [1.0.0-dev.40](https://bayes.colorado.edu/dev/html/gas-properties/1.0.0-dev.40/phet/gas-properties_en_phet.html).

**Comment by pixelzoom** [comment]
Also beware that there is no baseline dev version that was published immediately before adding PhET-iO code (kicking myself for not doing that). So there were a few changes in 1.0.0-dev.40 that are not related to instrumentation.   I'm going to investigate how to go back and create a baseline version for a snapshot immediate before instrumentation started.

**Comment by KatieWoe** [comment]
There's no real difference shown by the ?profiler parameter.  They both hover in the mid-thirties under the situation I was reproducing, and sometimes jump down to ~7 before jumping back up after a second.  Didn't see any performance difference I could precisely pinpoint either.

**Comment by pixelzoom** [comment]
@KatieWoe what "the situation that you are producing"?

**Comment by pixelzoom** [comment]
Here's the situation that I'm using to test performance:

1. Start the sim with `?profiler`
2. Go to the Ideal screen.
3. Open the Particles accordion box.
4. Add >= 500 heavy particles using the coarse spinner.
5. Immediately add >= 500 light particles using the coarse spinner.

Built versions 1.0.0-dev.39 and 1.0.0-dev.40 both run at 60fps, and there's no perceptible difference in smoothness.

Requirejs versions 1.0.0-dev.39 and 1.0.0-dev.40 also look good, running at 60fps. 

Adding `?ea` in requirejs mode results in a performance difference. 1.0.0-dev.40 is noticeably jerkier.  Perhaps the assertions added by PhET-iO are the cause.  And perhaps we're OK if the problem is indeed only in requirejs with `?ea`.

**Comment by KatieWoe** [comment]
I noticed the performance problem when I had all the blue and 3 pumps of the red particle.  This wasn't important to the issue, which is why I didn't mention it.  I just replicated it in order to have a more meaningful comparison.

**Comment by pixelzoom** [comment]
I confirmed with @KatieWoe via Slack that she was running in requirejs mode with `?ea` when she reported this issue. 

<details>
<summary>Slack discussion</summary>
<br>

Chris Malley 1:45 PM
When you tested master, were you running with ?ea

Kathryn Woessner:office: 1:49 PM
Yes.  It is default when you use the link from phettest.

Chris Malley 1:49 PM
Cool.  I think the performance hit is the additional assertions added by PhET-iO.
Those are of course stripped out in built version, so we’re probably OK here.
new messages

Kathryn Woessner:office: 1:50 PM
:+1:
</details>

**Comment by pixelzoom** [comment]
@KatieWoe Could you please do a performance comparison of built versions 1.0.0-dev.39 vs 1.0.0-dev.40 with `?profiler` on a range of platforms?  Whatever you think is necessary to be reasonably certain that instrumentation has not negatively impacted the built version.

Something like this is what I had in mind:

| OS | Browser | 1.0.0-dev.39 fps | 1.0.0-dev.40 fps |
| ------------- | ------------- | ------------- | ------------- |
| | | | |
| | | | |
| | | | |
| | | | |

And a description of whatever test scenario you decide to use.

**Comment by KatieWoe** [comment]
| OS & version | Browser & version | 1.0.0-dev.39 fps | 1.0.0-dev.40 fps |
| ------------- | ------------- | ------------- | ------------- |
| Win 10 | Chrome | | |
| Win 10 | Firefox | | |
| Win 10 | Edge | | |
| Win 10 | IE | | |
| Mac 10.14 | Chrome | | |
| Mac 10.14 | Safari | | |
| Chrome OS | Chrome OS | | |
| iOS 12 | Safari | | |
| Mac 10.10 | Safari | | |
| iOS 9 | Safari | | |

**Comment by arouinfar** [comment]
Thanks for the heads-up @pixelzoom. We will certainly discuss this during tomorrow's design meeting. Hopefully @KatieWoe will have have time to finish up the performance testing before then.

**Comment by KatieWoe** [comment]
@pixelzoom back to you.  Some of the results seem odd to me (Win 10 chrome) but I don't see any major differences between versions.

**Comment by pixelzoom** [comment]
Win10 + Chrome "odd results" move to #146.

Otherwise we've determined that the performance is only impacted with `?ea`, which we can live with. So closing.
