### ISSUE TITLE
inconsistent layering of stop watch and collision counter

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/gas-properties#148]
**Test Device**

MacBook Air

**Operating System**

macOS 10.14.5

**Browser**

Chrome 75.0.3770.142

**Problem Description**

For https://github.com/phetsims/QA/issues/386. If you're dragging a tool over another tool, the tool that is being dragged isn't necessarily the one that's "on top." The tool that is being dragged should be on top.

**Visuals**

Gas Properties (1.0.0-rc.1)
![issue1](https://user-images.githubusercontent.com/31285590/62086666-5a942f00-b21c-11e9-8283-545dda4a2436.gif)

Masses and Springs: Basics (published)
![issue2](https://user-images.githubusercontent.com/31285590/62086683-6122a680-b21c-11e9-9f3d-6bd905f03600.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Gas Properties‬
URL: https://phet-dev.colorado.edu/html/gas-properties/1.0.0-rc.1/phet/gas-properties_all_phet.html
Version: 1.0.0-rc.1 2019-07-29 20:25:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by lmulhall-phet** [comment]
@pixelzoom, I also found this:

![issue3](https://user-images.githubusercontent.com/31285590/62088501-c5486900-b222-11e9-922d-886baad4d547.gif)

Hence the title change. Let me know if I should make a separate issue. (The pressure with variable temperature radio button needs to be active to reproduce.)

**Comment by pixelzoom** [comment]
This is intentional for these particular tools.  It ensures that the stopwatch can't be lost behind the collision counter.  @arouinfar please advise whether you'd like me to change this.

**Comment by pixelzoom** [comment]
To clarify...  Relative layering of the stopwatch and collision counter is intentional. Dragging behind the bucket is not intentional.

**Comment by lmulhall-phet** [comment]
@arouinfar asked me to make this issue.

I've found a few published sims where there are tools that can be "lost" behind larger tools, such as [Wave Interference](https://phet.colorado.edu/sims/html/wave-interference/latest/wave-interference_en.html) where the tape measure can be lost behind the timer.

**Comment by lmulhall-phet** [comment]
To be clear, I'm not saying that losing small tools behind larger tools is ideal, just that there is precedent for this and (I assume) this was discussed by designers at some point.

**Comment by pixelzoom** [comment]
If we decide to make tools (the stopwatch and collision counter) pop to the front in pointer down, then we should probably also make tools pop to the front when their associated checkbox becomes checked.  For example, if the stopwatch is invisible and behind the collision counter, then it should become visible and pop to the front when the "Stopwatch" checkbox is checked.

**Comment by arouinfar** [comment]
> This is intentional for these particular tools. It ensures that the stopwatch can't be lost behind the collision counter.

You make a good point, but I think it looks odd to drag the Collision Counter behind the TimerNode. I would prefer the active tool has the top-most z-ordering.

> If we decide to make tools (the stopwatch and collision counter) pop to the front on pointer down, then we should probably also make tools pop to the front when their associated checkbox becomes checked. 

Agreed, I think this would be better UX.

**Comment by pixelzoom** [comment]
Fixed in master and 1.0 branches.  Stopwatch and Collision Counter now move to the front on pointer down, and when they become visible.  

@lmulhall-phet please verify in master.

**Comment by lmulhall-phet** [comment]
Looks good on master, @pixelzoom.

**Comment by pixelzoom** [comment]
To be verified in 1.0.0-rc.2.

**Comment by lmulhall-phet** [comment]
Sorry, @pixelzoom, I just noticed this:

![Screen Shot 2019-07-30 at 3 04 06 PM](https://user-images.githubusercontent.com/31285590/62165324-67c42300-b2db-11e9-94ab-26c0f679da1a.png)
 
Also, the cursor doesn't turn into a hand when you mouse over the collision counter as it does with the timer.

**Comment by pixelzoom** [comment]
Ah, right.  The counter needs to stay behind the parent for the combo listbox. 

On what platform does the cursor not turn into a hand on mouseOver?

**Comment by lmulhall-phet** [comment]
macOS + Chrome, same as the original issue.

**Comment by lmulhall-phet** [comment]
The cursor doesn't turn into a hand unless it's on top of a button, which is not the case with the timer.

![issue](https://user-images.githubusercontent.com/31285590/62165959-d81f7400-b2dc-11e9-9401-7b21af0c6e5a.gif)

![issue2](https://user-images.githubusercontent.com/31285590/62165972-de155500-b2dc-11e9-870d-fa71309ecff7.gif)

**Comment by pixelzoom** [comment]
Fixed the counter's cursor and listbox layering in master and 1.0 branches.  Good catch @lmulhall-phet, please verify in master.

**Comment by lmulhall-phet** [comment]
Both the cursor issue and the listbox issue look fixed on master.

**Comment by pixelzoom** [comment]
👍 To be verified in 1.0.0-rc.2.

**Comment by lmulhall-phet** [comment]
Looks good in 1.0.0-rc.2.

**Comment by KatieWoe** [comment]
Noticed this behavior when you open a dropdown while one of the objects is on top.  Probably acceptable, but leaving up to you @pixelzoom @arouinfar.  Please close if acceptable.
![haha](https://user-images.githubusercontent.com/41024075/62381326-76dbe880-b508-11e9-8295-e970b0472d65.png)

**Comment by pixelzoom** [comment]
Combobox listbox typically uses a layer that's in front of everything else (similar to Dialogs).  So that's what is causing this.  This is easy to change, so I'm going to address it.

**Comment by pixelzoom** [comment]
Actually...  I'm not going to change this.   This is the current PhET policy for ComboBox listbox, and it's what you'll see (or should see, if the policy is being followed) in other sims.  Changing that policy requires a more extensive discussion, as well as addressing several Dialog-related GitHub issues in the sun repo.   So if it's OK with @arouinfar, I recommend that we leave this as is, and close this issue.

**Comment by pixelzoom** [comment]
On second thought, I am going to address this.  

I also noticed another issue -- if you click on some interactive part of the stopwatch or collision counter (e.g. the play button), it does not move the tool to the front.

**Comment by pixelzoom** [comment]
It's also not possible to drag the Collision Counter by grabbing the bezel around it's outer edge.

**Comment by pixelzoom** [comment]
Fixed in master and 1.0.  Summary:

* ComboBox listboxes remain associated with their related UI component in the layering order. It's not possible to (for example) get the Stopwatch layered between the thermometer and its listbox.
* Clicking anywhere on the stopwatch or collision counter, even on interactive subcomponents, moves it to the front.
* You can drag the stopwatch and collision counter anywhere on their background, but not on their interactive subcomponents.
* The bezel is now part of the collision counter's background, and you can drag it.
* All text labels on the collision counter are `pickable:false`, so that they don't inhibit dragging.

@KatieWoe please verify in master.

**Comment by KatieWoe** [comment]
Confirmed in master.  Although I did find
>All text labels on the collision counter are `pickable:false`, so that they don't inhibit dragging.

a bit odd.

**Comment by pixelzoom** [comment]
@KatieWoe why is that odd? Do you think the tools should not be draggable if you happened to click on (for example) "Wall Collisions".

**Comment by KatieWoe** [comment]
This part isn't interactive (clicking on it doesn't change anything that I could find) but the mouse still makes the hand symbol that indicates it can be dragged/interacted with.  I think I misunderstood what you meant when I quoted that.  Sorry.  I think that clicking on "Wall Collisions" etc. should allow dragging.

**Comment by pixelzoom** [comment]
Discussed with @KatieWoe on Slack to clarify https://us04web.zoom.us/j/530972694, and we're all good here.   

To be verified in 1.0.0-rc.3.

**Comment by pixelzoom** [comment]
To summarize what needs to be verified in 1.0.0-rc.3:

* Click anywhere on the stopwatch or collision counter to move it to the front.
* Check the associated checkbox to move the stopwatch or collision counter to the front.
* Drag anywhere on the stopwatch or collision counter to move it, except on interactive subcomponents (buttons, ComboBox). 
* Verify that you can't put something (e.g. the stopwatch) between a ComboBox's button and listbox.

**Comment by lmulhall-phet** [comment]
**1.0.0-rc.3**

- [x] Click anywhere on the stopwatch or collision counter to move it to the front.
- [x] Check the associated checkbox to move the stopwatch or collision counter to the front.
- [x] Drag anywhere on the stopwatch or collision counter to move it, except on interactive subcomponents (buttons, ComboBox).
- [x] Verify that you can't put something (e.g. the stopwatch) between a ComboBox's button and listbox.

Looks good 👍!
