### ISSUE TITLE
Oops! dialog should interrupt any interactions that are in progress

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#149]
**Test device**
Dell Laptop
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/386 and https://github.com/phetsims/QA/issues/388
If you are interacting with an element when the max temp dialog (introduced in https://github.com/phetsims/gas-properties/issues/128) comes up, that aspect can still be manipulated.  Elements can include the heat bucket or the wall (anything that raises the temperature past the max).  Once you let go of the element, the dialog behaves as normal (clicking outside it will close it, etc.)
**Steps to reproduce**
1. Put in one atom so max temp can be reached without losing lid
2. Raise temp to close to 100000
3. Choose either the heat bucket or the wall, and use it to raise temp that bit
4. When dialog comes up, do not let go of slider/wall.  Continue to manipulate it

**Visuals**
![stillmovingthebucket](https://user-images.githubusercontent.com/41024075/62141064-392d5480-b2a9-11e9-86db-f3e2ed5e576c.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gases Intro‬
URL: https://phet-dev.colorado.edu/html/gases-intro/1.0.0-rc.1/phet/gases-intro_all_phet.html
Version: 1.0.0-rc.1 2019-07-29 21:24:26 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
Opening a modal Dialog should interrupt all other interactions that are in progress.  I could do that specifically for the Oops! dialogs in this sim.  But I think this is something that should potentially be in common code, perhaps a responsibility of Dialog.  @arouinfar do you agree?

**Comment by pixelzoom** [comment]
I'm going to change the title of this issue to reflect the more general problem.

**Comment by arouinfar** [comment]
> Opening a modal Dialog should interrupt all other interactions that are in progress. 

👍 

> I could do that specifically for the Oops! dialogs in this sim. But I think this is something that should potentially be in common code, perhaps a responsibility of Dialog. @arouinfar do you agree?

Agreed. I think we would want to handle this in common code, not in a sim-specific way.

**Comment by pixelzoom** [comment]
I talked with @ariel-phet about how to proceed on this one.  Solving this in common code is likely to take a long time, involving other Dialog-related issues, and requiring much discussion.  I also suspect that there will not be immediate agreement that this should be handled by Dialog.  

So I'm going to address this issue by:
(1) Creating an issue in the sun repo for the general issue of how interactions should be a affected when a modal Dialog is opened.
(2) Add sim-specific code to Gas Properties that cancels all interactions when a modal Dialog is opened.

**Comment by pixelzoom** [comment]
Fixed in master and 1.0 branches.  When an Oops! dialog is opened, any in-progress interactions are cancelled.  

@KatieWoe please verify in master.

**Comment by KatieWoe** [comment]
I did a quick check on all of the possible Oops! dialogs per request in slack.  All seem good in master.  Interestingly, I noticed some passed in the rc already that I thought would fail.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.

To be verified in 1.0.0-rc.2.

**Comment by pixelzoom** [comment]
@KatieWoe to clarify.... Did you also verify this issue, that all in-progress interactions are now cancelled when an Oops dialog opens?

**Comment by KatieWoe** [comment]
As many as I could come up with, yes.

**Comment by pixelzoom** [comment]
👍 To be verified in 1.0.0-rc.2.

**Comment by KatieWoe** [comment]
Looks good rc.2
