### ISSUE TITLE
Particles escape from closed container

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#15]
From the [SwingJS Notes](https://docs.google.com/document/d/1aGmLksuZrlVZf6GgeSJdIm4CcHHofqICzP5V4PNKhCQ/edit) in #5:

> In idealgas.controller.PumpControlPanel the loop

```
        	if( box.containsPt( molecule.getPosition() ) != isInBox ) {
            		isInBox = !isInBox;
            		spinner.updateValue();
        	}
```

> needed to check that the box was actually open. Otherwise, particles can “tunnel” through the box walls.
```
if( box.isOpen() && box.containsPt( molecule.getPosition() ) != isInBox ) { // BH BUG FIX don't notify
       	 // if box is closed; we will correct this later in IdealGasModel.  
            	isInBox = !isInBox;
            	spinner.updateValue();
        }
```
@samreid commented:
> This seems like a good fix, but I’m not sure what kept the particles in the box without it.

Another one for @pixelzoom.

**Comment by pixelzoom** [comment]
Noted. Unassigning until development begins.

**Comment by arouinfar** [comment]
This bug has also been reported by two users in [Unfuddle ticket #578](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/578).

User 1:
> Second, however, is a small bug. If I manually set the simulation to  
1,000 light species (a semi-ridiculous number), I can see the molecules  
actually moving outside the inner wall of the box. Although I can't see  
any escaping the number inside to box according to the text box is  
decreasing. It stabilises at ~558 molecules. Adding heat re-introduces  
the behavior. Large numbers of heavy species molecules exhibits the same  
behavior, but not quite as badly.
I ran it and indeed the number does seem to be decreasing.  If that's intended we can just tell the user that otherwise it's a bug.

User 2:
> I am a high school physics teacher and am using the Gas Laws simulation in my class this week. We have found that we are having trouble keeping the number of molecules constant. It seems to be decreasing when we try to keep it constant. Is there a way to fix this?

To reproduce:
1. On startup, add 1000 light species
2. Once the particles begin to collide with the container walls, the particle count will rapidly decline, and some will visibly tunnel through the container walls:
![image](https://user-images.githubusercontent.com/8419308/36746537-cc49814a-1baf-11e8-8cf2-2aa738e76eec.png)
![image](https://user-images.githubusercontent.com/8419308/36746553-d9780148-1baf-11e8-9eb3-2c672e300c3e.png)
![image](https://user-images.githubusercontent.com/8419308/36746595-f28fffd2-1baf-11e8-95e5-22866641bbcb.png)

**Comment by arouinfar** [comment]
More bug reports in [Unfuddle ticket #690](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/690):

User 3:
> I am a secondary school teacher in Sweden. I find the simulation program
Gas Properties very useful and enjoyable! But there is one feature of
the program that is disturbing for quantitative investigations: the
chamber is loosing molecules all the time - it´s leaking! The number of
molecules inside goes down a little during an investigation. Do you know
that? Is that on purpose, or a bug?

Julia C:
>I've been working on an activity with Gas Properties to give to my students.  While I was writing it, I noticed that as I used the sim, the number of particles decreased.  I set up an experiment and just let the sim run with 100 particles Heavy and 100 particles Light, and after 5 minutes over 1/4 of my particles had vanished.
I know this sim is not a priority and that it has outstanding issues we plan to fix later, but I am concerned that this sort of behavior will make teachers not want to use this sim.
Chris, is this in the realm of "we decided not to fix it right now", or is this a bug we didn't know about yet?

@pixelzoom replied to Julia:
> I don't know if it's a known problem. I do know that this sim has serious problems, and that the original developer is no longer with PhET.  I've fixed a few minor issues with it, and each such experience has been painful and expensive.  I recommend creating an Unfuddle ticket for what you're experiencing, and we can evaluate it at the next status meeting.

@oliver-phet commented 3 weeks ago:
> This issue was reported by another user

**Comment by pixelzoom** [comment]
@arouinfar FYI... It's worth noting that the particle counts are totally different in the HTML5 design and implementation.  Counts are the number of particles that exist (inside or outside the container), not the number of particles in the container.   So if the container did leak, it would not be reflected in the particle counts.

**Comment by pixelzoom** [comment]
1.0.0-dev.4 indicates that no particles are leaking from the container.  And I've added safeguards to notice if that happens.  So closing this issue.
