### ISSUE TITLE
Multiple Oops! dialogs at once

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#150]
**Test device**
Dell Laptop
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/386 and https://github.com/phetsims/QA/issues/388.
It is possible to trigger two "Oops!" dialogs at once, causing one to be layered on top of the other.  Not certain if this is a bug, but it can look a bit odd, so recording here.
**Steps to reproduce**
1. Raise temperature near max (one particle works best
2. If box is not small already, the decrease volume while temp is constant
3. Change to keep pressure constant with temp changing
4. Make box bigger

**Visuals**
![twodialogs](https://user-images.githubusercontent.com/41024075/62143859-0c2f7080-b2ae-11e9-990d-858cb294d966.png)
![twodialogstwo](https://user-images.githubusercontent.com/41024075/62143861-0c2f7080-b2ae-11e9-9260-95802bd0b7ca.png)
![twodialogsvideo](https://user-images.githubusercontent.com/41024075/62143862-0c2f7080-b2ae-11e9-8b31-a12b1bf65cd1.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gas Properties‬
URL: https://phet-dev.colorado.edu/html/gas-properties/1.0.0-rc.1/phet/gas-properties_all_phet.html
Version: 1.0.0-rc.1 2019-07-29 20:25:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
@KatieWoe could you please clarify this step for me, I can't parse.

> 2. If box is not small already, the decrease volume while temp is constant

Do you mean "then decrease the container volume"?

And does "while temp is constant" mean "Hold Constant" need to be set to "Volume"?  That's not shown in the screenshots.

**Comment by KatieWoe** [comment]
@pixelzoom 
Yes.  If the volume is not already small, make it small while the third option (holding temperature constant) is selected.  This is what is shown in the first step of the screenshots.  The next step is 
> Change to keep pressure constant with temp changing
Which is the next step shown in the gif

**Comment by pixelzoom** [comment]
Definitely a bug, unassigning @arouinfar.

**Comment by pixelzoom** [comment]
This is specific to the "Maximum temperature reached" condition, which was added in https://github.com/phetsims/gas-properties/issues/128#issuecomment-506109595.   The problem is that, when this condition occurs, we are removing all particles, then adjusting the "Hold Constant" setting.  We need to adjust the "Hold Constant" setting first.  The relevant code is in IdealGasLawModel:

```js
      // If the maximum temperature was exceeded, reset the state of the container.
      // See https://github.com/phetsims/gas-properties/issues/128
      if ( this.temperatureModel.temperatureProperty.value >= GasPropertiesQueryParameters.maxTemperature ) {

        // Remove all particles
        this.particleSystem.removeAllParticles();

        // Switch to a 'Hold Constant' setting that supports an empty container
        if ( this.holdConstantProperty.value !== HoldConstant.NOTHING &&
             this.holdConstantProperty.value !== HoldConstant.VOLUME ) {
          this.holdConstantProperty.value = HoldConstant.NOTHING;
        }

        // Put the lid on the container
        this.container.lidIsOnProperty.value = true;

        // Notify listeners that maximum temperature was exceeded.
        phet.log && phet.log( `Oops! Maximum temperature reached: ${this.temperatureModel.temperatureProperty.value}` );
        this.oopsEmitters.maximumTemperatureEmitter.emit();
      }
```

**Comment by pixelzoom** [comment]
Fixed in master and 1.0 branch.  @KatieWoe please verify in master.

**Comment by KatieWoe** [comment]
Confirmed in master

**Comment by pixelzoom** [comment]
To be verified in 1.0.0-rc.2.

**Comment by KatieWoe** [comment]
looks good rc.2
