### ISSUE TITLE
Options checkbox labels have different maxWidths

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#152]
**Test device**
Dell Laptop
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/386, https://github.com/phetsims/QA/issues/388, and possibly https://github.com/phetsims/QA/issues/387, depending on the size decided on.
The max width/size of the options in the options menu are different.
**Steps to reproduce**
1. Set stringTest=long
2. Go the Options in the PhET menu

**Visuals**
![optionboxsize](https://user-images.githubusercontent.com/41024075/62154491-0ba1d480-b2c4-11e9-97b1-77a162210133.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/gas-properties/1.0.0-rc.1/phet/gas-properties_all_phet.html?stringTest=long
Version: 1.0.0-rc.1 2019-07-29 20:25:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
This will involved setting `maxTextWidth` for ProjectorModeCheckbox.

**Comment by pixelzoom** [comment]
Checkbox labels in the Options dialog now have uniform maxWidth, see screenshot below.  Fixed in master and 1.0 branches.

@KatieWoe please verify in master.

<img width="820" alt="screenshot_1293" src="https://user-images.githubusercontent.com/3046552/62160831-182d2980-b2d2-11e9-9272-e56d3d030970.png">

**Comment by KatieWoe** [comment]
Confirmed in master

**Comment by pixelzoom** [comment]
To be verified in 1.0.0-rc.2.

**Comment by KatieWoe** [comment]
Looks good rc.2
