### ISSUE TITLE
"Oops Dialog" table is out of date in design doc

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#153]
In https://github.com/phetsims/gas-properties/issues/128, we added the Oops dialog shown below that is not included in the "Oops Dialog" table in the Google design document.  This is important to keep up to date for QA.

<img width="559" alt="screenshot_1260" src="https://user-images.githubusercontent.com/3046552/60227661-2cf34900-985e-11e9-902b-ee8bde7cf2e4.png">

**Comment by arouinfar** [comment]
Done
