### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#154]
For https://github.com/phetsims/QA/issues/386 and #1 
This sim is being published for the first time, and so it needs screenshots and alt screenshots.  @arouinfar let me know what you would like them to look like and when you think the sim is settle enough to take them, then assign back to me.

**Comment by arouinfar** [comment]
@KatieWoe please take screenshots during rc.2.

### Main screenshot
![Gas Properties-1](https://user-images.githubusercontent.com/8419308/62252404-fbffba00-b3af-11e9-8574-9f8abc4a13ba.png)

### Alt 1
<img width="1440" alt="Gas Properties-2" src="https://user-images.githubusercontent.com/8419308/62252405-fbffba00-b3af-11e9-9afa-2ae28fd2716b.png">

### Alt 2
Use equal numbers of light and heavy particles.
![Gas Properties-3](https://user-images.githubusercontent.com/8419308/62252406-fbffba00-b3af-11e9-9753-c2fe559511db.png)

### Alt 3
Use particles with different radii, and take screenshot as they start to mix.
![Gas Properties-4](https://user-images.githubusercontent.com/8419308/62252407-fc985080-b3af-11e9-93ab-aa6366a939bb.png)

**Comment by KatieWoe** [comment]
Here are the screenshots for this sim:
![gas-properties-screenshot](https://user-images.githubusercontent.com/41024075/62326739-0b443d80-b46c-11e9-882f-5a20b1d8c334.png)
![gas-properties-screenshot-alt1](https://user-images.githubusercontent.com/41024075/62326741-0b443d80-b46c-11e9-9210-87474630a62d.png)
![gas-properties-screenshot-alt2](https://user-images.githubusercontent.com/41024075/62326742-0b443d80-b46c-11e9-924a-5bde1f8058ce.png)
![gas-properties-screenshot-alt3](https://user-images.githubusercontent.com/41024075/62326743-0b443d80-b46c-11e9-8b35-273fb35e714a.png)

**Comment by KatieWoe** [comment]
@arouinfar to approve

**Comment by arouinfar** [comment]
Looks good, thanks!

**Comment by KatieWoe** [comment]
Added screenshots to master and 1.0.  @pixelzoom are they needed in any other branch?  If not, this can be closed.

**Comment by pixelzoom** [comment]
master and 1.0 are all that's needed.  Thanks @KatieWoe. Closing.
