### ISSUE TITLE
Collision Counter is interupted

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#155]
**Test device**
Dell Laptop
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/386 and https://github.com/phetsims/QA/issues/388
Not sure if this is a bug or intended behavior.  If intended, feel free to close.  When you adjust the volume of the container while the collision counter is running, it will go to zero and stop counting.  This does not happen if you adjust the volume after it is done counting, adjust another parameter such as temperature while counting, or allow volume to change by itself while counting.
**Steps to reproduce**
1. Go to the Ideal screen
2. Get the collision counter out
3. Put a number of particles in the container
4. Start the counter
5. While it is going, move the wall of the container

**Visuals**
https://drive.google.com/file/d/1-SrEhjBhALNDjRGQL8MRqGcELQgXP4-P/view?usp=sharing

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gas Properties‬
URL: https://phet-dev.colorado.edu/html/gas-properties/1.0.0-rc.1/phet/gas-properties_all_phet.html?showPointerAreas
Version: 1.0.0-rc.1 2019-07-29 20:25:10 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
My understanding is that this it the desired behavior. But @arouinfar please confirm.

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

While I don't remember making an explicit design decision to abort the Collision Counter when the container is resized (though I may have), I think this feels pretty natural. Changing V kicks the sim into a paused state, and it doesn't make sense to continue counting the particle-wall collisions.
