### ISSUE TITLE
Width string can be too long

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#156]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Edge (and others)
**Problem description**
For https://github.com/phetsims/QA/issues/386 and https://github.com/phetsims/QA/issues/388
The width string that measures the size of the container does not have a max width.
From slack:
>Amy Rouinfar 1:39 PM
No, it needs a proper maxWidth

**Visuals**
![normal](https://user-images.githubusercontent.com/41024075/62243002-aa4c3500-b399-11e9-8042-9a293a0c6460.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/gas-properties/1.0.0-rc.1/phet/gas-properties_all_phet.html?stringTest=long
Version: 1.0.0-rc.1 2019-07-29 20:25:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362
Language: en-US
Window: 1536x751
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Microsoft (Microsoft Edge)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
Fixed in master and 1.0 branches.  @KatieWoe please verify in master.

**Comment by KatieWoe** [comment]
Looks good to me

**Comment by pixelzoom** [comment]
To be verified in 1.0.0-rc.2.

**Comment by KatieWoe** [comment]
Looks good rc.2
