### ISSUE TITLE
branch: sprites

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/gas-properties#157]
For the semi-experimental work related to https://github.com/phetsims/scenery/issues/990.

**Comment by pixelzoom** [comment]
@jonathanolson can I delete this branch?

**Comment by jonathanolson** [comment]
Has it been effectively included in master? Otherwise presumably this work could be an improvement?

**Comment by pixelzoom** [comment]
The changes that you made in this branch are in https://github.com/phetsims/gas-properties/commit/cdb2888465ba839641de6e25e53cc3c271ce65c9.   Basically you changed the implementation of ParticlesNode from CanvasNode to Sprites.  There have been no reports of performance problems in Gas Properties, so I'm not sure if it's worth the effort (and risk?) to switch from CanvasNode (Canvas) to Sprites (WebGL with Canvas fallback). 

If we are going to consider this change in the future, I'm including to create a new issue, and include https://github.com/phetsims/gas-properties/commit/cdb2888465ba839641de6e25e53cc3c271ce65c9 as a possible patch. I don't see the need for an entire branch for a change to 1 file that we may never make.

@jonathanolson your opinion on how to proceed?

**Comment by pixelzoom** [comment]
The other options is of course to just merge the ParticlesNode changes into master now, and delete this branch.

**Comment by pixelzoom** [comment]
This branch was created before the conversion to ES6 modules, so there's going to be some manual work involved in merging.

**Comment by pixelzoom** [comment]
In the above commits, I converted ParticlesNode to Sprites, enabled webgl for all 3 sims in this suite, and cleaned up some cruft that wasn't addressed in cdb2888.   Performance with looks good, and `?profiler` is showing 60FPS on my MacBook Pro and iPad6. 

I'd still be interested in hearing from @jonathanolson about whether he expects this to be a "win", since performance wasn't a problem with CanvasNode.

**Comment by jonathanolson** [comment]
That sounds great! Thank you.

I could imagine it could be helpful on slower platforms, and it seems more maintainable than CanvasNode in general (so I believe it's also a code win).

**Comment by jonathanolson** [comment]
Sounds perfect, and removing the branch now.

**Comment by pixelzoom** [comment]
Due to https://github.com/phetsims/special-ops/issues/196#issuecomment-823486502, this branch was restored.  It will need to be deleted again.  Reopening and self assigning.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
