### ISSUE TITLE
only the lid's handle should be interactive

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#161]
While working on https://github.com/phetsims/gas-properties/issues/159, I discovered that the entire lid (not just its handle) is interactive.   This feels really odd/buggy, and it's also problematic because you can still resize the lid if its handle is hidden.  So with @arouinfar's approval, I will change it so that only the handle is interactive.  

This should be addressed for 1.0.0 release.

**Comment by pixelzoom** [comment]
Since this is a prerequisite to #159, I went ahead and pushed this change to master and 1.0 branches. @arouinfar and @KatieWoe please review in master.

**Comment by KatieWoe** [comment]
Looks good in master

**Comment by arouinfar** [comment]
This sounds reasonable to me @pixelzoom. The handle doesn't have visible pointer areas so I would want to make sure the touch area is reasonably dilated, similar to the `BicyclePumpNode` handle.
![image](https://user-images.githubusercontent.com/8419308/62654266-a762be80-b91c-11e9-8716-2c4edd083b62.png)

**Comment by pixelzoom** [comment]
Pushed to master and 1.0 branches. The handle's `touchArea` is now dilated by (25,20) -- that's x and y dilation.   See screenshot below.   @arouinfar please review.

<img width="838" alt="screenshot_1301" src="https://user-images.githubusercontent.com/3046552/62655506-5d2f0c80-b91f-11e9-9877-9fe21a3e77df.png">

**Comment by arouinfar** [comment]
@pixelzoom the screenshot in https://github.com/phetsims/gas-properties/issues/161#issuecomment-519256112 looks good to me, and the handle is easy to move on my phone.

**Comment by pixelzoom** [comment]
Great.  To be verified in 1.0.0-rc.3.

**Comment by KatieWoe** [comment]
Looks good rc.3
