### ISSUE TITLE
Update design doc for Hold Constant mode “Temperature (T)”

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#162]
In #159, we made a number of design changes related to Hold Constant mode “Temperature (T)”.  @arouinfar do you think the design doc should be updated to reflect these changes? The design doc is otherwise up-to-date, which is nice. 

This is not a prerequisite for publishing 1.0.0, it can be done at any time.

**Comment by arouinfar** [comment]
Done.
