### ISSUE TITLE
Exiting Fullscreen on Safari Does Not Resize Immediately 

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/gas-properties#163]
**Test device**
MacBook Air
**Operating System**
macOS 10.14.6
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/399. On macOS 10.14.6 on Safari I have noticed some problems when a large amount of particles are present and full screen mode is exited. The behavior of this problem differs from time to time and sometimes it has little or no impact on the sim performance. When the bug occurs the time to properly resize can take as little as half a second and as long as two minutes. During this time when the sim has not resized the whole sim area is unusable and Safari seems to be frozen (other Safari tabs can not be selected, the page can not be reloaded, the search bar becomes unusable, and the Safari app can not be closed or minimized). This becomes particularly problematic when the extreme times to resize occur as the sim and whole browser become unusable until the issue is resolved. As mentioned before the bug is not consistent and given the same conditions the time to resize can vary greatly from one occurrence to the next. Using the iFrame or XHTML versions of the sim seems to increase the time to resize but the base sim also experiences this problem. What I have found is that as a general rule the more complex the sim becomes the longer it takes to resize, which is why I have not noticed the issue on the "Diffusion" screen yet. I have done some testing on other sims with lots of moving parts such as "States of Matter" and the same issue occurs, however the sim resizes very quickly (about half a second), most likely due to the smaller amount of particles present in SoM. This makes me think that this might be a scenery issue that is present in many sims but for now I'll keep it here and leave that decision to the devs. So far this bug has only been seen on Safari (I have tested on macOS Chrome, and Windows 10 Edge, Firefox, and Chrome). 

**Steps to reproduce**
1. Go to "Ideal", "Explore", or "Energy" screens (it might happen on the "Diffusion" screen but the time to resize is so small that I have yet to see this bug occur on this screen)
2. Enter full screen mode
3. Add the maximum amount of particles (1000 of each, you might have to decrease the temp to ensure the lid does not pop off)
4. Add all other options such as Width, Stopwatch, Collision Counter, Speed and KE (where applicable)
5. Exit full screen using either the PhET menu or "esc" button
6. The sim should take a bit to resize (again the time to resize varies from time to time)
7. While the sim has not resized (refer to visual for example of resizing issue) click anywhere on the sim or Safari window, nothing should be able to be clicked or manipulated.

**Visuals**
![Screen Shot 2019-08-09 at 11 13 26 AM](https://user-images.githubusercontent.com/30352536/62797456-02b9bb80-ba99-11e9-92a5-5e1ff80c0a45.png)

</details>

**Comment by pixelzoom** [comment]
Thanks @JRomero0613.

Fullscreen is a general feature, and there's nothing sim-specific related to it in Gas Properties.  And as you noted, the problem occurs with other sims (e.g. SOM) to various degrees, depending on sim complexity. 

I have no familiarity with this feature, and no idea why the behavior described above would occur. This will probably require investigation by @jonathanolson.  

Assigning to @ariel-phet to decide whether addressing this issue is a prerequisite to publishing 1.0.0.

**Comment by JRomero0613** [comment]
This also occurs on both Gases Intro screens with similar effects (time to resize differs greatly from time to time). The console does not give me any errors so I think it might be a purely performance based issue.

**Comment by pixelzoom** [comment]
@JRomero0613 if the sim is paused, does the problem go away?

**Comment by KatieWoe** [comment]
Yes, pausing does seem to help/solve the problem.  A few things I found in addition: leaving using the phet menu also causes the problem, going to another browser such as chrome seems to solve it.

**Comment by pixelzoom** [comment]
I propose that we publish 1.0.0 with this as a known problem.  Then create a joist issue to investigate the general problem, followed by a batch maintenance release for all affected sims.  @ariel-phet is that acceptable?

**Comment by ariel-phet** [comment]
@pixelzoom quite acceptable. I think the main use case is entering full screen, exiting full screen is not too much of a worry to me if you are exiting full screen after having used the sim.

I agree to go ahead and make a joist issue (please assign to me for the time being), but I do not necessarily feel this is worthy of a batch maintenance release, perhaps when we fix the issue just have it in master going forward.

**Comment by pixelzoom** [comment]
I've create issue https://github.com/phetsims/scenery/issues/993 to track the general problem.

Since will not be fixed for 1.0.0 or in a maintenance release, I'm going to close this issue as "won't fix".
