### ISSUE TITLE
Particle size is incorrect

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#18]
From the [SwingJS Notes](https://docs.google.com/document/d/1aGmLksuZrlVZf6GgeSJdIm4CcHHofqICzP5V4PNKhCQ/edit) in #5:

> Particle radii are being read from GasMolecule.getRadius(), but this reads only the static reference s_radius in that class, not the actual ones in HeavySpecies or LightSpecies. Also, these are listed as 5 and 3.5, respectively, but they are really 4 and 2.5. That change is quite visible especially for light particles, which now cleanly bounce off the walls and each other:
![image](https://user-images.githubusercontent.com/8419308/36704029-a954a212-1b1b-11e8-97cb-db1504b7e149.png)
In the downloadable Java version one can see this quite clearly at low temperature, where there appears to be a layer between the particles and the walls. But that is just because the sphere-box collider consider the light spheres to have radius 5, when they actually have radius 2.5.
![image](https://user-images.githubusercontent.com/8419308/36704032-b0cb2c00-1b1b-11e8-8c11-f390c226ae85.png)

Tagging @pixelzoom so he's aware.

**Comment by pixelzoom** [comment]
This has already been addressed in the HTML5 implementation.  Each particle type has its own radius, and there is nothing like `s_radius`.   So closing.
