### ISSUE TITLE
State wrapper opens lid when moving wall

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#180]
For ES6 testing.
When moving the wall in the top sim, the bottom sim seems to open the box lid. This can lead to error messages that don't go away (as shown bellow) and the bottom sim crashing and no longer moving. 
![confusedlid](https://user-images.githubusercontent.com/41024075/76255503-e428c800-6213-11ea-9ea8-58238734f139.gif)

**Comment by pixelzoom** [comment]
@KatieWoe FYI, this sim has not been through PhET-iO design (see #30) and is not ready for PhET-iO testing.  You can continue to test if you'd like, but issues will not be immediately addressed.

**Comment by pixelzoom** [comment]
This is no longer a problem, undoubtedly fixed by fleshing out the PhET-iO implementation in #30 and #77.

Closing.
