### ISSUE TITLE
CT: bad holdConstant state

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#182]
Another CT failure related to restoring PhET-iO state.  This one alternates with #181 and #178.  Since it's related to the "Hold Constant" feature, it almost certainly occurs in gases-intro, but not in diffusion.

```
gas-properties : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1583918210254/phet-io-wrappers/state/?sim=gas-properties&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: bad holdConstant state: TEMPERATURE with numberOfParticles=0
Error: Assertion failed: bad holdConstant state: TEMPERATURE with numberOfParticles=0
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583918210254/assert/js/assert.js?bust=1583926228756:22:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583918210254/gas-properties/js/common/model/IdealGasLawModel.js:226:17
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1583918210254/axon/js/TinyEmitter.js:65:53)
    at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1583918210254/axon/js/Property.js:276:25)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583918210254/axon/js/Property.js:326:47
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583918210254/phet-io/js/PhetioStateEngine.js:188:42
    at Array.forEach (<anonymous>)
    at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/snapshot-1583918210254/phet-io/js/PhetioStateEngine.js:188:13)
    at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/snapshot-1583918210254/phet-io/js/PhetioEngineIO.js:200:43)
    at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/snapshot-1583918210254/phet-io/js/phetioCommandProcessor.js:264:51)
id: Bayes Chrome
Approximately 3/11/2020, 3:16:50 AM
```

Since the stack trace doesn't identify anything the specific Property, I'll need to use the technique described in https://github.com/phetsims/gas-properties/issues/181#issuecomment-597298024 to identify the phetioID of the Property that's being set.

**Comment by pixelzoom** [comment]
Assertion failure is here in IdealGasLawModel.js:

```js
    // Verify that we're not in a bad 'Hold Constant' state.
    assert && this.holdConstantProperty.link( holdConstant => {

      // values that are incompatible with an empty container
      assert && assert( !( this.particleSystem.numberOfParticlesProperty.value === 0 &&
      ( holdConstant === HoldConstant.TEMPERATURE ||
        holdConstant === HoldConstant.PRESSURE_T ||
        holdConstant === HoldConstant.PRESSURE_V ) ),
        `bad holdConstant state: ${holdConstant} with numberOfParticles=${this.particleSystem.numberOfParticlesProperty.value}` );

```

My guess is that `holdConstantProperty` is being restored before `numberOfParticlesProperty` (or visa versa).   This is probably another place where we need to check `phet.joist.sim.isSettingPhetioStateProperty.value`.   

But the more general issue is that this sim (and I suspect most sims) were not designed to have their Properties restored in any order other than the runtime order.  And I suspect that other sims are not hitting this because of their general lack of assertions like the one above.  I'm not looking forward to adding `phet.joist.sim.isSettingPhetioStateProperty.value` all over the place in sims, and I don't think that's a great solution.

**Comment by pixelzoom** [comment]
@samreid, @chrisklus, and I worked on the general problem via Zoom.  See discussion in https://github.com/phetsims/axon/issues/276#issuecomment-597779549.

**Comment by zepumph** [comment]
https://github.com/phetsims/gas-properties/commit/c8218e894bb6e0ba8289a16abc0b424f86caf8ad was added as part of https://github.com/phetsims/axon/issues/276, and this bug should now be fixed in master. See details of this support over in https://github.com/phetsims/axon/issues/276#issuecomment-618106191. @pixelzoom please confirm fixed, review the above commit, and close if all is well.

**Comment by pixelzoom** [comment]
I don't see this occurring in CT, and the commit looks great.  Thanks for handling this!  Closing.
