### ISSUE TITLE
DiffusionData shouldn't be phetioState:false

### ISSUE THREAD

**Issue by zepumph** [phetsims/gas-properties#183]
Looking at DiffusionData with @samreid, we were confused to see `phetioState` as an option for a class that didn't extend PhetioObject. @pixelzoom do you think that should be removed?

**Comment by pixelzoom** [comment]
Thanks, I removed `phetioState` from DiffusionData. 

I'm guessing that I may have intended to add `phetioDocumentation` to DiffusionData, but never followed through.  We'll see if that's needed when we address PhET-iO Design in #30.

**Comment by zepumph** [comment]
Do you feel similarly about `ParticleFlowRate` too?

**Comment by pixelzoom** [comment]
Yes thanks, done, closing.
