### ISSUE TITLE
User suggestion: air leakage in a vacuum system

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gas-properties#184]
> For many years, I’ve been exploring the creatopm pf a visual explanation of the effects of air in-leakage in a vacuum system, regarding the vacuum level (pressure) and capacity (cfm) of a vacuum pump.  I’d like to use/create a visual representation of the air molecules leaking in 1) slowly and 2) moderately; plotted against the capacity of the vacuum pump (if the air is leaking in faster that the vacuum pump can take it away, the end-user will never reach their vacuum pressure target – but the vacuum pump is still working correctly).
>  
> In looking at your internet gas laws interactive animation at https://phet.colorado.edu/sims/html/gas-properties/latest/gas-properties_en.html  This animation comes close to what I’d like to portray.  How difficult if instead of ‘pulling back the top lid’ and letting molecules under pressure ‘escape’, that a vacuum pump (or at least piping to a vacuum pump) be inserted there and the hand pump replaced by an adjustable leak…
>  
> How difficult would it be to modify this animation?

**Comment by pixelzoom** [comment]
This would require major changes to model and user interface, and would require some significant design work before I could estimate.  Assigning to @arouinfar to evaluate.

**Comment by ofey404** [comment]
Hey there! I think the air leaking visualization could be done using a 3-cell container, which could be implemented based on the 'Diffusion' screen.

**The design**

![gas-properties-leakage design](https://user-images.githubusercontent.com/35857538/79548843-a64b7900-80c8-11ea-9365-94fa21288124.png)

I am interested in PhET project and I'm planning to make a demo of the design above in a couple of days.

I'm an undergraduate of Physics Department of Fudan University, who is interested in programming.

**Comment by ofey404** [comment]
I have worked out a prototype of my design, on [my fork of gas-properties](https://github.com/ofey404/gas-properties/tree/leakage), `leakage` branch.

![Screen Shot 2020-05-01 at 18 59 41](https://user-images.githubusercontent.com/35857538/80801286-6a430880-8bde-11ea-9c83-bc456ae7c78c.png)
![Screen Shot 2020-05-01 at 18 59 24](https://user-images.githubusercontent.com/35857538/80801287-6c0ccc00-8bde-11ea-91c2-0353162d4524.png)

Besides, I have a problem now: I want to make the opening of barrier variable, but I don't know how to redraw a node while the property changes.

I try to refer [code in resistance-in-a-wire](https://github.com/phetsims/resistance-in-a-wire/blob/master/js/resistance-in-a-wire/view/FormulaNode.js#L144), but not work it out yet.

The node of barrier in my fork is in [ObstacleNode.js](https://github.com/ofey404/gas-properties/blob/leakage/js/leakage/view/ObstacleNode.js). Can someone help me?

**Comment by arouinfar** [comment]
@oliver-phet @pixelzoom this goes beyond the scope of the sim's learning goals, and is not a change we would make to Gas Properties. @oliver-phet please respond to the user.

@ofey404 thanks for your interest in modifying the simulation. Our developers do not have bandwidth to advise you in your work, but I hope you were able to troubleshoot the issue on your own.

**Comment by pixelzoom** [comment]
@ofey404 asked:
> I want to make the opening of barrier variable, but I don't know how to redraw a node while the property changes.

Here's the general idea.  

Suppose you have some Property that defines the barrier width:

```js
const barrierWidthProperty = new Property(...);
```

Then you can link an observer to the Property like this:

```js
barrierWidthProperty.link( barrierWidth => {
  // update your ObstableNode here
} );
```

You'll probably need to add methods to `ObstableNode` to make it mutable.

**Comment by oliver-phet** [comment]
Replied to user.

**Comment by pixelzoom** [comment]
@oliver-phet can this issue be closed?

**Comment by ofey404** [comment]
Please close it.
