### ISSUE TITLE
User suggestion: add external force

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gas-properties#187]
> I just found your PhET gas-simulator, and used to to explain some basics to my 
> son. I really like it, very neat & intuitive! :-)
> 
> I had a thought, though.
> Could you not also add an external force (my main interest is gravity, so you 
> can also demonstrate gradients)?
> I imagine it would be a trivial change to a constant (or configurable), uni-
> directional force, no?

**Comment by pixelzoom** [comment]
This is the second request for gravity (see https://github.com/phetsims/gas-properties/issues/173).   See https://github.com/phetsims/gas-properties/issues/173#issuecomment-531305020 for the long story.  The short story is that we made simplifying assumptions that explicitly exclude gravity, and adding it to the model is not possible.

**Comment by pixelzoom** [comment]
Assigning to @arouinfar in case she has more to add.  Then please assign to @oliver-phet to reply to the user.

**Comment by arouinfar** [comment]
Gravity will never be added to Gas Properties. After a lot of discussion we decided not to include it in the HTML5 version as it didn't support the learning goals related to the ideal gas law, kinetic molecular theory, and diffusion. Gravity will be included in a more atmosphere-focused simulation, but that's unfortunately a long way off.

**Comment by oliver-phet** [comment]
Replied to user. Closing.
