### ISSUE TITLE
stopwatch changes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#188]
In https://github.com/phetsims/scenery-phet/issues/565, StopwatchNode got some new features.  So here are some things that we could do now in Gas Properties:

(1) Use 1 decimal place.
The format of the time display is now more flexible. So instead of requiring 2 decimal places ("12.34 ps"), we could use 1 decimal ("12.3 ps").  This seems preferable to me, because 2 decimal places are unnecessary, and they change so fast you can't really see them.  I recommend this change.

(2) Allow the stopwatch to run indefinitely.
Previously it stopped at "999.99 ps" without any explanation.   I've definitely hit the "999.99" limit while developing/testing, but it's probably not a big deal in practice.  There's no memory penalty for letting it run indefinitely, and larger values get scaled down to fit in the display. So I'm on the fence about this change. 

@arouinfar Let me know if you want to make either of these changes.

**Comment by pixelzoom** [comment]
Another good reason to limit the number of decimal places is to limit the number of times that the stopwatch's display needs to be updated.  This is a sim where performance is critical, and that will be even more so when this becomes a PhET-iO sim. Imo we're currently updating the stopwatch 10x more than necessary by displaying 2 decimal places.

**Comment by arouinfar** [comment]
@pixelzoom let's reduce the display to one decimal place -- two are definitely not pedagogically necessary. I think the limit of 999.9 ps is large enough for typical classroom applications. I don't anticipate allowing the stopwatch to run indefinitely in most sims, so for consistency across sims, we could do the same here. I don't have a strong opinion on this, though. If you find value in letting it run indefinitely, I'd be fine with that change.

**Comment by pixelzoom** [comment]
I ran into problem with the numberFormatter API in StopwatchNode, see https://github.com/phetsims/scenery-phet/issues/618.  This issue is on hold until that issue is resolved.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/issues/618#issuecomment-681902936, a `numberOfDecimalPlaces` option was added to `StopwatchNode.getRichNumberFormatter`.   In the above commit, I'm using that option to display 1 decimal place. 

Ready for testing the next time this sim is released.

**Comment by brooklynlash** [comment]
All stopwatches in Gas Properties are rounded to one decimal place.

**Comment by pixelzoom** [comment]
Thanks @liam-mulhall. Closing.
