### ISSUE TITLE
Where did the "o" go in "Remove Divider"?

### ISSUE THREAD

**Issue by zepumph** [phetsims/gas-properties#189]
While pairing with @ariel-phet and poking around in sims, we found that the "o" was gone from "Remove Divider" on the diffusion screen:

![image](https://user-images.githubusercontent.com/6856943/98615580-77d0fd80-22a7-11eb-881c-8466808ba5da.png)

@jonathanolson, this feels potentially like a scenery bug. Thoughts?

**Comment by pixelzoom** [comment]
I just did a pull-all, and I don't see the problem in my working copy on macOS 10.15.7 + Chrome latest. 

What platform are you testing on?

**Comment by pixelzoom** [comment]
I just did a pull-all, and I don't see this problem in my working copy on macOS 10.15.7 + Chrome latest.   And the button is green at all times, not the strange yellow/gray shown in the above screenshot.

What platform are you testing on?

**Comment by zepumph** [comment]
I pulled master and couldn't reproduce. @ariel-phet did the same. We feel like it may have just been a fluke. We feel like closing this. 

The yellow was me highlighting the spot where the button was.
