### ISSUE TITLE
List original designer in "Lead design"?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#194]
In https://github.com/phetsims/natural-selection/issues/270#issuecomment-827745710, @amanda-phet said:
> @kathy-phet and I reviewed a bunch of recent HTML5 ports, and we'd like to keep up the convention of listing the original designer when we do a port. 

If that applies to this sim, please specify what you'd like changed. 

The current credits in GasPropertiesConstants.js are:

```js
  CREDITS: {
    leadDesign: 'Amy Rouinfar',
    softwareDevelopment: 'Chris Malley (PixelZoom, Inc.)',
    team: 'Jack Barbera, John Blanco, Michael Dubson, Amy Hanson, Linda Koch, Ron LeMaster, Trish Loeblein, ' +
          'Emily B. Moore, Ariel Paul, Kathy Perkins, Carl Wieman',
    qualityAssurance: 'Jaspe Arias, Liam Mulhall, Jacob Romero, Kathryn Woessner',
    graphicArts: '',
    thanks: ''
  },
```

**Comment by kathy-phet** [comment]
Gas Properties was a very, very early sim. Development was being done on it already when I started in Jan 2003, and it evolved over the years, with Carl, myself, Linda, Trish, and Jack all having a lot of input into the Java design of the original and its variants. So, it was more of a collaborative effort than a lead design - which we evolved to later in PhET's evolution. I think the current credits are appropriate for this case.
