### ISSUE TITLE
Control wall speed with alt input

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#197]
A user wrote into phethelp with concerns about the simulation model, reporting:

> If I fill the container with gas at width=7.5 nm, 300 K, 25 atmospheres, and then compress the gas adiabatically until width=5 nm, the temperature and pressure both rise, as expected.  The problem, though, is that a slow compression produces a LARGER increase in temperature than a fast compression to the same distance.  It should be the other way around, since the fast compression is MORE irreversible.  Molecules "bunched up" near the piston wall should require more external work to be done for the compression in the fast case

I could not reproduce this behavior in the published sim, and sent a video to the user to demonstrate the behavior:

https://user-images.githubusercontent.com/8419308/138513778-93d987ed-085d-48e2-b730-09109abf09f2.mp4

They responded:
>Your video shows the behavior I would expect, but mine still does not.  Maybe the problem with my simulation is that it is difficult to control the motion of the wall, and my "slow" motion is actually a series of brief rapid motions with rests in between.  I do not seem to be able to achieve uniform slow compression at all with my trackpad.    The same thing happens in reverse -- as I "slowly" move the wall, I'm actually moving it in rapid jerks (each of which may have no collisions).   Do you have any recommendations for achieving uniformly slow compression or expansion?  Was your movie made with compression "manually" via mouse or trackpad?

Controlling the wall speed with a trackpad can be difficult and many laptops and Chromebooks do not have high-quality trackpads that provide more precise control. Alt input would likely alleviate this issue (though we would need to figure out ways to control the speed).

I think it would be worth considering adding support for alt input when we resume work on this simulation.

**Comment by pixelzoom** [comment]
I changed the title of this issue to be more specific, and linked it to the more general issue #213 (Alt Input support).

**Comment by pixelzoom** [comment]
See ContainerResizeDragListener, a specialization of DragListener.  We'll somehow need to factor out functionality that's also needed by KeyboardDragListener.

**Comment by pixelzoom** [comment]
@arouinfar said:
>  Alt input would likely alleviate this issue (though we would need to figure out ways to control the speed).

KeyboardDragListener gives us 2 drag speeds.  Should we try that to see if it will be sufficinet?

**Comment by pixelzoom** [comment]
Over in #213, I added a keyboard drag listener for resizing the container - see ResizeHandleKeyboardDragListener.  The drag speeds are easily changed, currently set to:

```ts
      dragSpeed: 300,
      shiftDragSpeed: 75,
```

@arouinfar please let me know if you think this approach works.   Test in the Explore screen, where the wall behaves differently (it does work, so making the container smaller behaves differently)

**Comment by pixelzoom** [comment]
Design meeting 6/13/2024 @arouinfar @Nancy-Salpepi @kathy-phet @ariel-phet @KatieWoe

dragSpeed is probably fine.

I will adjust shiftDragSpeed to be slower, to meet the goal of resizing the container very slowly in the Energy screen.  We'll use the same shiftDragSpeed value in all screens for now.  @arouinfar may want to adjust later.

**Comment by pixelzoom** [comment]
@arouinfar I added query parameters for tuning the drag speeds for the resize handle.  Here are the query parameters and their defaults, which currently apply to any screen that has a resize handle.  If you'd like to have different values for different screens, that's relatively easy, just let me know the desired values for each screen.

* resizeHandleDragSpeed=300
* resizeHandleShiftDragSpeed=5

**Comment by arouinfar** [comment]
Thanks for setting up these query parameters @pixelzoom!

For the Explore Screen, the default speeds are perfect and support the learning goals related to work.

> If you'd like to have different values for different screens, that's relatively easy, just let me know the desired values for each screen.

I'd like to use less extreme speeds on the Ideal Screen (and Gases Intro). The goal here is to support users in setting the container to a particular width.

* resizeHandleDragSpeed=100
* resizeHandleShiftDragSpeed=20

If possible, can we use these same speeds for the lid handle on all screens?

Back to you @pixelzoom.

**Comment by pixelzoom** [comment]
Done in the above commit.  @arouinfar please review, close if OK.

To summarize, here's what we have now:

Lid handle, Idea/Explore/Energy screens:
* `dragSpeed: 100`
* `shiftDragSpeed: 20`

Resize handle, Idea screen:
* `dragSpeed: 100`
* `shiftDragSpeed: 20`

Resize handle, Explore screen:
* `dragSpeed: 300`
* `shiftDragSpeed: 5`

Also note that the `resizeHandleDragSpeed` and `resizeHandleShiftDragSpeed` query parameters have been removed.

**Comment by arouinfar** [comment]
Looks great, thanks @pixelzoom! Closing.
