### ISSUE TITLE
Dynamic Locale support

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#201]
Requested by @kathy-phet.   Current milestone for publication is 9/30/2023.

**Comment by pixelzoom** [comment]
Baseline before starting this work: 
https://phet-dev.colorado.edu/html/gas-properties/1.1.0-dev.4/phet/gas-properties_en_phet.html

**Comment by pixelzoom** [comment]
All strings have been converted to StringProperty.  Next step is to address #205 (replace FixedWidthNode), then address layout issues.

**Comment by pixelzoom** [comment]
Ready for review by @arouinfar.

**Comment by arouinfar** [comment]
This simulation is not a current PhET-iO design priority, so unassigning.

**Comment by pixelzoom** [comment]
Checking on the current state of things...

There are multiple layout problems with the Collision Counter:

<img width="198" alt="screenshot_3242" src="https://github.com/phetsims/gas-properties/assets/3046552/f6283ac2-2086-4922-8554-1ccadc68a9f6">

**Comment by arouinfar** [comment]
I reviewed on main with `stringTest=dynamic` and overall the behavior looks good. The Sample Period ListBox sizing looks off, though. 

Steps to reproduce
1. Run the sim with `stringTest=dynamic` and select Ideal Screen
2. Open the Sample Period ComboBox 
3. Use the right arrow a few times to increase string length.
4. Use the left arrow to return the strings to their default length. The ListBox width remains wide:
  ![image](https://github.com/phetsims/gas-properties/assets/8419308/318f01b5-e905-4faf-b1fe-e6ad7af9e06a)

**Comment by pixelzoom** [comment]
> The Sample Period ListBox sizing looks off, though. ...

I had this exact problem in previous sims. It was reported and fixed in https://github.com/phetsims/sun/issues/785. 

I don't see anything unusual in how I'm creating the sample period combo box.  Here's the relevant code in 

```ts
// Combo box items
    const comboBoxItems: ComboBoxItem<number>[] = collisionCounter.samplePeriods.map( samplePeriod => {

      return {
        value: samplePeriod,
        createNode: ( contentTandem: Tandem ) => {

          // e.g. '10 ps'
          const samplePeriodStringProperty = new PatternStringProperty( GasPropertiesStrings.valueUnitsStringProperty, {
            value: samplePeriod,
            units: GasPropertiesStrings.picosecondsStringProperty
          }, {
            tandem: contentTandem.createTandem( 'samplePeriodStringProperty' )
          } );
          return new Text( samplePeriodStringProperty, {
            font: CONTROL_FONT,
            maxWidth: 100 // determined empirically
          } );
        },
        tandemName: `samplePeriod${samplePeriod}Item`
      };
    } );

    // Combo box
    const samplePeriodComboBox = new ComboBox( collisionCounter.samplePeriodProperty, comboBoxItems, listboxParent, {
      align: 'right',
      xMargin: 6,
      yMargin: 3,
      cornerRadius: 5,
      tandem: options.tandem.createTandem( 'samplePeriodComboBox' )
    } );
```

**Comment by pixelzoom** [comment]
@jonathanolson did the dynamic layout for ComboBox, and fixed https://github.com/phetsims/sun/issues/785.  Perhaps he can help here.  The steps to reproduce are described in https://github.com/phetsims/gas-properties/issues/201#issuecomment-2073571632.  The relevant code is SamplePeriodComboBox.ts.

**Comment by pixelzoom** [comment]
Pinging @jonathanolson again. Your assistance is needed with the ComboBox layout problem identified in https://github.com/phetsims/gas-properties/issues/201#issuecomment-2073571632.

**Comment by pixelzoom** [comment]
The problem with the Sample Period combo box is now being tracked in https://github.com/phetsims/gas-properties/issues/237.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/gas-properties/issues/237 has been addressed, and that was the last issue with dynamic layout.  So closing this issue.
