### ISSUE TITLE
Address listener order dependencies

### ISSUE THREAD

**Issue by zepumph** [phetsims/gas-properties#206]
From https://github.com/phetsims/axon/issues/215, when the time is right in this issue.

**Comment by pixelzoom** [comment]
@zepumph As noted in https://github.com/phetsims/axon/issues/215, https://github.com/phetsims/gas-properties/issues/186 has been tracking this since May 2020.  Why the new issue?  Can I close this as a duplicate?

**Comment by zepumph** [comment]
I see now, thanks! Pointing the TODOs over there now.
