### ISSUE TITLE
Issues updating the code

### ISSUE THREAD

**Issue by ramiro-marinio** [phetsims/gas-properties#207]
I tried modifying the code, but there is no visible change, even after transpiling and restarting the http server. Am I doing something wrong?

**Comment by veillette** [comment]
Hello @ramiro-marinio, Thanks for your inquiry. I think your question is not specific about gas-properties but rather more about the process of making changes to an existing simulation and getting started in general. I think you would get more support to your question in the forum https://github.com/orgs/phetsims/discussions.
I should also point out that there is some information in https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md#getting-started about getting started.

**Comment by veillette** [comment]
@ramiro-marinio : 
 I forgot to mention that you will get more help with your issue if you include a good description of your problem, error messages, etc,  as well as the steps you have taken so far.  For instance, it is useful to know which of the steps in https://github.com/phetsims/gas-properties/blob/master/README.md you have taken and have been successful, and which one(s) you are stuck on.

**Comment by ramiro-marinio** [comment]
There is no error message. I tried changing variables like colors, retranspiled the program, shut down the http server and started it again, and nothing happened

**Comment by veillette** [comment]
Am I correct to assume that you have carried out successfully the steps 1 to 5 of [quick-start](https://github.com/phetsims/gas-properties/blob/master/README.md#quick-start) for the out-of-box code base, and are able to run the gas-properties simulation within a browser?

I am unclear about what you mean by 'nothing happened' after retranspiling the program: Do you mean
- You can no longer run the simulation in the browser after the changes
- You can run the simulation but the changes you have made are not reflected in the simulation  

If it is the second case, can you describe what you observe in the terminal once you run the transpiler. 
The command  `node js/scripts/transpile.js --watch` should pick up the changes to the codebase and output something to the terminal that it has successfully transpiled the modified file.
