### ISSUE TITLE
All PatternStringProperties should be instrumented

### ISSUE THREAD

**Issue by zepumph** [phetsims/gas-properties#208]
From https://github.com/phetsims/phet-io/issues/1942, I passed some tandems through but mostly `Tandem.OPT_OUT`s, please review this sim's instrumentation of PatternStringProperties in correlation to this sims' phet-io priorities.  In general all PatternStringProperties should be instrumented unless they are just symbols or patterns that aren't for i18n purposes.

**Comment by pixelzoom** [comment]
In the above commit, I instrumented PatternStringProperty instances.  There are no DerivedProperty instances responsible for creating visible strings.

This will undoubtedly get more review when this sim is eventually instrumented. But for now, this can be closed.
