### ISSUE TITLE
Allow volume to be calculated precisely

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#21]
For #8. A user reported in [Unfuddle Ticket #3645](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3645):
> I have another question, if you don't mind.  It's already possible to obtain the base and height of the 2D gas container in nm. Could the simulation be modified so that the depth of the container is always  the same as the base, regardless of how the base changes during run-time?  In this way, volumes could then be determined.

Self-assigning for response.

**Comment by arouinfar** [comment]
Discussed with @ariel-phet. We could add a checkbox to display a volume readout. However, the underlying model is 2D, so this may pose some challenges. Perhaps we could assume one unit of depth? 

We can discuss this more once this sim moves from brainstorming to design.

**Comment by arouinfar** [comment]
In the [4/6/18](https://docs.google.com/document/d/1HOCO6vXfqlHIf3MrdldaiZTPFKYWTzS9Jm8fw-b25EU/edit#heading=h.p2kpqhkzbqsw) brainstorming meeting we decided to add a length readout to replace the ruler. The length of the container can be swapped out for the volume in the ideal gas equation, so long as the students are using dummy units. Doubling the length will double the volume.

Given the 2D/3D complexities, I'm inclined to pass on this suggestion.  How does that sound @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar I agree. I think the key is that we can determine functional relationships. Doubling/halving the volume or such. Calculating the exact volume is not a learning goal.
