### ISSUE TITLE
UI Sound support

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#214]
@kathy-phet asked to evalute alt input for https://github.com/phetsims/gas-properties/issues/191.

From a Slack discussion with @kathy-phet @arouinfar @pixelzoom:

@kathy-phet 
Let's evaluate alt input and UI sound, and see if there are any challenges there.

@pixelzoom 
For UI sound (no sonification), the bicycle pump is the only thing that looks tricky.

@arouinfar 
I think we’ll want something for the HeaterCoolerNode too, especially since it can automatically heat/cool depending on what mode the sim is in.

**Comment by pixelzoom** [comment]
UI Sound is now "on" for all sims in this suite, so we can see what comes for free.

**Comment by pixelzoom** [comment]
Sim-specific UI sound that is missing:
- [ ] Grab/release for container lid handle (should come for free with RichKeyboardDragListener)
- [ ] Grab/release for container resize handle (should come for free with RichKeyboardDragListener)

Common-code UI sound that is missing, this work will need to be scheduled:
- [ ] BicyclePumpNode - are grab/release sufficient, or should this sound like a slider, or something else?
- [ ] FineCoarseSpinner - all 4 buttons currently have the same default push button sound

@arouinfar also said:
> I think we’ll want something for the HeaterCoolerNode too, especially since it can automatically heat/cool depending on what mode the sim is in.

Imo, that's sonification, which is not in the scope of sound for this release. But let's discuss.

**Comment by pixelzoom** [comment]
4/11/24 design meeting with @arouinfar @kathy-phet @Nancy-Salpepi @ariel-phet @pixelzoom

* @pixelzoom should pair with @jessegreenberg on adding UI sound to FineCoarseSpinner and BicyclePumpNode.

**Comment by pixelzoom** [comment]
@arouinfar ready for review.  Let me know what you'd like to change.

**Comment by arouinfar** [comment]
I reviewed the UI sounds on main it all sounds good. I don't have any changes to request @pixelzoom. Closing.
