### ISSUE TITLE
Keyboard help for alt input.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#215]
Related to https://github.com/phetsims/gas-properties/issues/213 ...

We'll need to add keyboard help for alt input.  There are many questions here.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/gas-properties/commit/1ea56443d3ad6cd8e9df699cb8141a1edd299359, I added stubs for the keyboard help in each screen.  @arouinfar let's figure out what we want for each screen.

**Comment by pixelzoom** [comment]
Some additional work that needs to be done:

- [ ] Include NumberSpinnerKeyboardHelpContent when it's completed in https://github.com/phetsims/scenery-phet/issues/848.

- [ ] Add MoveDraggableItemsKeyboardHelpSection for the collision counter and stopwatch.

- [ ] To include the bicycle pump handle for https://github.com/phetsims/scenery-phet/issues/848, add up/down arrows to this part of the keyboard help:

<img width="338" alt="screenshot_3226" src="https://github.com/phetsims/gas-properties/assets/3046552/79dcd411-26ca-44f9-9b0e-2d5b70f907f8">

**Comment by pixelzoom** [comment]
@arouinfar FYI I added a placeholder for 'Spinner Controls' in the Gas Properties keyboard help, so that we can get a feel for space/layout/etc. until scenery-phet.SpinnerHelpSection is ready in https://github.com/phetsims/scenery-phet/issues/847.  I'm not suggesting that this should inform the design of SpinnerHelpSection, just needed something to fill the approximate amount of space.

In the first 3 screens, it looks like this, because the spinners are horizontal:
<img width="291" alt="screenshot_3227" src="https://github.com/phetsims/gas-properties/assets/3046552/06118023-fa13-4123-80ee-f2fe405bb3cd">

In the Diffusion screen, it looks like this, because the spinners are vertical:
<img width="382" alt="screenshot_3228" src="https://github.com/phetsims/gas-properties/assets/3046552/b581ce2b-70d4-4f30-8b81-4dbe439b2a6c">

**Comment by terracoda** [comment]
What about using language like "bursts" and "singles" or is that idea sim-specific?

**Comment by terracoda** [comment]
Also, are the size of the small steps (singles) and large steps (bursts) always fixed or can they be random bursts?

**Comment by terracoda** [comment]
Maybe the bike pump is the randomizer, and the FineCoarseSpinner gives more precision?

**Comment by pixelzoom** [comment]
> What about using language like "bursts" and "singles" or is that idea sim-specific?

@terracoda I don't know what you're referring to here.

**Comment by terracoda** [comment]
I was referring to the language for the big and small steps of the fine coarse spinner - pressing the arrow key is like a burst and pressing the shift + arrow is like a single.

Apologies if this is wrong issue in which to comment.

**Comment by terracoda** [comment]
More detail is over in https://github.com/phetsims/scenery-phet/issues/847#issuecomment-2067197305

**Comment by pixelzoom** [comment]
@arouinfar and I reviewed the current state of keyboard help dialogs.  The "Move Handles" section did not contain anything that wasn't covered by the "Move Draggable Items" section, so we deleted the "Move Handles" section.  

@arouinfar ready for review, with the caveat that the "Spinner Control" section is still being worked on in https://github.com/phetsims/scenery-phet/issues/847.

**Comment by arouinfar** [comment]
@pixelzoom the Slider Controls section is largely irrelevant now that BicyclePumpNode is a draggable object. We should keep it on the Energy Screen, but it's not needed elsewhere. Let's also move it below the Spinner Controls, since it's less important.

**Comment by pixelzoom** [comment]
> @pixelzoom the Slider Controls section is largely irrelevant now that BicyclePumpNode is a draggable object.  ....

BicyclePumpNode was never a slider.  "Slider Controls" section was for the slider on the Heat/Cool control (HeaterCoolerNode).  But I'm guessing that we'll have keyboard help for HeaterCoolerNode as part of https://github.com/phetsims/scenery-phet/issues/853. Do you want me to remove "Slider Controls" in the meantime?

**Comment by pixelzoom** [comment]
> ...  Do you want me to remove "Slider Controls" in the meantime?

Discussed with @arouinfar.  We'll need keyboard help for HeaterCoolerNode, so we'll keep "Slider Controls" help as a placeholder until https://github.com/phetsims/scenery-phet/issues/853 is wrapped up.

**Comment by pixelzoom** [comment]
The last remaining task for this issue is to integrate help for HeaterCoolerNode when it's available, see https://github.com/phetsims/scenery-phet/issues/853.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/gas-properties/issues/213#issuecomment-2173851089, @Nancy-Salpepi said:

> The hotkey for Play/Pause is going to be really useful when setting up experiments. It should be added to the Keyboard Shortcuts Dialog to remind users of it.

**Comment by pixelzoom** [comment]
We'd like to get this sim into dev testing by Friday 6/21, so removing the hold. 

@jessegreenberg Is it possible to complete https://github.com/phetsims/scenery-phet/issues/853 before Friday?

@arouinfar The keyboard help dialogs are large, with lots of redundancy. I'm not quite sure where we're going to squeeze in the help for HeaterCoolerNode.  Thoughts on what we need to do to have this ready for dev testing?

**Comment by pixelzoom** [comment]
Discusssed with @arouinfar.  TODO:

- [ ] Replace SliderControlsKeyboardHelpSection with HeaterCoolerNodeHelpSection
- [ ] "Change Choice" => "Change Units"

**Comment by pixelzoom** [comment]
Over to @arouinfar for a review.  Anything else to change? If not, feel free to close.

**Comment by arouinfar** [comment]
Looks good on main, thanks @pixelzoom. Closing.
