### ISSUE TITLE
Change "Pressure Noise" control to a toggle.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#216]
In Preferences, this control should be an on/off toggle, with a description:

<img width="628" alt="screenshot_3087" src="https://github.com/phetsims/gas-properties/assets/3046552/55ac2265-4e33-41b1-9c84-907a636bf8fe">

**Comment by pixelzoom** [comment]
The revised control is shown below.  @arouinfar please review.  Let me know if you'd like to change the description, or close if OK.

<img width="746" alt="screenshot_3088" src="https://github.com/phetsims/gas-properties/assets/3046552/a87c178f-abdd-41de-be66-27e35ef0d4bf">

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I would get rid of the comma, but otherwise looks great.

**Comment by pixelzoom** [comment]
Comma expunged, screenshot below. Closing.

<img width="716" alt="screenshot_3091" src="https://github.com/phetsims/gas-properties/assets/3046552/6608f4a9-1afe-488f-98aa-21a1d2f56a6e">
