### ISSUE TITLE
Update credits for 1.1 release.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#221]
We'll need to update QA credits.

@arouinfar also said that she thought KP's brother was involved in the HTML5 redesign, and he's not currently listed. @arouinfar will investigate and review the current credits.

**Comment by arouinfar** [comment]
I updated the team credits in the above commit. QA credits will need to be updated once we get to testing.

**Comment by pixelzoom** [comment]
I've added @Nancy-Salpepi to "Team" credits, since she's contributing to the PhET-iO design.

**Comment by Nancy-Salpepi** [comment]
Oh yay! I'm moving up in the world!

**Comment by pixelzoom** [comment]
Please identify changes to QA credits for https://github.com/phetsims/gas-properties/issues/221.

**Comment by Nancy-Salpepi** [comment]
Please add Jaron Droder and Matthew Moore to QA credits. Thanks!

**Comment by pixelzoom** [comment]
Please identify changes to QA credits for RC tests https://github.com/phetsims/qa/issues/1107, https://github.com/phetsims/qa/issues/1108, https://github.com/phetsims/qa/issues/1109.

**Comment by KatieWoe** [comment]
Luisa Vargas, Nancy Salpepi, Clifford Hardin should be added.

**Comment by pixelzoom** [comment]
> Luisa Vargas, Nancy Salpepi, Clifford Hardin should be added.

Done in the above commits, patched into release branches. 

Note that Nancy Salpepi had previously been added to the "Team" section, for her role in PhET-iO and general design.  PhET does not typically credit people in multiple sections, but in this case I also added her to the QA section.

**Comment by pixelzoom** [comment]
> Luisa Vargas, Nancy Salpepi, Clifford Hardin should be added.

Done in the above commits, patched into release branches. 

Note that Nancy Salpepi had previously been added to the "Team" section, for her role in PhET-iO and general design.  PhET does not typically credit people in multiple sections, but in this case I also added her to the QA section.

**Comment by pixelzoom** [comment]
Please identify changes to QA credits for RC tests https://github.com/phetsims/qa/issues/1123, https://github.com/phetsims/qa/issues/1124, and https://github.com/phetsims/qa/issues/1125.

**Comment by KatieWoe** [comment]
No new QA additions.

**Comment by pixelzoom** [comment]
Ready to publish 1.1.0.  Closing.
