### ISSUE TITLE
Memory test for 1.1 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#222]
For #191 ... Memory testing should be done before the sim goes into dev test, for phet and phet-io brands.

**Comment by pixelzoom** [comment]
phet brand was tested with https://phet-dev.colorado.edu/html/gas-properties/1.1.0-dev.16/phet/gas-properties_en_phet.html?fuzz.  No memory leaks noted. Heap snapsnots were taken at 1-minute intervals, and stabilized at ~110MB.

<img width="244" alt="screenshot_3367" src="https://github.com/phetsims/gas-properties/assets/3046552/15f05771-8263-49b6-a045-a45f649cb419">

**Comment by pixelzoom** [comment]
phet-io brand was tested with https://phet-dev.colorado.edu/html/gas-properties/1.1.0-dev.16/phet-io/gas-properties_all_phet-io.html?postMessageOnError&phetioStandalone&fuzz. No memory leaks noted. Heap snapsnots were taken at 1-minute intervals, and stabilized at ~130MB.

<img width="221" alt="screenshot_3368" src="https://github.com/phetsims/gas-properties/assets/3046552/6f9fbcc8-5902-4b41-9141-a1c47258cdac">

**Comment by pixelzoom** [comment]
Please verify the above memory testing results for dev test https://github.com/phetsims/qa/issues/1100.

OK to close if memory testing looks OK.

**Comment by KatieWoe** [comment]
Looking at the phet-brand, the memory test looks a bit worse, and seems to be leaking at least a bit.
![growingmem](https://github.com/phetsims/gas-properties/assets/41024075/e071576c-bdc5-4745-871c-66958cc1439f)

**Comment by KatieWoe** [comment]
Same thing for PhET-iO Memory
![samemem](https://github.com/phetsims/gas-properties/assets/41024075/17dc312f-1694-4d8a-9760-605751057da9)

**Comment by pixelzoom** [comment]
My memory test in https://github.com/phetsims/gas-properties/issues/222#issuecomment-2173985134 were done with 1.1.0-dev.16, published 6/17/24.

Dev test https://github.com/phetsims/qa/issues/1100 was done with 1.1.0-dev.18, published 6/24/24.

Do it's possible that a leak could have snuck in during the 7 days between those versions.  I'll do another test with a new dev version.

**Comment by pixelzoom** [comment]
Testing 1.1.0-dev.18 on macOS 14.5 + Chrome 126.

phet brand was tested with https://phet-dev.colorado.edu/html/gas-properties/1.1.0-dev.18/phet/gas-properties_en_phet.html?fuzz. Heap snapsnots were taken at 1-minute intervals, with 10 minutes between Snapshots 9 & 10.  Heap size was observed to go down once (Snapshot 8).  There may be a very slow memory leak, but nothing to be concerned about in practice.

<img width="178" alt="screenshot_3409" src="https://github.com/phetsims/gas-properties/assets/3046552/b08cfefc-d4dd-4ece-b902-4de52c6d82ee">

**Comment by pixelzoom** [comment]
I'll keep this open for verification in 1.1.0-rc.1.

**Comment by KatieWoe** [comment]
Memory tests look similar to before. Small but non-worrying leak.
PhET Brand:
![slight](https://github.com/user-attachments/assets/f2eb15a3-078f-461c-a004-956749ff6c2c)
PhET-iO:
![slight2](https://github.com/user-attachments/assets/53ed35ed-6386-408d-9959-7708ee2ae2ed)

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.  We won't be making any changes that affect memory management going forward, so closing this issue.

**Comment by pixelzoom** [comment]
Reopening because we have a suspected memory problem on iPad in https://github.com/phetsims/gas-properties/issues/289.

**Comment by pixelzoom** [comment]
#289 turned out to be caused by WebGL, not memory related.  I did another heap size test, and heap size still stabilizes ~140MB.  So re-closing this issue.
