### ISSUE TITLE
Update Teacher Tips for 1.1 Release

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#224]
Related to #191 

Updates include:
- [x] #210 
- [x] #220
- <s>#245</s>
- [x] #271
- [x] Screenshots 
- [x] Inter-molecular forces are ignored (purely hard sphere)
- [x] Fix typo: "The Energy and Kinetic Energy histograms" -- should be "Speed and Kinetic Energy"
- [x] Radius control on Diffusion related to mean free path

**Comment by Nancy-Salpepi** [comment]
@arouinfar do you think we should add something to the teacher tips regarding the changes made in #271?

**Comment by arouinfar** [comment]
Teacher Tips are ready to go. Leaving this issue open until 1.1 is published.

**Comment by pixelzoom** [comment]
1.1.0 has been published, so this issue can proceed.

**Comment by arouinfar** [comment]
Done, closing.
