### ISSUE TITLE
Factor out `toolsPanel` for Ideal screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#225]
Discussed with @arouinfar...  The Explore, Energy, and Diffusion screens all have a `toolsPanel` PhET-iO element.  For example in the Explore screen:

<img width="277" alt="screenshot_3248" src="https://github.com/phetsims/gas-properties/assets/3046552/fcfb9138-b187-43a0-b339-7dbb26a382e8">

In the Ideal screen, there is no `toolsPanel`, the controls are inside the `controlPanel` element:

<img width="280" alt="screenshot_3249" src="https://github.com/phetsims/gas-properties/assets/3046552/b07266ee-51c4-47c9-a923-702f052f8c71">

For PhET-iO consistency, and to clean up the implementation, we're going to factor out a separate `toolsPanel` in the Ideal screen. It will look like this:

<img width="243" alt="screenshot_3250" src="https://github.com/phetsims/gas-properties/assets/3046552/e6f0e909-1f8d-4b8b-9bc9-c2161644c896">

**Comment by pixelzoom** [comment]
@arouinfar please review, close if OK.

Note the new PhET-iO elements:
* gasProperties.idealScreen.view.holdConstantPanel
* gasProperties.idealScreen.view.toolsPanel

Also note that holdConstantPanel.radioButtonGroup.visibleProperty is not instrumented.  The client should use holdConstantPanel.visibleProperty.

**Comment by arouinfar** [comment]
Looks good, closing!
