### ISSUE TITLE
examples.md for 1.1 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#226]
This issue captures things that need to be included in examples.md for PhET-iO.

**Comment by pixelzoom** [comment]
- [ ] In the Diffusion screen, the 2 types of particles are referred to as "particle 1" and "particle 2".  That numbering is applied to many elements in both the model and view.  For example `centerOfMass1Property` and `centerOfMass2Property`, `mass1Spinner` and `mass2Spinner`.

**Comment by pixelzoom** [comment]
- [ ] While it's mentioned in the phetioDocumentation, you might want to also mention in examples.md that the following value are time averaged:

* leftFlowRateProperty
* rightFlowRateProperty
* heavySpeedBinCountsProperty
* lightSpeedBinCountsProperty
* allSpeedBinCountsProperty
* heavyKineticEnergyBinCountsProperty
* lightKineticEnergyBinCountsProperty
* allKineticEnergyBinCountsProperty

Especially with the bin counts (number of particles), it may be confusing to see non-integer values in Studio and the PhET-iO data stream.

**Comment by pixelzoom** [comment]
- [ ] Add an example for creating Maxwell-Boltzmann curve.

**Comment by pixelzoom** [comment]
-  [ ] While it's noted in the phetioDocumentation for these Properties, also note in example.md that these Properties in the Diffusion screen must be multiples of a specific delta.

* numberOfParticlesProperty: 10
* radiusProperty: 5
* initialTemperatureProperty: 50

**Comment by pixelzoom** [comment]
- [ ] Describe how to get the current state of all particles.  See https://github.com/phetsims/gas-properties/issues/231#issuecomment-2103577265.

**Comment by arouinfar** [comment]
I created examples.md for all 3 sims in the above commits, closing.
