### ISSUE TITLE
Move origin of Diffusion container to bottom center.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#228]
The origin of containers is currently at bottom right.  In the Diffusion screen, it would make more sense to have the origin at the bottom center, because of the vertical divider.   This would make centerOfMass1Property and centerOfMass2Property values relative to the divider.  Currently these values are always negative, difficult to understand, because they are relative to the bottom right of the container.

**Comment by pixelzoom** [comment]
It's not going to be possible to move the origin because all containers (in all screens) extend `BaseContainer`, which has the origin at bottom right. 

As an alternative, perhaps we can adjust the values of centerOfMass1Property and centerOfMass2Property, so that they are relative to the vertical divider.  I'll discuss with @arouinfar.

**Comment by pixelzoom** [comment]
@arouinfar ready for review.  

centerOfMass1Property and centerOfMass2Property are now relative to the center of the container, and documented like this:

```ts
phetioDocumentation: 'Center of mass for particles of type 1, relative to the center of the container.'
```

One other thing that I'm wondering about.  "Center of mass" would typically be an (x,y) position, and these Properties are the x-coordinate only.  Should we rename them to something like centerXOfMass1Property and centerXOfMass2Property?

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Looks good on main.

> One other thing that I'm wondering about. "Center of mass" would typically be an (x,y) position, and these Properties are the x-coordinate only. Should we rename them to something like centerXOfMass1Property and centerXOfMass2Property?

For consistency with the checkbox name, I would leave it as `centerOfMass`. If you think it needs clarification, you could do that in the `phetioDocumentation`. I'm fine with the way it is now, but back to you @pixelzoom to amend the documentation, if desired.

**Comment by pixelzoom** [comment]
Thanks @arouinfar.   I clarified like so in the phetioDocumentation:

```ts
phetioDocumentation: 'Center of mass for particles of type 1. This is the x offset from the center of the container.'
```

Closing.
