### ISSUE TITLE
Support setting up an initial state with specific V, T, N.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#229]
From https://github.com/phetsims/gas-properties/issues/30#issuecomment-512980763:

> **Setting an initial state for first 3 screens:**
> - [ ] Query parameters to set up specific initial state by specifying V,T,N.  Need N for light and heavy (NL, NH), one of them needs to be non-zero for this feature.  Also need to specify which screen.  V and T use their usual defaults. P is computed.  (V doesn’t apply to Energy.)
> - [ ] PhET-IO API function to do the same thing as above query parameters.
> - [ ] Load state will use the above API.  It will create a system to match a desired config. It will not restore individual particle state.

Discussed in 4/30/24 design meeting with @arouinfar and @kathy-phet. Notes:

* temperatureModel.controlTemperatureEnabledProperty and temperatureModel.initialTemperatureProperty seems like the right direction but are too complicated.
* What we want is something like temperatureModel.initialTemperatureForEmptyContainerProperty that lets us specify the desired injection temperature for an empty container.  Or maybe we can move injectionTemperatureProperty to the model base class (currently only in EnergyModel).
* No query parameters, too complicated because we need them per screen, and Diffusion screen needs to have N as multiples of 10.

**Comment by pixelzoom** [comment]
The Diffusion screen supports specification of V, T, N via these elements:

V: constant 1600 pm, cannot be changed
T: particle1Settings.initialTemperatureProperty, particle2Settings.initialTemperatureProperty
N: particle1Settings.numberOfParticlesProperty, particle2Settings.numberOfParticlesProperty

For the other 3 screens, specifying V,T,N is problematic.

N can be set via `numberOfHeavyParticlesProperty` and `numberOfLightParticlesProperty`.

V cannot be set via the PhET-iO API.  V is `container.volumeProperty`, which is derived from `container.widthProperty`, which is `phetioReadOnly: true` because it is controlled by the sim for some of the `holdConstantProperty` values. 

T is also derived and cannot be set. We started to investigate this in https://github.com/phetsims/gas-properties/issues/229#issue-2272667078. But unless we figure out a way around being able to set V, being able to set T will not be useful.  So I'm going to defer this until we discuss in 5/20 PhET-iO design meeting.

**Comment by pixelzoom** [comment]
Design meeting 5/20/24:

* add something like injectionTemperatureProperty for the first 2 screens, particle temp when the container is empty
* Punt on V for now, until some client asks for it.  Can set width manually in the meantime.
* Would be nice to be able to set the temperature of the particle system, but skip it for now.

**Comment by pixelzoom** [comment]
After more investigation.... `injectionTemperatureProperty` and `setInjectionTemperatureEnabledProperty` are part of the general TemperatureModel used by the first 3 screens.  They are currently instrumented only in the Energy screen, via the `hasInjectionTemperatureFeature` options.  Instrumenting these Properties for all 3 screens would be straightforward. But...

What is not straightforward is how these Properties should behave in the Intro and Explore screens:
* Should they be reset when the `resetAllButton` is pressed? Probably not, since they can't be changed via the UI.
* Should `injectionTemperatureProperty` apply only when the container is empty, or should it behave like the Energy screen and be used  as long as `setInjectionTemperatureEnabledProperty` is `true`?
* Do we even need `setInjectionTemperatureEnabledProperty` instrumented in the Intro and Explore screens? What purpose does it serve here?

I guess I'm still not clear on the PhET-iO use case here, and will need to discuss with @arouinfar.

**Comment by pixelzoom** [comment]
In the above commits, I cleaned up the temperature-related constants.  The value that we want to change via a Property is:

```ts
// Temperature (in K) used to compute the initial speed for particles when the container is empty and the user
// has not set a specific injection temperature.
const DEFAULT_INITIAL_TEMPERATURE = 300;
```

**Comment by pixelzoom** [comment]
@arouinfar ready for review.

I've added `defaultInitialTemperatureProperty` to the first 3 screens, details shown in Studio screenshot below.

On the subject of possible ordering problems when restoring state... I tested the Standard wrapper (Studio "Test" button) and did not see any problems.  I can't test this in the State wrapper because there is no way to set `defaultInitialTemperatureProperty` via the sim's UI.  So perhaps you can test this in what you think would be a typical use case.

<img width="804" alt="screenshot_3325" src="https://github.com/phetsims/gas-properties/assets/3046552/742a20f3-65d2-48c3-9941-9cdd2ff75c2e">

**Comment by Nancy-Salpepi** [comment]
The defaultInitialTemperatureProperty is working nicely for me!

**Comment by arouinfar** [comment]
The `defaultInitialTemperatureProperty` is working really well @pixelzoom. I haven't run into any issues while reviewing the tree. I've made a note over in #226 to include this in the examples, closing.
