### ISSUE TITLE
PhET-iO instrumentation for particles

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#231]
- [x] Use the same approach as projectile-data-lab, see: Projectile, ProjectileIO, Field, FieldIO. Check in with them to confirm how I apply this pattern.

- [x] Replace Particle's `Vector2` fields (position, previousPositive, velocity) with `number` x,y fields, so that ParticleIO will be a flat data structure.

- [x] Add ParticleIO, IdealGasLawParticleSystemIO, and DiffusionParticleSystemlO to handle serialization.

- [x] Identify other places where Particle serialization is needed.

Since this work requires fundamental chances to Particle, there is high risk for introducing regressions. For reference, 1.1.0-dev.12 was published on 5/1, before this work was started:
* https://phet-dev.colorado.edu/html/gas-properties/1.1.0-dev.12/phet/gas-properties_all_phet.html
* https://phet-dev.colorado.edu/html/gas-properties/1.1.0-dev.12/phet-io/

**Comment by pixelzoom** [comment]
In the above commits, I instrumented the arrays of particles for the particle systems. The state of particles looks pretty good in the State wrapper - positions and velocities are tracked by the downstream sim.   But I'm not convinced that this is totally correct -- sometimes the downstream sim seems to deviate.  So there's likely more work to do here.

I'd also like to take a stab at factoring a `class DiffusionParticleSystem` out of `DiffusionModel`, instead of instrumenting the latter.

**Comment by pixelzoom** [comment]
@zepumph noted that I should consider making Particle implement TPoolable.

**Comment by pixelzoom** [comment]
Above I said:
> But I'm not convinced that this is totally correct -- sometimes the downstream sim seems to deviate. 

Since there is randomness in the sim, it makes sense that there the downstream sim would deviated from the upstream sim when as they continue to run.  They will be the same only at the moment when state is set in the downstream sim.

**Comment by pixelzoom** [comment]
To get the state of the particle system for a specific screen, replace `{screenTandemName}` with the tandem name of the desired screen:

```
await phetioClient.invokeAsync( 'phetioEngine', 'getPhetioElementState', [ 'gasProperties.{screenTandemName}.model.particleSystem' ] )
```

For example, for the Ideal screen:

```
await phetioClient.invokeAsync( 'phetioEngine', 'getPhetioElementState', [ 'gasProperties.idealScreen.model.particleSystem' ] )
```

**Comment by pixelzoom** [comment]
This is looking pretty good.  I still have some questions for the PDL team (@samreid and @matthew-blackman) and @zepumph .  But in the meantime, here's a dev version:

* https://phet-dev.colorado.edu/html/gas-properties/1.1.0-dev.13/phet/gas-properties_all_phet.html
* https://phet-dev.colorado.edu/html/gas-properties/1.1.0-dev.13/phet-io/

**Comment by pixelzoom** [comment]
@arouinfar @Nancy-Salpepi @kathy-phet This is ready for review.

The state object for a single particle is shown below.  `previousX` and `previousY` are not interesting to the client, but are required for collision detection & response. Note that speed and kinetic energy are not included here; they are computed by the histograms as needed.

```ts
 {
  mass: number;
  radius: number;
  x: number;
  y: number;
  previousX: number;
  previousY: number;
  vx: number;
  vy: number;
};
```

The state of a particle _system_ is serialized as arrays of particles.  In the first 3 screens, `model.particles` includes these arrays:

```ts
heavyParticles: HeavyParticle[];  // heavy particles that are inside the container
lightParticles: LightParticle[]; // light particles that are inside the container
heavyParticlesOutside: HeavyParticle[];  // heavy particles that are outside the container
lightParticlesOutside: LightParticle[]; // light particles that are outside the container
```

In the _Diffusion_ screen, where particles are always inside the container, `model.particles` includes these arrays:

```ts
particles1: DiffusionParticle1[];
particles2: DiffusionParticle2[];
```

The follow custom IOTypes were created to support the above serialization. You can inspect them in Studio.
* HeavyParticleIO
* LightParticleIO
* IdealGasLawParticleSystemIO
* DiffusionParticle1IO
* DiffusionParticle2IO
* DiffusionParticleSystemIO

Since Studio is unable to display custom IOTypes, none of the above arrays can be inspected in Studio. (This is also true of projectiles in PDL.). To inspect the arrays, it's necessary to use the PhET-iO API.  See examples in https://github.com/phetsims/gas-properties/issues/231#issuecomment-2103577265.

Because you can't inspect particle arrays in Studio, I did not feature `model.particles.  I can imagine featuring them for IOType documentation, but I don't know how useful that is. Let me know if you'd like `particleSystem.model` to be featured.

**Comment by pixelzoom** [comment]
> @zepumph noted that I should consider making Particle implement TPoolable.

In discussion with PDL team, I noted that in the State wrapper, the Downstream sim pauses slightly each time that state is set.  PDL exhibits this same behavior.  I asked if the PDL team considered making Projectile implement TPoolable, and @samreid said that they did not optimize for that.  @samreid also did a quick test with GP in the State wrapper.  GC doe not appear to be the issue. Most of the time is spent in `getState` and `setState`, and very little time spent in the particle constructor.  Implementing TPoolable would mean calling an initializer method (like `setXY` for Vector2) instead of a constructor. Since particle is basically a data structure, there's unlikely to be any significant different between the constructor and an initializer method.  So I'm not going to pursue pooling for particles.

**Comment by pixelzoom** [comment]
Design meeting 5/20/24 @arouinfar @kathy-phet @Nancy-Salpepi @matthew-blackman @pixelzoom

We decided not to add a `type` field to particle state, something like:

`type: 'heavy' | 'light' | 'diffusion1' | 'diffusion2'`

Particles are already separated by type in the PhET-iO state.  Adding a `type` field would be redundant and add unnecessary bloat to what is a large data set.

As @matthew-blackman demonstrated in #244, a wrapper can add type information if needed.  For example in particleDataWrapper.html:

```js
        const simulationReadings = {
          'Particle speed': speedForParticle( particleData ),
          'Particle KE': kineticEnergyForParticle( particleData ),
          'Particle type': 'heavy',
          'Stopwatch reading': stopwatchReading
        };
```

**Comment by arouinfar** [comment]
Reviewed with @Nancy-Salpepi and the Particle arrays look good in the console and state appears to be restoring correctly. Closing.

**Comment by arouinfar** [comment]
Reopening, I forgot to respond to @pixelzoom's question about `phetioFeatured`

> Because you can't inspect particle arrays in Studio, I did not feature model.particles. I can imagine featuring them for IOType documentation, but I don't know how useful that is. Let me know if you'd like particleSystem.model to be phetioFeatured: true.

Let's feature `model.particleSystem`. The IOType Documentation is likely useful, but we'll also be including information about accessing particle data in examples.md. Featuring it in Studio makes it easier for clients to find and explore.

**Comment by pixelzoom** [comment]
`model.particleSystem` is now featured.  Back to @arouinfar for review, close if OK.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good on main. Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
