### ISSUE TITLE
Additional documentation for PhET-iO.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#233]
Some additional things to document for PhET-iO, in model.md, examples.md, and/or phetioDocumetation:

- [x] When running at Normal speed, 1 sec real time === 2.5 ps model time. (See TimeTransform.ts, `NORMAL`)
- [x] When running at Slow speed, 1 sec real time === 0.3 ps model time. (See TimeTransform.ts, `SLOW`)
-[x] The first 3 screens have a maximum of 1000 heavy particles + 1000 light particles. (See GasPropertiesConstants.ts, `HEAVY_PARTICLES_RANGE` and `LIGHT_PARTICLES_RANGE`)
- [x] Heavy particles have mass = 28 AMU (N<sub>2</sub>), radius = 125 pm (see GasPropertiesConstants.ts,  `HEAVY_PARTICLES_MASS` and `HEAVY_PARTICLES_RADIUS`)
- [x] Light particles have mass = 4 AMU (approximately He), radius = 87.5 pm (see GasPropertiesConstants.ts,  `LIGHT_PARTICLES_MASS` and `LIGHT_PARTICLES_RADIUS`)
- [x] Initial temperature of particles added to the container in the first 3 screens: With collisions disabled, use the mean temperature to compute initial speed, which results in wave-like behavior. With collisions enabled, create Gaussian deviation in the temperature used to compute speed, but maintain the desired mean.  This makes the motion of a group of particles look less wave-like. We do this for temperature instead of speed because temperature in the container is T = (2/3)KE/k, and KE is a function of |v|^2, so deviation in speed would change the desired temperature. (See IdealGasLawParticleSystem.ts, `addParticles`)
- [x] Temperature is updated in the model and view on every step. (See TemperatureModel.ts)
- [x] Pressure is updated in the model on every step. The Pressure gauge view is updated every 0.75 ps, using the model pressure at that time. Pressure noise is added only to the view. The noise function is described at a high level in model.md. (See PressureModel.ts, `REFRESH_PERIOD` and `step`)
- [x] Average Speed, Speed histogram, and KE histogram display the average of samples collected over 1 ps. (See EnergyModel.ts, `SAMPLE_PERIOD`)
- [x] Speed histogram has 19 bins, with bin width 170 pm/ps. (See HistogramModel.ts, `numberOfBins` and `speedBinWidth`)
- [x] Kinetic Energy histogram has 19 bins, with bin width 8E5 AMU * pm^2 / ps^2. (See HistogramModel.ts, `numberOfBins` and `kineticEnergyBinWidth`)
- [x] Flow Rate is a running average over 300 samples, updated in the model and view on every step. (See ParticleFlowRateModel.ts, `NUMBER_OF_SAMPLES`)
- [x] Center of Mass is update in the model and view on every step.

@arouinfar let's discuss where this information should live.

**Comment by pixelzoom** [comment]
@arouinfar observed that everything in above bullet list is related to time.  So I'll attempt to roll this into a new section in model.md.

**Comment by arouinfar** [comment]
Reviewed with @Nancy-Salpepi and the changes look good, thanks @pixelzoom!
