### ISSUE TITLE
PhET-iO support for data fluency

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#236]
We've had 2 meetings (4/31/24, 5/6/24) to discuss Gas Properties in the context of statistics, data science, CODAP, etc. 

Looking at the [PhET-iO Design document](https://docs.google.com/document/d/1VTPqRdh9OPsUDFhd8KfWRS_MGOYlDUeb0JqsHkL2r2Q/edit?pli=1#heading=h.qfx24bhz5uem).... I've added links to the Zoom recordings of those meetings.  But it does not look like anyone took notes, or summarized conclusions.  And I don't recall anything actionable from those meetings.

Assigning to @arouinfar and @kathy-phet to identify requirements.  High priority, since instrumentation is very far along at this point.

**Comment by pixelzoom** [comment]
5/20/24 design meeting: @arouinfar @kathy-phet @pixelzoom 

* No major PhET-iO changes as the result of the data fluency meerings.
* We do not need to collect histogram (and other) samples.
* We do need to collect particle data (which is already supported).
* Change pressure meter to Gaussian noise model -- @matthew-blackman will take a stab at this.

**Comment by pixelzoom** [comment]
> @arouinfar will review the recordings of the data fluency meetings, so see if there is anything that was missed.

@arouinfar Feel free to close this after reviewing the meeting recordings.

**Comment by arouinfar** [comment]
Nothing to add to the list in https://github.com/phetsims/gas-properties/issues/236#issuecomment-2120765007, closing.
