### ISSUE TITLE
Dynamic layout problem with Sample Period combo box

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#237]
Reported by @arouinfar in https://github.com/phetsims/gas-properties/issues/201#issuecomment-2073571632:

I reviewed on main with `stringTest=dynamic` and overall the behavior looks good. The Sample Period ListBox sizing looks off, though. 

Steps to reproduce
1. Run the sim with `stringTest=dynamic` and select Ideal Screen
2. Open the Sample Period ComboBox 
3. Use the right arrow a few times to increase string length.
4. Use the left arrow to return the strings to their default length. The ListBox width remains wide:
  ![image](https://github.com/phetsims/gas-properties/assets/8419308/318f01b5-e905-4faf-b1fe-e6ad7af9e06a)

**Comment by pixelzoom** [comment]
Comments starting at https://github.com/phetsims/gas-properties/issues/201#issuecomment-2073575074:

@arouinfar 4/23/24
> @pixelzoom seems like the ListBox sizing issue is sim-specific. I can't reproduce in other sims on main, such as Geometric Optics.

@pixelzoom 4/23/24
> > The Sample Period ListBox sizing looks off, though. ...
>
> I had this exact problem in previous sims. It was reported and fixed (?) in https://github.com/phetsims/sun/issues/785. 
> I don't see anything unusual in how I'm creating the sample period combo box, see SamplePeriodComboBox.ts.

@pixelzoom 4/23/24:
> I'm stumped. @jonathanolson did the dynamic layout for ComboBox, and fixed https://github.com/phetsims/sun/issues/785.  Perhaps he can help here.  The steps to reproduce are described in https://github.com/phetsims/gas-properties/issues/201#issuecomment-2073571632.  The relevant code is SamplePeriodComboBox.ts.

**Comment by pixelzoom** [comment]
I broke this out into its own issue, in hope that it will get some attention.  @jonathanolson ping.

**Comment by jonathanolson** [comment]
Reproducing, looks like it's a failure to keep the list item content positioned over the highlight rectangle. Investigating why.

**Comment by jonathanolson** [comment]
Can you verify the fix above?

**Comment by pixelzoom** [comment]
Confirmed that this is fixed. Thanks @jonathanolson. Closing.
