### ISSUE TITLE
PhET-iO instrumentation of sampling models

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#241]
Related to #231 (PhET-iO instrumentation for particles) and #236 (PhET-iO support for data fluency) ...

The following things sample the particle system:
* AverageSpeedModel - the Average Speed accordion box in the Energy screen, an average of samples collected during a fixed period of time
* HistogramModel - the Speed and KE histograms in the Energy screen, an average of samples collected during a fixed time period
* ParticleFlowRateModel - the flow rate arrows shown in the Diffusion screen, a running average of a constant number of samples

For each of these, the samples need to be stateful.  For the elements that involve a fixed time period, the accumulated time must also be stateful.

**Comment by pixelzoom** [comment]
Most of this work was done as part of #30, #77, and #231.    In the above commits, documentation for IOTypes was improved.

**Comment by pixelzoom** [comment]
@arouinfar @Nancy-Salpepi @kathy-phet This is ready for review.   Below is a summary of the relevant PhET-iO elements.

### Average Speed

`heavyAverageSpeedProperty` and `lightAverageSpeedProperty` are the (running) average speeds for heavy and light particles respectively, as displayed in the Average Speed accordion box.  These Properties are `phetioFeatured: true`.

`averageSpeedModel` handles serialization of internal elements that are used to derive the above Properties.  All of its fields are for internal use only, so it is `phetioFeatured: false`. AverageSpeedModelIO is its IOType, which looks like this in Studio:
<img width="754" alt="screenshot_3300" src="https://github.com/phetsims/gas-properties/assets/3046552/e7bc2b22-314e-482e-a3e0-10a34c292ef0">

### Speed and KE histograms

`heavyKineticEnergyBinCountsProperty`, `lightKineticEnergyBinCountsProperty`, and `totalKineticEnergyBinCountsProperty` are the bin counts displayed by the Kinetic Energy histogram. These Propertes are `phetioFeatured: true`.

`heavySpeedBinCountsProperty`, `lightSpeedBinCountsProperty`, and `totalSpeedBinCountsProperty` are the bin counts displayed by the Speed histogram. These Propertes are `phetioFeatured: true`.

`histogramsModel` handles serialization of internal elements that are used to derive the above Properties.  All of its fields are for internal use only, so it is `phetioFeatured: false`. HistogramsModelIO is its IOType, which looks like this in Studio:
<img width="763" alt="screenshot_3301" src="https://github.com/phetsims/gas-properties/assets/3046552/5f7da74a-6460-4ee7-8f8d-2187af90e844">

### Particle Flow Rate

`particle1FlowRateModel.leftFlowRateProperty` and `particle1FlowRateModel.rightFlowRateProperty` are the left and right flow rates displayed for particles of type 1. These Propertes are `phetioFeatured: true`.

`particle2FlowRateModel.leftFlowRateProperty` and `particle2FlowRateModel.rightFlowRateProperty` are the left and right flow rates displayed for particles of type 2. These Propertes are `phetioFeatured: true`.

`particle1FlowRateModel` and `particle2FlowRateModel` handle serialization of internal elements that are used to derive the above Properties. All of their fields are for internal use only, so they are `phetioFeatured: false`.  ParticleFlowRateModelIO is their IOType, which looks like this in Studio:
<img width="750" alt="screenshot_3302" src="https://github.com/phetsims/gas-properties/assets/3046552/49e72ab8-6ff5-40ec-b84a-8f52e6dc5919">

**Comment by pixelzoom** [comment]
@arouinfar and @Nancy-Salpepi noted a potential problem with restoring state for the Speed histogram, tracking in #261.

@arouinfar @Nancy-Salpepi if everything else looks OK here, and the state schemas look reasonable, please close this issue.

**Comment by arouinfar** [comment]
> @arouinfar @Nancy-Salpepi if everything else looks OK here, and the state schemas look reasonable, please close this issue.

Looks good, closing.
