### ISSUE TITLE
Update Screenshots for 1.1 Release

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#247]
Related to #191 

We should update the screenshots for the Explore screen to display the changes made in #220. I'll likely retake all screenshots so the navbar looks consistent across all screens.

Marking as on-hold until we are closer to release.

**Comment by pixelzoom** [comment]
Reminder that this needs to be done for all 3 sims in the suite.

**Comment by arouinfar** [comment]
@pixelzoom I updated the screenshots for all 3 sims on main and 1.1 in the above commits. Closing.
