### ISSUE TITLE
Change justification of checkbox icons?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#248]
@arouinfar Do you want the icons for these checkbox to be right justified?  I'm not a fan of that approach, but I realize that it's what most sims are doing.

<img width="264" alt="screenshot_3321" src="https://github.com/phetsims/gas-properties/assets/3046552/e3e485c2-4c62-4261-8ca7-3a01aaa1eec2">

<img width="347" alt="screenshot_3320" src="https://github.com/phetsims/gas-properties/assets/3046552/07d12c5f-a37a-4aaf-9564-80629aaabdc4">

**Comment by pixelzoom** [comment]
Spoke with @arouinfar, yes please aligning right.

**Comment by pixelzoom** [comment]
@arouinfar ready for review, close if OK.

<img width="258" alt="screenshot_3324" src="https://github.com/phetsims/gas-properties/assets/3046552/50eaa706-b579-4f52-b943-bbd5a70fa1cb">
<img width="340" alt="screenshot_3323" src="https://github.com/phetsims/gas-properties/assets/3046552/4cdad6df-f234-4169-8b5f-83363f370fac">

**Comment by arouinfar** [comment]
Looks great, thanks @pixelzoom! Closing.
