### ISSUE TITLE
Collision Counter should be off by default

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#249]
Discovered during review for #30 

@Nancy-Salpepi noticed that the Collision Counter is on by default, which differs from the published version the simulation.

Given that the Collision Counter isn't central to the primary learning goal (PV=NkT), let's keep it off by default.

**Comment by pixelzoom** [comment]
This bug was introduced by @zepumph in https://github.com/phetsims/gas-properties/commit/1b7cbcbfb15705d301519e6ec65048068d75832a way back on 1/9/23, apparently for work that he was doing in chipper.  Fixed in the above commit.

@Nancy-Salpepi please verify in main, close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks good in main. Closing.
