### ISSUE TITLE
Make `heatCoolAmountProperty` read-only on all screens

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#250]
For #30 

The `heatCoolAmountProperty` is read-only on the Ideal Screen, as the model needs to automatically heat/cool, depending on the Hold Contant mode. However, it is API-settable on the Explore and Energy screens. We made a design decision for the HeaterCoolerNode to snap-to-zero when not user-controlled, and we don't allow the snap-to-zero behavior to be turned off with a query parameter, as we do in EFAC and SoM. Allowing clients to control `heatCoolAmountProperty` is inconsistent with these decisions.

@pixelzoom please make `heatCoolAmountProperty` read-only on all screens.

**Comment by pixelzoom** [comment]
`heatCoolAmountProperty` is now read-only for all screens.  @arouinfar please review, close if OK.
