### ISSUE TITLE
Remove "Cumulative" from `heavySpeedCumulativeBinCountsProperty`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#251]
For #30 

For the most part, the tandems for histogram bin counts follow the same pattern of {{speciesHistogramType}}BinCountsProperty:
![image](https://github.com/phetsims/gas-properties/assets/8419308/b110f381-c8f0-4107-81fb-ff1b2e33b8ce)

`heavySpeedCumulativeBinCountsProperty` is an outlier. For consistency, let's remove "Cumulative".

**Comment by pixelzoom** [comment]
This was a buggy tandem name, fixed in the above commits.  @arouinfar please review, close if OK.

**Comment by arouinfar** [comment]
Looks good on main, closing.
