### ISSUE TITLE
Uninstrument `resizeHandleNode` on the Energy Screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#252]
For #30 

The container on the Energy Screen has a fixed volume and the handle is permanently hidden via `resizeHandleVisibleProperty`. However, the `resizeHandleNode` is still instrumented including the `hasResizeHandleProperty`, which is confusing.
![image](https://github.com/phetsims/gas-properties/assets/8419308/e866e4dc-324c-4d17-9de0-d1b70d7347a8)

@pixelzoom if possible, please uninstrument the `resizeHandleNode` on the Energy Screen.

**Comment by pixelzoom** [comment]
In addition to uninstrumenting `resizeHandleNode `.... It seems like the the structure under `containerNode` is a little off.   So I reorganized as shown below.   @arouinfar please review, close if OK.

Ideal and Explore screens:

<img width="345" alt="screenshot_3340" src="https://github.com/phetsims/gas-properties/assets/3046552/d370a18b-1a7f-43d0-a332-46d2636941d9">

Energy screen:

<img width="264" alt="screenshot_3338" src="https://github.com/phetsims/gas-properties/assets/3046552/c71003cd-8383-4684-a52d-581bdd59d717">

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom! Closing.
