### ISSUE TITLE
Link `model.histogramsModel` under each `histogramNode`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#253]
For #30 

It would be helpful to link the histogram data, found under `model.histogramsModel` to the `histogramNode` view element.
![image](https://github.com/phetsims/gas-properties/assets/8419308/f64e36f4-2f1a-4139-b3fa-7395a482781c)

My initial instinct was to add a link to the specific histogram, but it seems like the `histogramsModel.kineticEnergy` and `histogramsModel.speed` are just organizational and not instrumented things. (Nothing shows up in the Element Panel when I select them in the tree.) 
![image](https://github.com/phetsims/gas-properties/assets/8419308/231f544a-4c04-42ac-ae29-5bf81df9ca3b)

If I'm mistaken and we can link to `histogramsModel.kineticEnergy` and `histogramsModel.speed`, let's do that. Otherwise, linking to `histogramsModel` is perfectly fine.

@pixelzoom please
- [x] Add a link to the model data for each `histogramNode`
- [x] So that these newly-added links appear in the Featured tree, make `histogramNode` and the target of the links `phetioFeatured: true`.

**Comment by pixelzoom** [comment]
> If I'm mistaken and we can link to histogramsModel.kineticEnergy and histogramsModel.speed, let's do that. Otherwise, linking to histogramsModel is perfectly fine.

Linking to `histogramsModel.kineticEnergy` and `histogramsModel.speed` would require some relatively major code changes.  So I linked to `histogramsModel`, and added `phetioFeatured: true` where requested.

@arouinfar please review, close if OK.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! Looks good in main, closing.
