### ISSUE TITLE
Create `checkboxGroup` for species checkboxes in histograms

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#254]
For #30 

The Speed and Kinetic Energy histograms have checkboxes to display the data for a single particle type. 
![image](https://github.com/phetsims/gas-properties/assets/8419308/9ac7f6b0-38b1-4182-98e3-ef9450940e68)

I can see a client wanting to hide both checkboxes, but not just one. @Nancy-Salpepi and I think it would be nice to create a `checkboxGroup` that contains both `heavyParticlesCheckbox` and `lightParticlesCheckbox`.  We could then feature `checkboxGroup.visibleProperty` and uninstrument the individual child `checkbox.visibleProperty`. 

I recognize that request is treading into scope-creep territory, so feel free to veto @pixelzoom.

**Comment by pixelzoom** [comment]
@arouinfar please review, close if OK.
