### ISSUE TITLE
Create `pressureAtmospheresProperty`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#256]
For #30 

Under `pressureModel`, we provide the pressure value with and without noise in kPa, but only provide the noisy version for atm.
![image](https://github.com/phetsims/gas-properties/assets/8419308/16c09b58-a714-47cf-ac42-46336805df2e)

@pixelzoom can we create  `pressureAtmospheresProperty` so clients can access the pressure in atm without noise?

**Comment by pixelzoom** [comment]
@arouinfar please review, close if OK.

**Comment by arouinfar** [comment]
Looks good, closing!
