### ISSUE TITLE
Updates to `phetioFeatured`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#257]
For #30 

@pixelzoom did a great job of featuring elements, and we found relatively few things during the tree review.

Here's the list of things we'd like to feature. While I specified things on the `idealScreen`, the `phetioFeatured` metadata should be the same for all relevant screens.

```ts
/* eslint-disable */
window.phet.preloads.phetio.phetioElementsOverrides =
  {
    "gasProperties.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.simulationPreferencesPanel.pressureNoiseControl.visibleProperty": {
      "phetioFeatured": true
    },
    "gasProperties.idealScreen.model.pressureModel": {
      "phetioFeatured": true
    },
    "gasProperties.idealScreen.model.temperatureModel": {
      "phetioFeatured": true
    },
    "gasProperties.idealScreen.view.heaterCoolerNode.visibleProperty": {
      "phetioFeatured": true
    },
    "gasProperties.idealScreen.view.oopsDialogs.oopsMaximumTemperatureDialog": {
      "phetioFeatured": true
    },
    "gasProperties.idealScreen.view.panels.particlesAccordionBox.numberOfHeavyParticlesControl.visibleProperty": {
      "phetioFeatured": true
    },
    "gasProperties.idealScreen.view.panels.particlesAccordionBox.numberOfLightParticlesControl": {
      "phetioFeatured": true
    },
    "gasProperties.idealScreen.view.pressureGaugeNode.visibleProperty": {
      "phetioFeatured": true
    },
    "gasProperties.idealScreen.view.thermometerNode.visibleProperty": {
      "phetioFeatured": true
    }
  };
  ```
Some clarification around `oopsDialog`:

 @Nancy-Salpepi noticed that the Oops Dialogs all had linked StringProperties. These links seem helpful because it can be inconvenient to trigger the Oops Dialog to autoselect the string. However, because the dialog itself is not featured, the LinkedProperties don't show up in the Featured tree. @pixelzoom I included just a single `oopsDialog` in the list above, but please make all Oops Dialogs featured on all screens.

**Comment by pixelzoom** [comment]
These 2 requests look inconsistent:

```json
    "gasProperties.idealScreen.view.panels.particlesAccordionBox.numberOfHeavyParticlesControl.visibleProperty": {
      "phetioFeatured": true
    },
    "gasProperties.idealScreen.view.panels.particlesAccordionBox.numberOfLightParticlesControl": {
      "phetioFeatured": true
    },
```

So I featured:
* `numberOfHeavyParticlesControl`
* `numberOfHeavyParticlesControl.visibleProperty`
* `numberOfLightParticlesControl`
* `numberOfLightParticlesControl.visibleProperty`

@arouinfar please review, close if OK.

**Comment by arouinfar** [comment]
> These 2 requests look inconsistent

You're right, my bad. I meant to feature the `visibleProperty` of both controls. That said, I don't see any harm in featuring the control itself. 

Looks good on main, thanks @pixelzoom. Closing.
