### ISSUE TITLE
Revisit the order of panels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#259]
Related to https://github.com/phetsims/gas-properties/issues/213, @arouinfar and @Nancy-Salpepi would like to revisit the order of the panels at the right edge of the Ideal, Explore, and Energy screens.

**Comment by pixelzoom** [comment]
Design meeting 6/13/2024 @arouinfar @Nancy-Salpepi @kathy-phet @ariel-phet @KatieWoe

Decisions for first 3 screens:
* Move Particles accordion box to the top
* Move Tools panel to the bottom

**Comment by pixelzoom** [comment]
@arouinfar @Nancy-Salpepi Ready for review. Note. that removing vertical space when accordion boxes are collapsed will be done in https://github.com/phetsims/gas-properties/issues/264.

**Comment by Nancy-Salpepi** [comment]
Looks great! Thanks @pixelzoom!

**Comment by arouinfar** [comment]
The new panel order is feeling good to me. Once focus order is settled in #213, let's ask the rest of the team to review.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/gas-properties/issues/213 is done.  Let's get sign-off from @Nancy-Salpepi and @kathy-phet.

**Comment by Nancy-Salpepi** [comment]
Commented last week. Looks good to me!

**Comment by kathy-phet** [comment]
Panel order looks good to me too.

**Comment by pixelzoom** [comment]
We have consensus, so closing.
