### ISSUE TITLE
Revisit design of the "Particles" accordion box

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#260]
@arouinfar and @Nancy-Salpepi wondered why the "Particles" accordion box is not simply a panel.   Or why it's not expanded by default, since it's the most efficient way of adding particles. 

The design document specifies that it's an accordion box, but I don't see any information about why.  I suspect that collapsing it makes things less quantitative.  And it's collapsed by default to encourage use of the more "fun" (and entirely redundant) way of adding particles via the bicycle pump.

In the Java version, these controls were part of the monolithic control panel along the right edge of the sim, and could not be hidden.

**Comment by pixelzoom** [comment]
Design meeting 6/13/2024 @arouinfar @Nancy-Salpepi @kathy-phet @ariel-phet @KatieWoe

Decisions for first 3 screens:
* Move Particles accordion box to the top.
* Make Particles acccordion box expanded by default.

**Comment by pixelzoom** [comment]
@arouinfar @Nancy-Salpepi Ready for review. Note. that removing vertical space when accordion boxes are collapsed will be done in #264.

**Comment by Nancy-Salpepi** [comment]
Everything looks great @pixelzoom!

**Comment by arouinfar** [comment]
Thanks @pixelzoom! I like the new panel ordering. I think once alt input ordered is settled in #213, it would be good to ask the rest of the team to review.

**Comment by arouinfar** [comment]
> I think once alt input ordered is settled in https://github.com/phetsims/gas-properties/issues/213, it would be good to ask the rest of the team to review.

Oops, I was thinking this was #259. There was a consensus to start with Particles open in the design meeting, so I'll close.
