### ISSUE TITLE
Heavy/Light histograms don't reset 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#262]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
Seen while testing https://github.com/phetsims/gas-properties/issues/261, the blue and red histogram outlines remain after unchecking the corresponding checkbox and pressing Reset All.

**Steps to reproduce**
1. On the Energy Screen, add some blue and red particles
2. Open the KE accordion box
3. Check the Heavy and Light Particles checkboxes for both histograms
4. Uncheck the Heavy and Light Particles checkboxes for both histograms
5. Press Reset All

**Visuals**
<img width="239" alt="Screenshot 2024-06-13 at 8 25 49 AM" src="https://github.com/phetsims/gas-properties/assets/87318828/2355c858-7b55-4df5-b4ab-1e49ce27a958"> <img width="239" alt="Screenshot 2024-06-13 at 8 26 00 AM" src="https://github.com/phetsims/gas-properties/assets/87318828/95b3f69c-2aad-4e45-80d3-a79b209b2d11">

**Comment by arouinfar** [comment]
After Reset All, if you add more particles to the container, the heavy/light lines will not update until the checkboxes are checked again. 

1. Follow NS's steps in https://github.com/phetsims/gas-properties/issues/262#issue-2351022942
2. Add particles to the container. Notice that the heavy/light outlines remain unchanged. 
    <img width="270" alt="image" src="https://github.com/phetsims/gas-properties/assets/8419308/6590059e-5f9c-4552-bb25-9ad196f450c0"> 
3. Check the heavy/light checkboxes, and they will start updating again.
    <img width="265" alt="image" src="https://github.com/phetsims/gas-properties/assets/8419308/955d4186-5cf4-4fda-84d1-8e06e20b6600">

**Comment by arouinfar** [comment]
Actually... this isn't just a bug with reset all. Anytime the checkboxes are unchecked, the line remains visible. The data displayed corresponds to the moment the checkbox was unchecked and will not update until the checkbox is checked again.

**Comment by pixelzoom** [comment]
Whoopsie... Fixed in the above commit.  @Nancy-Salpepi please review, close if OK.

**Comment by Nancy-Salpepi** [comment]
Fixed! Closing.
