### ISSUE TITLE
Inform translators about new strings in 1.1 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#266]
... to be done after 1.1 is published for #191.

This is relevant to all 3 sims in the suite: gas-properties, gases-intro, and diffusion.

**Comment by pixelzoom** [comment]
Here are the strings that are new in the 1.1 release.

```json
  "wallVelocity": {
    "value": "Wall Velocity"
  },

  "pressureNoiseDescription": {
    "value": "Adds a bit of noise to the pressure gauge to make it look more realistic."
  },

  "oopsTemperatureOpen": {
    "value": "Oops!<br><br>Temperature cannot be held constant<br>when the container is open."
  },

  "keyboardHelpDialog.changeUnites": {
    "value": "Change Units"
  }
```

**Comment by pixelzoom** [comment]
In Slack#dev-public, @arouinfar said:

> The sim admin page has a utility to send out an email to trusted translators. I can do that when we publish.

**Comment by pixelzoom** [comment]
1.1.0 has been published, so translators can be notified at any time.

**Comment by arouinfar** [comment]
Notification sent, closing.
