### ISSUE TITLE
Lid is not resized when sim is paused.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#269]
Reported by @Nancy-Salpepi. This is not a new problem, and occurs in the 1.0 production version, as well as in main.

Steps to reproduce:
1. Start the sim.
2. Go to Ideal screen.
3. Fill the container with particles until the lid blows.
4. Pause the sim.
5. Press the "Return Lid" button.
6. Make the container smaller until the "Return Lid" button reappears. Note that the lid is not resized or repositioned, as shown in the 1st screenshot below.
7. Make the container larger. Note that the lid is not resized or repositioned, as shown in the 2nd screenshot below.

<img width="1104" alt="screenshot_3374" src="https://github.com/phetsims/gas-properties/assets/3046552/4815bbef-de2a-4150-956b-28e4c79cb040">
<img width="1108" alt="screenshot_3375" src="https://github.com/phetsims/gas-properties/assets/3046552/66cb2dee-002b-404f-bca1-7c16c4579503">

**Comment by pixelzoom** [comment]
Relevant bits of code are in IdealGasLawContainer.ts: `lidWidthProperty`, `setWidth`, `setDesiredWidth`, `resizeImmediately`

**Comment by pixelzoom** [comment]
Note that #269, #276, and #280 are all bad State Wrapper behavior when the sim is paused.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi please review, close if OK.  @arouinfar feel free to have a look too.  

Details:

The problem here is that while the lid looks like it is still on the container, it is actually off of the container, but has not yet begun its "spinning" animation.  And when the lid is off of the container, resizing the container does not resize the lid.  So the sim is actually behaving correctly, but what we're showing is confusing.

I discussed this with @arouinfar, and a reasonable change is to immediately move the lid up a bit (10 pixels seems sufficient) when the "Return Lid" button is made visible.  The lid animation will then start from this position.  That has been implemented in https://github.com/phetsims/gas-properties/commit/8be84b9a2b7b991336e4bb9ee40775203a4c54e6.

So following the steps in https://github.com/phetsims/gas-properties/issues/269#issue-2360219523 will now look like the screenshots below. This (hopefully) makes it clear that the lid is not on the container, and eliminates the expectation that the lid should resize when the container is resized.

<img width="1211" alt="screenshot_3404" src="https://github.com/phetsims/gas-properties/assets/3046552/e0419869-e597-4031-846a-d34334524584">
<img width="1211" alt="screenshot_3405" src="https://github.com/phetsims/gas-properties/assets/3046552/90db25fd-c7cb-4d55-8035-14b747c3c3ae">

**Comment by Nancy-Salpepi** [comment]
Working as you described. 
Closing.
