### ISSUE TITLE
User question: divide isobaric process

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gas-properties#27]
> I think that ISOBARIC process should be divided in two aspects.
> 
>  
> 
> The piston is free of every (human or external) forces and control. Only the gas’s systole/diastole is able to control the piston. So, we provide some heat and then we may see the piston move to the left (gas expansion). So, the little man at the bottom of the piston should be eliminated, because it gives the impression that he is provoking the piston’s displacement. But this is not the case. In this case, the piston’s displacement is a result of the cause “Τhermal Energy provision (Q>0 or <0)”.
> The piston now is not free. The little man controls it, so it can move it to the left or to the right. The man now is the ‘cause’. But, in order for pressure to remain invariable, we must provide specific amount of Τhermal Energy (Q>0 or <0).
>  
> 
> So, the RadioButton “Pressure”, could have two additional tree-RadioButtons where there should be selected who is the ‘cause’
> 
> i)                    thermal energy (heat/cold) or
> 
> ii)                   piston displacement (which then demands heat/cold provision to the dispenser, so that the pressure remains the same)).
> 
>  
> 
> This might sound somehow self-evident for clever people, but for weak students like me, it is not. When I see this little man pull/pulling the piston in a moment that the primary cause is the Thermal Heat provision, I translate what I see as if the little man is a simultaneous additional ‘cause’. A combination of i) and ii), that is, both ‘causes’ act simultaneously, appears without meaning. Because if we want pressure to remain constant, then if we provoke one act < i) or ii) >, then specific actions should be done: i) do nothing and let the piston act freely, ii) control the piston at will, but then we are constrained to provide specific amount of thermal energy. It is clear that we have to modify the ideal gas equation so that in the first case V=V(T) and in the second case T = T(V), P = const.
> 
>  
> 
> The work done, however, will be the same in both cases. No matter who provokes what!
> 
>  
> 
>  
> 
> You see, when it comes to draw graphs or revise theory or even worst, solve exercises (never solved actually without the solution manual!!!!!!!!) such relativity clarifications (who-is-who and when) really may help or may confuse even worst.
> 
>  
> 
> Thank you or being patient to hear perhaps something without any sense.

**Comment by arouinfar** [comment]
@oliver-phet I believe the current Gas Properties design already addresses the user's concerns.

* We have removed the figure that pushes against the container wall
* We will allow users to hold the pressure & temperature constant or pressure & volume constant, like so:
![image](https://user-images.githubusercontent.com/8419308/38440163-b2cc75ea-399d-11e8-9985-e565c510da45.png)

Can you respond to the user and thank them for their input, and let them know these are issues we are planning to address in the HTML5 version?

**Comment by oliver-phet** [comment]
replied to user. closing.

**Comment by arouinfar** [comment]
@oliver-phet Unfuddle Ticket [#3770](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3770) contains a similar request. 

In particular, this change should address the user's request. 

> Constant pressure mode will have two options (i) the model will automatically add/remove heat to maintain constant pressure, and (ii) the model will automatically change the volume to maintain constant pressure.
