### ISSUE TITLE
Interactive highlights for Number of Particles Controls behaves oddly   

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#272]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1100 on the first three screens: with interactive highlights on, there is a highlight around the entire group when hovering the pointer over the number display/disabled buttons of the `numberOfHeavyParticlesControl` or `numberOfLightParticlesControl` . Moving the pointer over one of the enabled spinners highlights only that button. 

Should there be a thin highlight around the entire control and then the thicker highlight around the buttons when I hover on them or should there be no highlight around the entire group?
 
**Steps to reproduce**
1. Turn on Interactive Highlights in the Preferences Menu
2. On any of the first 3 screens, move the pointer over the number display or disabled buttons in `numberOfHeavyParticlesControl` 
3. Move the pointer to one of the increment buttons

**Visuals**

https://github.com/phetsims/gas-properties/assets/87318828/cfb43dae-d6cd-4213-a917-4663cab017ae

**Comment by pixelzoom** [comment]
@Nancy-Salpepi please verify, close if OK.

**Comment by Nancy-Salpepi** [comment]
Fixed! Closing.
