### ISSUE TITLE
Interactive highlight missing from bicycle pump

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#273]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1100, the bicycle pump is missing the interactive highlight for the mouse.

**Visuals**

https://github.com/phetsims/gas-properties/assets/87318828/05ffd75a-334d-4e73-b34c-9f0964b9d524

**Comment by pixelzoom** [comment]
The interactive highlight was missing in common code, should have been added as part of https://github.com/phetsims/scenery-phet/issues/848.  I've fixed that in https://github.com/phetsims/scenery-phet/commit/74f11211b54233e4355a5694ad1a7c331035cf50.

@Nancy-Salpepi please verify, close if OK.

**Comment by Nancy-Salpepi** [comment]
Fixed on main. Closing.
