### ISSUE TITLE
What color should the resize handle be?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#274]
While testing https://github.com/phetsims/qa/issues/1100, I noticed that the resize handle is brassy on the Ideal Screen and gray (same color as lid handle) on the Explore Screen. 
I see that @arouinfar mentioned changing the color [here](https://github.com/phetsims/gas-properties/issues/220#issuecomment-2073212086), but it was never changed. @arouinfar which color did you want the resize handle to be?

<img width="227" alt="Screenshot 2024-06-21 at 1 35 32 PM" src="https://github.com/phetsims/gas-properties/assets/87318828/a20e13d0-0c5c-459d-b596-6a83e966f046"> <img width="227" alt="Screenshot 2024-06-21 at 1 35 20 PM" src="https://github.com/phetsims/gas-properties/assets/87318828/11d7935f-3ebc-455f-a599-03c89ce58da0">

**Comment by pixelzoom** [comment]
See below for the design document specification for handle color. I've never been a fan of this. It's too subtle and even potentially confusing. For anyone who does notice the color difference, the color alone is incapable of communicating what's intended here.  My vote would be to use the same handle color in all cases.

<img width="639" alt="screenshot_3385" src="https://github.com/phetsims/gas-properties/assets/3046552/205f9357-dbed-448e-ab8c-c704f453904f">

**Comment by pixelzoom** [comment]
@arouinfar @Nancy-Salpepi and I decided in standup meeting to use the same handle color (grey) for both screens.

**Comment by pixelzoom** [comment]
@arouinfar please review, close if OK.  Be sure to check in Color Editor, where the handle colors are `resizeHandleColor` and `lidHandleColor`.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi  please review, close if OK.  Be sure to check in Color Editor, where the handle colors are `resizeHandleColor` and `lidHandleColor`.

**Comment by Nancy-Salpepi** [comment]
Handle colors are now the same. Thanks!
