### ISSUE TITLE
Set State problems with particle locations and container width

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#276]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1100, and possibly related to https://github.com/phetsims/gas-properties/issues/269 in the State Wrapper on all screens, the first time I set state with the sim paused, the state of the particles in the downstream sim matches the upstream. If I unpause the upstream sim and allow the particles to move a bit before pausing again, the downstream sim will not match the upstream sim when setting state. Everything else does update (the graphs, pressure, temperature etc). Once I press play, the particles in the downstream sim update. On Reset All the state is correctly set. 

This also happens whens I resize the container. It will not update the second time I set state. 

**Steps to reproduce**
Here is an example:
1. In the State Wrapper, set state rate = 0
2. In the upstream sim on the Ideal Screen add a bunch of particles and then hit Pause
3. Press Set State Now
4. In the upstream sim, press Play
5. After the particles have obviously changed locations, press Pause 
6. Press Set State Now

**Visuals**

https://github.com/phetsims/gas-properties/assets/87318828/e252a7c1-f86d-4f39-bc44-42f5e48d0761

<img width="545" alt="Screenshot 2024-06-24 at 2 02 16 PM" src="https://github.com/phetsims/gas-properties/assets/87318828/d668342a-f200-420e-a956-78b2f38381a1">

**Comment by KatieWoe** [comment]
I see this in the 4th screen as well.
![pausedstate](https://github.com/phetsims/gas-properties/assets/41024075/59b108b5-b91f-451d-8132-79686af9ab51)

**Comment by pixelzoom** [comment]
Note that #269, #276, and #280 are all bad State Wrapper behavior when the sim is paused.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi said:
> This also happens when I resize the container. It will not update the second time I set state.

Fixed in https://github.com/phetsims/gas-properties/commit/e8aaef06d04576205ae4364a335801c80986dc97.

**Comment by pixelzoom** [comment]
The reason that the particles updated the first time that state was set is that the number of particles had changed, and that triggers an update of the view.  When the number of particles is constant, and all that changes is their positions, there was nothing telling the view to update when state was set. In https://github.com/phetsims/gas-properties/commit/98b2d2d886e7f407188e5f70af451543a3ed1cec, I added a listener that explicitly calls `particleSystemNode.update` when state is restored while the sim is paused. 

So... The particles and container size should now update correctly when state is set while the sim is paused.

@Nancy-Salpepi please verify, close if OK.

**Comment by Nancy-Salpepi** [comment]
Working great! Closing.

**Comment by Nancy-Salpepi** [comment]
It works correct on main but not in 1.1.0-rc.1

**Comment by pixelzoom** [comment]
> It works correctly on main but not in 1.1.0-rc.1

This would be typical of a missing cherry-pick.   But the commits above were all made before the 1.1 branch was created on 7/10/24 @ 5:55PM.  Investigating...

**Comment by pixelzoom** [comment]
I confirmed that the changes in all of the above commits are present in the gas-properties 1.1 branch.

**Comment by pixelzoom** [comment]
For particle positions, broken in 1.1.0-rc.1, OK in main.  

For container size, OK in both 1.1.0-rc.1 and main.

@Nancy-Salpepi is that what you are seeing too?

**Comment by Nancy-Salpepi** [comment]
Yes that is what I see @pixelzoom

**Comment by pixelzoom** [comment]
Ugh... The problem is a difference between built and unbuilt versions.   The workaround added in https://github.com/phetsims/gas-properties/commit/98b2d2d886e7f407188e5f70af451543a3ed1cec looks like this:

```ts
    if ( assert && Tandem.PHET_IO_ENABLED ) {
      phet.phetio.phetioEngine.phetioStateEngine.stateSetEmitter.addListener( () => {
        if ( !model.isPlayingProperty.value ) {
          particleSystemNode.update();
        }
      } );
    }
```

That chunk of code was copied from elsewhere, from a case that we want to execute only if assertions are enabled. But assertions are stripped out in built versions, so the workaround never gets executed.

**Comment by pixelzoom** [comment]
The primary fix is https://github.com/phetsims/gas-properties/commit/081fbea01ad209885339f00de5cf069327b7c266, the other commits are for patching release branches.

@Nancy-Salpepi please review.  You can test unbuilt using main in phetmarks.  You can use [1.2.0-dev.1](https://phet-dev.colorado.edu/html/gas-properties/1.2.0-dev.1/phet-io/) for the built version.  Leave this open for verification in 1.1.0-rc.2.

**Comment by Nancy-Salpepi** [comment]
Looks good in 1.2.0-dev.1 and on main.

**Comment by Nancy-Salpepi** [comment]
@pixelzoom on the Diffusion Screen using Studio/State I noticed that if I increase the radius of either particle and then launch the sim, the particles in the launched/downstream sim can partially cross the container wall. 
<img width="326" alt="Screenshot 2024-07-19 at 1 39 05 PM" src="https://github.com/user-attachments/assets/257bf59f-8b99-48c8-baed-2c084ca704fd">

This issue isn't present in 1.2.0-dev.1. I'm guessing it may have been related to this issue?

**Comment by pixelzoom** [comment]
> This issue isn't present in 1.2.0-dev.1 or in main. I'm guessing it may have been related to this issue?

Yes, that's right. Both mass and radius were not being deserialized, and that was fixed in https://github.com/phetsims/gas-properties/commit/081fbea01ad209885339f00de5cf069327b7c266.   So while it was a problem in 1.1.0-dev.rc.1, it is no longer a problem in main and (upcoming) 1.1.0-rc.2.

So we're still ready for 1.1.0-rc.2. for this issue.

**Comment by pixelzoom** [comment]
Please verify for particle locations and container width in https://github.com/phetsims/qa/issues/1123 and https://github.com/phetsims/qa/issues/1124.

Please verify for particle locations in https://github.com/phetsims/qa/issues/1125. (Container width is fixed in Diffusion.)

If this issue looks OK, please close.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2 for all sims.
Closing.
