### ISSUE TITLE
Currently unable to hide a particle type in the Average Speed Panel

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#277]
While testing https://github.com/phetsims/qa/issues/1100, on the Energy Screen I noticed that it is currently not possible to hide one of the particle types in the Average Speed panel. 

If I set `averageSpeedAccordionBox.heavyNumberDisplay.visibleProperty` or `averageSpeedAccordionBox.lightNumberDisplay.visibleProperty` to false, a value will no longer show, but the particle icon is still  present. Wondering if there is an easy way to solve this? 

<img width="157" alt="Screenshot 2024-06-25 at 12 27 56 PM" src="https://github.com/phetsims/gas-properties/assets/87318828/4458d176-cd53-429f-b270-4442ae61830f">

I thought that perhaps an instructor may want to only focus on the relationship between temperature, KE and speed. Currently, it is possible to show only 1 particle type everywhere else on this screen (remove radio buttons under pump, remove particle type in Particles panel, remove checkbox groups for the graphs).

**Comment by pixelzoom** [comment]
`averageSpeedAccordionBox.heavyNumberDisplay.visibleProperty` and `averageSpeedAccordionBox.lightNumberDisplay.visibleProperty` are now featured. Setting them to `false` also hides their associated particle icons.

@Nancy-Salpepi please review, close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks great.  I can now completely hide one particle type on the Energy Screen!
Closing.
