### ISSUE TITLE
Title on y-axis isn't centered in locales other than English

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#279]
**Test device**
MacBook Air M1 chip and Chromebook

**Operating System**
macOS14.5

**Browser**
Safari  + Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1100, on the Energy Screen: 
In locales other than English the "Number of Particles" title on the y-axis for both graphs isn't centered. The title on the x-axis is always centered no matter which locale is selected.

**Visuals**
<img width="230" alt="Screenshot 2024-06-25 at 5 47 34 PM" src="https://github.com/phetsims/gas-properties/assets/87318828/9f255553-833b-43d4-ab97-9255f84b1168">

It is very easy to see using ?stringTest=dynamic:
<img width="230" alt="Screenshot 2024-06-25 at 6 14 52 PM" src="https://github.com/phetsims/gas-properties/assets/87318828/05b07ba0-5b87-4b0d-be63-323db604f433">

**Comment by pixelzoom** [comment]
@Nancy-Salpepi please review, close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks good now. Closing.
