### ISSUE TITLE
credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#28]
Finalize the credits in gas-properties-main.js.

**Comment by pixelzoom** [comment]
I'm a little confused about how to handle the legacy credits.  For now, Gas Properties credits are what in the HTML5 design doc + what’s on the legacy webpage.

**Comment by pixelzoom** [comment]
@arouinfar here are the current credits.  Any changes other than the addition of QA credits?

<img width="821" alt="screenshot_1219" src="https://user-images.githubusercontent.com/3046552/58522152-41b7c080-817c-11e9-8fb9-d60ebf102e08.png">

**Comment by arouinfar** [comment]
@pixelzoom please add @KatieWoe `Kathryn Woessner` to the design team credits.

**Comment by pixelzoom** [comment]
Credits were factored out into `GasPropertiesConstants.CREDIT` so that they can be shared with diffusion-main.js.

**Comment by pixelzoom** [comment]
@arouinfar said:
> @pixelzoom please add @KatieWoe Kathryn Woessner to the design team credits.

PhET typically has a person appearing in one place in the credits.  I added Katie to the QA credits, but can move her to the Team credits.  @KatieWoe what would you prefer?

**Comment by KatieWoe** [comment]
Lets stick with QA.  I did more work there than in design

**Comment by pixelzoom** [comment]
@KatieWoe when 1.0.0-rc.1 RC testing is completed, please let me know who should be added to the QA credits.

**Comment by pixelzoom** [comment]
Testing of 1.0.0-rc.1 is done, and it's time to move on to 1.0.0-rc.2. Judging from the 1.0.0-rc.1 test matrix, I’m guessing that QA credits should be “Jaspe Arias, Liam Mulhall, Jacob Romero, Kathryn Woessner".   I'm going to go with that for 1.0.0-rc.2.  If it's not correct, it will be a simple cherry-pick.

**Comment by KatieWoe** [comment]
Looks good
