### ISSUE TITLE
Stepping forward in upstream sim while paused doesn't change state of downstream sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#280]
**Test device**
MacBook Air M1 chip and iPad 

**Operating System**
14.5 and 17.5.1

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1100, while trying to replicate https://github.com/phetsims/gas-properties/issues/282  I came across another issue that occurs while paused. 
In the state wrapper, on any screen, if you use the step forward button in the upstream sim the particles do not update in the downstream sim. 

**Steps to reproduce**
1. In the state wrapper, on any screen press Pause in the upstream sim
2. Add some particles
3. Continuously press the Step Forward button--the particles do not update in the downstream sim. 

**Visuals**
<img width="446" alt="Screenshot 2024-06-25 at 8 45 48 PM" src="https://github.com/phetsims/gas-properties/assets/87318828/e18f283f-ec35-4c76-95ef-da0e64771b29">
<img width="446" alt="Screenshot 2024-06-25 at 8 51 56 PM" src="https://github.com/phetsims/gas-properties/assets/87318828/fa82d151-5384-4ba2-815f-aa76db7501d2">

**Comment by pixelzoom** [comment]
Note that #269, #276, and #280 are all bad State Wrapper behavior when the sim is paused.

**Comment by pixelzoom** [comment]
This was fixed by https://github.com/phetsims/gas-properties/commit/98b2d2d886e7f407188e5f70af451543a3ed1cec over in https://github.com/phetsims/gas-properties/issues/276. (I love it when that happens.)

@Nancy-Salpepi please verify, close if OK.
