### ISSUE TITLE
Some visibleProperty instances should be featured.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#286]
From https://github.com/phetsims/gas-properties/issues/285#issuecomment-2230721306,  these `visibleProperty` elements are mentioned in examples.md and should be featured:

```
gasProperties.diffusionScreen.view.panels.settingsPanel.numberOfParticlesControls.visibleProperty
gasProperties.diffusionScreen.view.panels.settingsPanel.massControls.visibleProperty
gasProperties.diffusionScreen.view.panels.settingsPanel.radiusControls.visibleProperty
gasProperties.diffusionScreen.view.panels.settingsPanel.initialTemperatureControls.visibleProperty
```

**Comment by pixelzoom** [comment]
Fix in main in the above commits.  This now needs to be patched into the following repos and branches:

gas-properties:
- [ ] phet-io-sim-specific gas-properties-1.1
- [ ] gas-properties 1.1

gases-intro:
- [ ] gas-properties gases-intro-1.1
- [ ] phet-io-sim-specific gases-intro-1.1
- [ ] gases-intro 1.1

diffusion:
- [ ] gas-properties diffusion-1.1
- [ ] phet-io-sim-specific diffusion-1.1
- [ ] diffusion 1.1

**Comment by pixelzoom** [comment]
Patching of release branches is paused while MR work is being done for https://github.com/phetsims/joist/issues/976.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi please verify in main.  Then leave assigned to me for patching release branches.

**Comment by Nancy-Salpepi** [comment]
Looks good on my end. Back to you.

**Comment by pixelzoom** [comment]
Patching is completed for all 3 sims.

Ready for verification in 1.1.0-rc.2.  Please inspect these Properties using Studio in Gas Properties and Diffusion sims.

**Comment by pixelzoom** [comment]
Please verify for https://github.com/phetsims/qa/issues/1123 and https://github.com/phetsims/qa/issues/1125.  (This issue is irrelevant for the Gases Intro sim.)

If everything looks OK, please close this issue.

**Comment by KatieWoe** [comment]
Looks good in rc.2
