### ISSUE TITLE
Average Temperature changes when the Number of Particles is decreased

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#287]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1107, on the Diffusion screen, if I add particles and then remove some, the Tavg changes. This also happens in published. 

**Steps to reproduce**
1. Go to the Diffusion Screen
2. Open the Data panel
3. Add 50 blue particles
4. Decrease the number of particles to 40

**Visuals**

https://github.com/user-attachments/assets/13215ac7-7b5a-4b4b-86cb-c50bab5152de

**Comment by pixelzoom** [comment]
Reproduced in main.

**Comment by pixelzoom** [comment]
Fixed in https://github.com/phetsims/gas-properties/commit/a3b0abe7bf067a4ffb8a5a61d21139b481ed62b1, the other commits are to patch release branches.

@Nancy-Salpepi please review in main. Leave open for verification in 1.1.0-rc.2.

**Comment by Nancy-Salpepi** [comment]
Looks great in main!

**Comment by pixelzoom** [comment]
Please verify for https://github.com/phetsims/qa/issues/1123 and https://github.com/phetsims/qa/issues/1125.  (This issue is irrelevant for the Gases Intro sim.)

If everything looks OK, please close this issue.

**Comment by KatieWoe** [comment]
Looks fixed in rc.2
