### ISSUE TITLE
Initial position of blown lid isn't stateful

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#288]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1107 with Studio/State wrappers on the Ideal screen:
if the sim is launched while paused with the blown lid just above the container (which was discussed/implemented in https://github.com/phetsims/gas-properties/issues/269#issuecomment-2218145115), it will appear as though the lid is on the container in the downstream/launched sim. 

**Steps to reproduce**
1. In the State wrapper, set state rate = 0
2. Add 1000 heavy particles
3. Press Pause
4. Decrease the container size until the Return Lid button appears--the lid will be above the container
5. Press Set State Now --the downstream sim shows the lid on the container

**Visuals**
<img width="500" alt="Screenshot 2024-07-17 at 8 01 20 AM" src="https://github.com/user-attachments/assets/afbe4df9-5b46-4218-92bf-ef20518a9682">

**Comment by pixelzoom** [comment]
Reproduced in main -- good catch!

Fixed in https://github.com/phetsims/gas-properties/commit/7cf989cc7dc99cfce05d989f5ec7741fabdf9e40, and the other commits are patches to the release branches. 

@Nancy-Salpepi please review in main. Leave open for verification in 1.1.0-rc.2

**Comment by Nancy-Salpepi** [comment]
Looks great on main!

**Comment by pixelzoom** [comment]
Please verify for https://github.com/phetsims/qa/issues/1123 and https://github.com/phetsims/qa/issues/1124.  (This issue is irrelevant for the Diffusion sim.)

If everything looks OK, please close this issue.

**Comment by KatieWoe** [comment]
Looks good in rc2
