### ISSUE TITLE
Remove "Adjust in smaller steps" from Diffusion

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#290]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1123 and https://github.com/phetsims/qa/issues/1125, since the step size is specific for the particle properties (ex. # particles, radius, mass, and temperature) there are no smaller step sizes for this screen/sim. 

Perhaps we should remove the "Adjust in smaller steps" from the keyboard dialog.

**Visuals**
<img width="664" alt="Screenshot 2024-07-30 at 11 36 56 AM" src="https://github.com/user-attachments/assets/2e84d7a0-4bb9-46cc-8bc1-34ab5fe04a22">

**Comment by pixelzoom** [comment]
@arouinfar and I discussed. I fixed in the above commit, will cherry-pick next. We don't feel this is worthy of QA's time, and the QA Pipeline overfloweth. If no other problems are found, I'll publish 1.1.0-rc.3 and have @arouinfar verify, then publish production.

**Comment by pixelzoom** [comment]
@arouinfar please verify in:
* https://phet-dev.colorado.edu/html/gas-properties/1.1.0-rc.3/phet/gas-properties_all_phet.html
* https://phet-dev.colorado.edu/html/diffusion/1.1.0-rc.3/phet/diffusion_all_phet.html

Close if OK.

**Comment by arouinfar** [comment]
Looks good in rc.3 for both sims, thanks @pixelzoom. Closing.

<img width="433" alt="image" src="https://github.com/user-attachments/assets/e4f824af-c8e8-48fb-95b1-f1f83605bfe3">
