### ISSUE TITLE
PhET-iO design

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#30]
Should PhET-iO API design be part of the initial (1.0) design and implementation?
(ANSWER: No, but prudent to do some initial thinking about requirements and issues.)

@arouinfar and I have determined that this sim's model has the same problems that we encountered in instrumenting Hooke's Law (see https://github.com/phetsims/hookes-law/issues/52, https://github.com/phetsims/hookes-law/issues/57).  Should we be proactive about addressing this?

**Comment by pixelzoom** [comment]
The most promising approach for achieving acceptable performance involves few Properties in the model, and treating the entire system of particles as one model element. But Properties are fundamental to PhET-iO.  So I recommend that we have a design meeting ASAP to discuss potential PhET-iO design/goals for this sim (what will need to be instrumented, etc.) and make sure that we're all on the same page.  The meeting should include the sim design team, plus someone from the PhET-iO team.

**Comment by arouinfar** [comment]
@pixelzoom there were quite a few design meeting requests for this week, but I've created a reminder to request time for GasProps PhET-iO at next week's design meeting.

**Comment by pixelzoom** [comment]
3/14/19 design meeting:

* No needs to instrument individual particles.
* Want to be able to inspect things like #particle in histogram bins, #particles in left/right sided of container, etc.
* Need to to think about how to save/restore state. No need for particles to be in same positions with same velocities.  But if we don't save state of each particle, then need to evaluate the difficultly of inverting the model, to create a set of particles based on temperature, pressure,...  Could save just number of particles and velocity magnitudes, then choose random locations and velocity angles when restoring state.

**Comment by amanda-phet** [comment]
@pixelzoom can you edit the above to say @arouinfar not me?

**Comment by pixelzoom** [comment]
When the first (Ideal) screen is feature complete, I think it will be worth revisiting this.

**Comment by pixelzoom** [comment]
See also "PhET-iO instrumentation notes" in https://github.com/phetsims/gas-properties/issues/77.

**Comment by pixelzoom** [comment]
@arouinfar do you want to revisit this issue now that the sim is feature complete?

**Comment by arouinfar** [comment]
Seems like @kathy-phet's call.

**Comment by pixelzoom** [comment]
Re this issue that we identified on 3/14/19:
> Need to to think about how to save/restore state. No need for particles to be in same positions with same velocities. But if we don't save state of each particle, then need to evaluate the difficultly of inverting the model, to create a set of particles based on temperature, pressure,... It would be acceptable to save just number of particles (of each type) and velocity magnitudes, then choose random locations and velocity angles when restoring state.

There is no way that we can invert the model, and that is (in general) a bad design decision.   With the current implementation, we will need to save thousands of particles in order to save the state.  And similarly, we will need to save the location and velocities of thousands of particles on each time step in order to record/playback.   That will most certainly impact performance - there's no way we can do that and keep animation running smoothly.

**Comment by pixelzoom** [comment]
Added `meeting:design` label for discussion at 5/30/19 design meeting.

We are waiting on feedback from @kathy-phet. Specifically, should we do some more initial thinking about PhET-iO now that the sim is feature complete?

**Comment by pixelzoom** [comment]
5/30/19 design meeting @arouinfar @ariel-phet @kathy-phet 

We briefly discussed issues with getting state of the particle system, record/playback, etc.  This sim will be a challenge to instrument.  It won't be as simple as just adding tandems and describing the API in Studio.  It will require some additional PhET-iO specific code.   

Deferring this issue until we begin PhET-iO design.

**Comment by pixelzoom** [comment]
We are resuming PhET-iO design for this sim, while it's fresh in our minds.  In preparation for a Thursday 7/18 design meeting, I have added tandems and metadata to the Gas Properties code base, so that you can explore using Studio.  

Please play with version 1.0.0-dev.40 in Studio by visiting this link (password required):

https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.40/phet-io/

Notes:
* The sim is sparsely instrumented.  I started only with the things that seemed obvious.
* You will want to explore in "All" mode. Anything that is showing up as "featured" is because it is featured in common code. 
* There are many Properties that are necessarily "read only", because they are derived from the state of the particle system.  For example, you can read pressure, but you cannot set pressure. 
* Save/Load do not work; we don't currently have a way to save/load the state of the particle system.

**Comment by pixelzoom** [comment]
Here's a list of specific questions that I compiled while adding tandems.  

- [ ] How to save/load state? What state needs to be saved?

- [ ] Which model classes should `extend PhetioObject` and set `phetioState: false` in order to add `phetioDocumentation`?

- [ ] Does anything about the pump or its radio buttons need to be instrumented?

- [ ] How to prevent client from setting `container.widthProperty` for specific `holdConstantProperty` values.

- [ ] How to prevent client from setting `container.lidWidthProperty` while container is being resized?

- [ ] Do spinners in Diffusion screen need to be individually instrumented? What about their icons and labels?

- [ ] Do any of the UI elements in Particles accordion box need to be instrumented?

- [ ] Do any parts of `LidNode` need to be instrumented? For example, do we need to support hiding the handle?

- [ ] Do the thermometer or pressure gauge Nodes need to be instrumented? Which parts?

- [ ] Do the individual radio button in `HoldConstantControl` need to be instrumented? The client should not have control over disabling these, since that’s derived based on state of particle system.

- [ ] Should checkboxes for histograms be instrumented? There currently are.

- [ ] Are the Properties associated with histogram checkboxes difficult to find? They are current owned by `histogramNode`.

- [ ] Which drag listeners should be instrumented?  Container resize handle? Lid? Bicycle pump? HeaterCooler slider?

- [ ] What to do about `AnimatedHeaterCoolerNode`? I'll explain...

- [ ] What parts of `CollisionCounterNode` should be instrumented?

- [ ] What parts of `StopwatchNode` should be instrumented?

- [ ] Do we need to instrument any Properties in `GasPropertiesColorProfile`?

- [ ] Do we need to instrument any parts of the Options dialog or its elements?

- [ ] Do we need to instrument any of the Emitters that result in Oops dialogs?

- [ ] Why does `scenery-phet.TimeControl` support hiding or disabling individual buttons? 

- [ ] Is it OK to instrument the Normal and Slow radio buttons as a group? And/or do we need to instrument individual buttons?

- [ ] Should the Remove/Restore Divider toggle button be instrumented? 

- [ ] Should the eraser button be instrumented?

- [ ] In Diffusion screen, what elements of the Data accordion box should be instrumented?

- [ ] `heatCoolFactorProperty` is currently `phetioReadOnly: true` because it needs to snap back to zero.  And it shouldn’t be set for some Hold Constant modes.

- [ ] Properties controlled by spinners in Diffusion screen don’t have Studio controls because their values are multiples of some delta.

**Comment by pixelzoom** [comment]
7/18/19 design meeting notes, @arouinfar @ariel-phet @kathy-phet @pixelzoom 

**Setting an initial state for first 3 screens:**
- [ ] Query parameters to set up specific initial state by specifying V,T,N.  Need N for light and heavy (NL, NH), one of them needs to be non-zero for this feature.  Also need to specify which screen.  V and T use their usual defaults. P is computed. PhET-IO API function to do the same thing as above query parameters. (V doesn’t apply to Energy.)
- [ ] Load state will use the above API.  It will create a system to match a desired config. It will not restore individual particle state.

**API functions**
- [ ] get all speeds for a species of particle.
- [ ] get all KEs for a species of particle.

**phetioDocumentation**
- [ ] mass of particles with `numberOfHeavyParticleProperty` and `numberOfLightParticleProperty`
- [ ] describe particle1 and particle2 terminology at `diffusion.model`
- [ ] `holdContantProperty` has values of type `phet.gasProperties.HoldConstant`

**Ask PhET-iO Team**
* Are there hooks to make API calls on `step`?
* How to `setValue` for `EnumerationProperty`?
* General way to indicate or document the `Enumeration` for a `EnumerationProperty`?

**Comment by pixelzoom** [comment]
I added "phet-io" to supportedBrands for Diffusion and Gases Intro, so they are also officially instrumented and usable in Studio.

**Comment by pixelzoom** [comment]
@arouinfar @kathy-phet @ariel-phet I have followed up on the 4 "Ask PhET-iO Team" action items in https://github.com/phetsims/gas-properties/issues/30#issuecomment-512980763.   None of these features are currently supported, so I created a GitHub issue for each item.  If you have thoughts about the priority of those issues, please comment.

**Comment by arouinfar** [comment]
> None of these features are currently supported, so I created a GitHub issue for each item. 

Bummer! Thanks for investigating @pixelzoom. 

Priority is fully up to @kathy-phet and @ariel-phet, so unassigning myself.

**Comment by pixelzoom** [comment]
Gas Properties and its derivatives (Gases Intro, Diffusion) are now in RC testing.  Until 1.0.0 is published, we should refrain from making any additional PhET-iO changes to sim code, because it will complicate cherry-picking of RC fixes.

**Comment by pixelzoom** [comment]
Self unassigning until the PhET-iO design process is restarted.

**Comment by pixelzoom** [comment]
From 1/14/2021 PhET-iO meeting, milestones are:

4/1/21 Begin working on design
7/31/21 RC-lite testing completed

**Comment by pixelzoom** [comment]
In a 8/11/21 Slack message, @kathy-phet said that Gas Properties PhET-iO release (#191) is now a priority.  Self assigning to review what needs to be done, and who needs to do it.

**Comment by pixelzoom** [comment]
@kathy-phet @arouinfar According to the plan for Gas Properties 1.1 in https://github.com/phetsims/gas-properties/issues/191#issue-800528675, the first phase is do complete PhET-iO design.  So this is in your court.  If you'd like to move this forward, please self-assign this issue.

**Comment by pixelzoom** [comment]
Status for 1/4/2022 quarterly-planning meeting:

* Basic instrumentation has been done. 
* This issue has been assigned to AR & KP for design since 1/14/21. 
* There will almost certainly have challenges with dynamic elements.

**Comment by arouinfar** [comment]
This simulation is not a current PhET-iO design priority, so unassigning.

**Comment by pixelzoom** [comment]
Work has resume for https://github.com/phetsims/gas-properties/issues/191, which will include PhET-iO.

Things to do:
* Review previous comments and history in this issue.
* Create a PhET-iO Design document, if it doesn't already exist.
* Identify sim-specific PhET-iO features and requirements.

**Comment by pixelzoom** [comment]
4/11/24 design meeting with @arouinfar @kathy-phet @Nancy-Salpepi @ariel-phet @pixelzoom

* @arouinfar to create PhET-iO design document and triage the history in this issue.
* Add @Nancy-Salpepi to the PhET-iO design team
* @arouinfar @Nancy-Salpepi and @pixelzoom will discuss/filter the PhET-iO design and bring questions back to the team.

**Comment by pixelzoom** [comment]
Gas Properties: PhET-iO Design
https://docs.google.com/document/d/1VTPqRdh9OPsUDFhd8KfWRS_MGOYlDUeb0JqsHkL2r2Q/edit?pli=1#heading=h.qfx24bhz5uem

**Comment by pixelzoom** [comment]
With the exception of particles and histogram samples, I've completed a first pass at instumentation, including Studio tree structure, phetioFeatured, phetioReadOnly, and phetioDocumentation.  So I've labeled this as "ready for review".

@arouinfar @Nancy-Salpepi I'll leave it up to you whether you'd like to review now, or wait until particles and histogram samples have been instrumented.

**Comment by arouinfar** [comment]
@Nancy-Salpepi and I completed the first pass through the Studio tree, and identified the issues tagged above (beginning with #249). There are a few more things we would like to discuss first with @pixelzoom to decide on the best path forward, and haven't created GitHub issues for those, other than #255.

**Comment by pixelzoom** [comment]
> There are a few more things we would like to discuss first with @pixelzoom  ...

To be discussed tomorrow, 6/11/24.

**Comment by pixelzoom** [comment]
We discussed on 6/11/24 and created some other issues.

@arouinfar @Nancy-Salpepi Is this issue ready to close?

**Comment by pixelzoom** [comment]
@arouinfar says OK to close.
