### ISSUE TITLE
User suggestion: air pressure in container

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gas-properties#31]
> Firstly thanks for the amazing simulations you make. As a science teacher they are invaluable. The best ones are those that can visually represent an abstract concept. My absolute favourite is "gas properties" because I can "show" and my students can "see" so many different interactions. I can use it for the basics, but also diffusion, and even evaporation if I put the gravity on full and add a tonne of particles. Students really understand evaporation this way as they get an idea of how particles need a certain amount ot energy to escape the liquid.
> 
> Anyway, I'd like to recommend another simulation: Air pressure, and how it interacts with a container of a gas. I have not seen any simulations or videos on this topic and students find this quite confusing, mainly because they struggle to understand that air could exert pressure. If they could see the particles colliding with a container on screen it would make a huge difference. The best would be to have a container in the centre with the ability to withdraw or add particles to the container. The container could have something like expandable walls to show how differences in pressure inside and outside will affect the container.

Maybe this would need to be a separate sim, but seemed like it related to Gas Properties?

**Comment by pixelzoom** [comment]
@arouinfar Is this something that needs to be addressed for Gas Properties?  If not, recommended to move this to wherever ideas for new sims are being tracked.

**Comment by arouinfar** [comment]
@pixelzoom this is beyond the scope of Gas Properties. This would be more in line with the atmospheric spin-off that Kathy has in mind for the future. 

@oliver-phet can you move this to Unfuddle?

**Comment by oliver-phet** [comment]
Recorded on the [sim suggestion form](https://docs.google.com/forms/d/e/1FAIpQLSec0EXNHF7wMKBJN-hD2PyrUVSz2v5-hGLXVqCl2NyppmhOng/viewform). Closing.
