### ISSUE TITLE
[BicyclePumpNode] How to handle dynamic number of particles/pump?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#33]
The BicyclePumpNode in SOM will be converted to a common code component in https://github.com/phetsims/states-of-matter/issues/217.

However, the bicycle pump in GasProps behaves a little differently than SOM. In SOM, there is a set number of particles that get pumped in, regardless of how far/fast the handle moves. In Java GasProps, the number of particles appears to depend on both the distance the handle travels, and the speed at which it travels.

| | Slow | Fast |
|---|---|---|
|Long Handle| N=22 ![long_slow](https://user-images.githubusercontent.com/8419308/48440661-bda16c80-e746-11e8-8b82-0001f5fa9ce1.gif) | N=379 ![long_fast](https://user-images.githubusercontent.com/8419308/48440664-bf6b3000-e746-11e8-9c7b-2cd8cb596e54.gif) |
|Short Handle| N=3 ![short_slow](https://user-images.githubusercontent.com/8419308/48440669-c42fe400-e746-11e8-926a-e7187d098d84.gif) | N=191 ![short_fast](https://user-images.githubusercontent.com/8419308/48440675-c5f9a780-e746-11e8-8ca9-62758e04cfbd.gif)|

Ultimately, the common-code bicycle pump should have two options for the number of particles/pump.
1. Particles/pump is a constant 
2. Particles/pump depends on handle dynamics (speed/distance).

I am reasonably confident that we will want the number of particles pumped in tied to the dynamics of the handle. While the current Java behavior seems fine, I don't know if there are any odd things that would need to get worked out.

Tagging for discussion at the next design meeting.

**Comment by pixelzoom** [comment]
My first question: Is the behavior in SOM desired, or just an artifact of how it was implemented?

**Comment by pixelzoom** [comment]
@arouinfar said:
> Ultimately, the common-code bicycle pump should have two options for the number of particles/pump.
>
> 1. Particles/pump is a constant
> 2. Particles/pump depends on handle dynamics (speed/distance).

More general would be an option to provide a function that maps motion of the handle (distance and speed) to number of particles.   And the 2 mappings above (content, dynamics) would be pre-defined (reusable) values for that option.

**Comment by arouinfar** [comment]
@pixelzoom I don't think the SOM model can handle a sudden influx of a ton of particles, so a constant number of particles/pump would be desired. There aren't any learning goals that would require a more dynamic BicyclePumpNode in that particular sim.

**Comment by arouinfar** [comment]
To clarify, options (1) and (2) in https://github.com/phetsims/gas-properties/issues/33#issue-380409753 were meant to describe the desired outcome/UX. I wasn't trying to recommend any specific code architecture.

**Comment by pixelzoom** [comment]
12/20/18 design meeting:

* @ariel-phet pointed out that having the dynamics depend on how fast the pump moves is bad physics.  The same number of particles should be added regardless of how fast the pump is moved. 
* We want a linear relationship between the length of the pump and the number of particles.
* When you release the pump, it stays where you release it.
* For Gas Properties, max 50 particles per full range of pump.

**Comment by pixelzoom** [comment]
@chrisklus FYI, see above design decisions relevant to  phetsims/states-of-matter#217.

**Comment by arouinfar** [comment]
One correction to https://github.com/phetsims/gas-properties/issues/33#issue-380409753 -- in SOM, there isn't a fixed number of particles per pump. There is a max number of 3 particles/pump, depending on how far the handle is moved, so there isn't a need for the two options in my original post.

The number of particles added to a the container will linearly map to the distance the handle of the BicyclePumpMoves. From sim to sim, the max particles/pump will vary, but the mechanics should be the same.

**Comment by chrisklus** [comment]
@SaurabhTotey and I were looking into the pump behavior today, and we noticed that the number of particles added per pump *is* based on the speed of the pump currently in SOM. Distance is relevant as well. With a full-length pumping action at a slow speed, the pump releases 4 particles. With a full-length pumping action at maximum speed, the pump releases 1 particle.

>The number of particles added to a the container will linearly map to the distance the handle of the BicyclePumpNode. From sim to sim, the max particles/pump will vary, but the mechanics should be the same.

Should this be the standard (and only) behavior for this pump, meaning that SOM will deviate from what is currently published?

**Comment by pixelzoom** [comment]
> ... the number of particles added per pump is based on the speed of the pump ...

This is buggy behavior, not physically correct.  Speed should not be a factor, only distance traveled.
My understanding is that the speed behavior should _not_ be implemented as part of BicyclePumpNode.  And it should probably be corrected in SOM.  @arouinfar @ariel-phet is that correct?

**Comment by arouinfar** [comment]
> This is buggy behavior, not physically correct. Speed should not be a factor, only distance traveled.

Agreed @pixelzoom.

> My understanding is that the speed behavior should not be implemented as part of BicyclePumpNode. And it should probably be corrected in SOM. 

That's correct. Handle speed should never determine the number of particles pumped in.

Some additional notes from the Gas Properties meeting notes that lead this https://github.com/phetsims/gas-properties/issues/33#issuecomment-449151395:

>How should we handle a dynamic pump rate? In Java particles/pump depends on handle distance and speed.
>* AP pointed out that having the dynamics depend on how fast the pump moves is bad physics. The same number of particles should be added regardless of how fast the pump is moved.
>* We want a linear relationship between the length of the pump and the number of particles.
>* When you release the pump, it stays where you release it.
>* For Gas Properties, max 50 particles per full range of pump.

**Comment by pixelzoom** [comment]
@arouinfar Could you also comment on whether behavior should be changed in SOM?  And if so, an  issue should be created.

**Comment by arouinfar** [comment]
The behavior in SOM is incorrect, but it can wait to get corrected until @chrisklus works on https://github.com/phetsims/states-of-matter/issues/217.

**Comment by pixelzoom** [comment]
SOM bug has been reported in https://github.com/phetsims/states-of-matter/issues/242.

The HMTL5 implementation guarantees that particles behave the same when added via the pump vs spinners.  How groups of particles look when they are added (wave vs somewhat chaotic) is being tracked in https://github.com/phetsims/gas-properties/issues/42.

So closing this issue.
