### ISSUE TITLE
behavior at absolute zero

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#36]
In https://github.com/phetsims/gas-properties/issues/10#issuecomment-450756942, @arouinfar said:

@pixelzoom a lot of these seem irrelevant to Gas Properties HTML5, especially since you are not directly porting the Java model. There may be a few items that may require some design discussion. Can you review and see which of these items merits further discussion? The only thing that sticks out to me is the behavior around 0 K. 

> - [ ] When the temperature is at 0K, the molecules continue to twitch. Even if the ice is left on for a long time.
> 
> - [ ] If you keep cooling the take after it has reached 0K, then when you try to warm it up, it takes as long to warm it up to 1 K as you spent cooling it after it reached 0K.

I do not think we need to allow the system to be cooled to 0 K. The behavior of matter at 0 K is strange, and there will be a lot of weird edge cases we'll need to work out (which is what happened for States of Matter). The learning goals of this sim do not require 0 K, so I would be fine with limiting the HeaterCoolerNode so that the system cannot be cooled beyond a certain limit, say 5 K.

**Comment by pixelzoom** [comment]
@arouinfar That sounds OK.  Does it need to be discussed with the design team?  Can you please add to the design doc?

**Comment by arouinfar** [comment]
@pixelzoom I believe there was some off-hand discussion about this during brainstorming, but it would be good to confirm with @kathy-phet in design meeting.

Slack discussion with @ariel-phet:
> Amy Rouinfar [11:14 AM]
I vaguely remember some off-hand discussion in GasProps brainstorming about 0 K. I don’t think there’s any reason to allow the system to get cooled to 0 K, so perhaps we should limit the HeaterCoolerNode to something like 5 K?
>
>Ariel Paul [11:29 AM]
What does Java do?
>
>Amy Rouinfar [11:29 AM]
It allows 0 K, but it’s buggy
And 0 K was really tricky for SOM
I don’t think 0 K is integral to the learning goals for gas props
>
>Ariel Paul [11:30 AM]
I am fine with not allowing 0 K (since it really is not part of any of the learning goals)

**Comment by pixelzoom** [comment]
Assigning to @arouinfar so that this gets on the design meeting schedule.

**Comment by arouinfar** [comment]
Reminder has been set to request GasProps time at next week's design meeting. I've also added this issue to the meeting agenda in the design doc. Since there's nothing else to be done for now, I'm unassigning myself.

**Comment by pixelzoom** [comment]
3/14/19 design meeting:

We'd like to trying letting it go to absolute zero and see what cases come up.   Then we'll evaluate and revisit.

**Comment by pixelzoom** [comment]
Enough of the sim is implemented that this can now be investigated.  

I can make the thermometer read 0K via the following steps:
1. Go to Intro screen
2. Pump some particles into the container.
3. Hold the heater/cooler slider in the "full cooling" position until the thermometer reads 0K.

Particles are still moving, so we're probably at some small value that's < 0.5K and is rounded to 0K. 

@arouinfar how do you want to proceed?

**Comment by arouinfar** [comment]
It takes quite a bit of time (~1 minute) to cool the particles from the initial 0 K reading until the the average speed finally reaches 0 m/s. This is very similar to the Java behavior. 

The behavior at absolute zero is not a primary learning goal, and I would be totally fine with limiting the min temperature to 1 K. However, I do recall that @kathy-phet may have had a differing opinion here, so it would be good for her to review.

My bigger concern is the pressure gauge fluctuations we introduced in #50. When the temperature is very low, the pressure gauge fluctuations start to look a bit jarring. My original testing focused on low pressures associated with low N, not low T, so it looks a bit odd to me. I wonder if others feel the same.

**Comment by pixelzoom** [comment]
@arouinfar said:
> ...  I do recall that @kathy-phet may have had a differing opinion here, so it would be good for her to review.

@kathy-phet your thoughts?

**Comment by kathy-phet** [comment]
I took a quick look. I think the behavior going to 0K seems fine, and my preference would be to leave it in as opposed to constrain it to 1K. I think it makes for a nice conversation opportunity the way it is now.

Regarding the fluctuation on the pressure needle - I agree it should be a bit more sophisticated than just a jumpiness at a certain pressure if that is what is in there now (I cannot recall, sorry). If there is a lot of particles at low T it should also have very little jumpiness because it would be pretty steady pressure with big N (even if it is smaller P). So it should be related to the number of particles more than the pressure? I forget what the relationship you built in was, Chris?

**Comment by pixelzoom** [comment]
@kathy-phet said:
>  Regarding the fluctuation on the pressure needle ... If there is a lot of particles at low T it should also have very little jumpiness because it would be pretty steady 

We addressed this in https://github.com/phetsims/gas-properties/issues/67, which was reviewed and closed by @arouinfar.

**Comment by pixelzoom** [comment]
It sounds like there's nothing left to do here, but I'll leave this issue open so we can review at next design meeting.

**Comment by pixelzoom** [comment]
5/1619 design meeting @arouinfar @kathy-phet 

Jitter is currently a function of pressure and temperature.  As pressure increases, jitter decreases. Between 5-50K, a jitter multiplier ranges linearly from 0-1, so that jitter is totally removed when temperature is <= 5K.  `?maxJitter` controls the maximum jitter, default 200 kPa.  

@kathy-phet's homework is to review the current behavior and suggest changes.

**Comment by pixelzoom** [comment]
@kathy-phet reminder that this issue is assigned to you with high priority.

**Comment by pixelzoom** [comment]
Thinking about absolute zero some more...  With the current model, temperature `T` should approach, but never reach, `0K`.   That said, it is possible (though highly unlikely, given the time it would take) that we may exceed the floating-point precision of Javascript.   (The smallest number in Javascript is `Number.MIN_VALUE` whose value is `5e-324`.) And that may cause the sim to fail hard.   

Options are:
(1) Assume this will never happen, and it's OK for the sim to fail if it does.
(2) Detect this condition and set T to zero.
(3) Detect this condition and set T to `Number.MIN_VALUE` (non-zero).

@arouinfar thoughts?

**Comment by pixelzoom** [comment]
`Number.MIN_VALUE - Number.MIN_VALUE` evaluates to `0`, so I think we may be OK here with the "do nothing" option.

**Comment by arouinfar** [comment]
@pixelzoom let's go with the "do nothing" option, but I think it would be good for QA to spend a bit of time trying to break things at 0 K.

**Comment by pixelzoom** [comment]
> ... I think it would be good for QA to spend a bit of time trying to break things at 0 K.

It will be more than "a bit" of time :)   Starting with T=300K and applying maximum cooling, I estimate that you'll need to cool the container continuously for ~60 minutes before it gets anywhere near 5e-324.

**Comment by pixelzoom** [comment]
Moved remaining jitter issues to #92.
