### ISSUE TITLE
investigate Java model

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#37]
The TODO list in https://github.com/phetsims/gas-properties/issues/10 contained a few items that I'll need to look out for in the Java model:

- [x]  Look in to moving wall collisions
- [x] make more versatile & robust collision detection system that works heirarchically with object types
(The HTML5 implementation will not be "more versatile", it will address only the needs of Gas Properties. It will of course be robust. See https://github.com/phetsims/gas-properties/issues/37#issuecomment-467541520.)
- [x] clean up constraints. In particular, there is a lot of duplication in HollowSphereMustContain and
HollowSphereMustNotContain
(Constrains are irrelevant to Gas Properties, used in other related sims.)
- [x] hierarchy of Body/.../IdealGasParticle is way too big. Clean it up!
(Collapsed hierarchy to `Particle`, see https://github.com/phetsims/gas-properties/issues/37#issuecomment-456965705.)
- [x] set default energy so kinetic energy is never < 0
(HTML5 implementation sets initial velocity magnitude to correspond to 300K, so KE is always > 0. See also https://github.com/phetsims/gas-properties/issues/37#issuecomment-450943946.)

**Comment by pixelzoom** [comment]
Re " set default energy so kinetic energy is never < 0", here's a Slack discussion that @arouinfar had:

Amy Rouinfar [11:20 AM]
I don’t how it could ever be < 0

Chris Malley [11:21 AM]
My thought too.  Probably just a bug in the Java model that we need to watch out for?

Amy Rouinfar [11:21 AM]
The only thing that can be negative is velocity, which gets squared for KE
Oh, maybe it’s using 3/2 kT for energy, and T can be negative… but you should be using Kelvin for T
Either way, seems like a weird java bug

**Comment by pixelzoom** [comment]
Re: 

> - [ ] hierarchy of Body/.../IdealGasParticle is way too big. Clean it up!

The class hierarchy is indeed ridiculously deep:

```
ModelElement
  SimpleObservable
    Body
      Particle
        CollidableBody
          SphericalBody
            SolidSphere
              GasMolecule
                HeavySpecies
                LightSpecies
```

And everything above (and including) Body is in package `edu.colorado.phet.common.mechanics`, which is common code used by multiple sims.

So it's very difficult to determine what is and isn’t used in Gas Properties.  But it looks to me like there is a bunch of code related to properties of rotating particles (orientation, angular velocity, angular acceleration,...) that is not used by Gas Properties.  I asked @arouinfar about this on Slack, and she said:

> No, we don’t need to think about the particles rotating.

**Comment by pixelzoom** [comment]
This comment will include a list of important classes in the Java implementation.

`GasPropertiesApplication` - the sim's main

`IdealGasModule` - the sim's sole module

`IdealGasModel` - the sim's model container, start with `stepInTime`

`CollisionGod` - the top-level model element that handles collision detection and response

`CollisionExpert` - the interface implemented by classes that detect collisions.  _NOTE: Use the one in ideal-gas, not the one in collision!_

`SphereSphereExpert`, `SphereBoxExpert` - the 2 CollisionExperts that handle sphere-to-sphere and sphere-to-box collisions respectively.  _NOTE: Use the ones in ideal-gas, not the ones in collision!

`HeavySpecies, `LightSpecies` - heavy and light particles, see the class hierarchy identified in https://github.com/phetsims/gas-properties/issues/37#issuecomment-456965705

`PressureSensingBox` - the container (aka box)

**Comment by pixelzoom** [comment]
Re:

> - [ ] make more versatile & robust collision detection system that works heirarchically with object types

Part of the problem with the Java model is that it's used by quite a few sims, it's trying to be too general and too versatile (handling anything that that is a "Body"), and it's therefore overly complicated and buggy (not robust). 

My plan for the HTML5 implementation is not to be "versatile", but to handle the requirements of Gas Properties in a clear and robust manner.  That means that collision detection will handle only the objects needed for Gas Properties - particles and a container.

**Comment by pixelzoom** [comment]
Some notes about the Java pressure model...

Relevant code, with my annotations preceded by "//CM":

```java
//———————————————————————————————————
// IdealGasModule

private void createGauges( IdealGasClock clock ) {
    // Add the pressure gauge
    PressureSlice gaugeSlice = new PressureSlice( box, idealGasModel, clock );
    gaugeSlice.setTimeAveragingWindow( 2500 * ( clock.getDt() / clock.getDelay() ) );
    gaugeSlice.setUpdateContinuously( true );
    gaugeSlice.setY( box.getMinY() + 50 );  //CM where the gauge is attached to the box
    box.setGaugeSlice( gaugeSlice );
…
}

public void setGravity( double value ) {
    gravity.setAmt( value );
    if ( value != 0 ) {
        pump.setPumpingEnergyStrategy( new Pump.FixedEnergyStrategy() );
        box.setMultipleSlicesEnabled( false );
    }
    else {
        pump.setPumpingEnergyStrategy( new Pump.ConstantEnergyStrategy( getIdealGasModel() ) );
        box.setMultipleSlicesEnabled( true );
    }
}

//———————————————————————————————————
// PressureSensingBox

public double getPressure() {
    if ( multipleSlicesEnabled ) {
        double sum = 0;
        for ( int i = 0; i < averagingSlices.size(); i++ ) {
            PressureSlice slice = (PressureSlice) averagingSlices.get( i );
            sum += slice.getPressure();
        }
        return sum / averagingSlices.size();  //CM there are 5 slices
    }
    else {
        return gaugeSlice.getPressure();
    }
}

//———————————————————————————————————
// PressureSlice

//Converts raw data to ATM
private double scaleFactor = .025;  //CM arbitrary, to make values look reasonable

public double getPressure() {
    double pressure = pressureRecorder.getDataTotal() / pressureRecorder.getTimeWindow();
    double sliceLength = box.getMaxX() - box.getMinX();
    return scaleFactor * pressure / sliceLength;
}
```

A "slice" is a horizontal line that spans the width of the box.  Particles that pass cross this line during a tilmestep contribute to a "momentum sum" for that slice.  Pressure for the slice is the average momentum. Collisions between particle and container and not considered in the computation of pressure. 

Pressure is scaled by an arbitrary constant (0.0.25), documented as "Converts raw data to ATM". This value was presumably tuned to give the desired behavior.

The pressure displayed by the gauge is an average across slices.   

When gravity is off (which is always the case in HTML5), there is only once slice. Its y location matches the y location of where the pressure gauge is attached to the container.   Only the particles that cross this line during a step contribute to  the pressure.   You can confirm this by adding particles to the container; as soon as a particle crosses the horizontal line where the gauge is connected, there will be a pressure reading on the gauge.  No collisions with the container are involved.

Conclusions:

(1) The Java pressure model has nothing to do with collisions between particles

(2) The Java pressure model has nothing to do with `P = NkT/V`.  It's not at all physical, and relies on a scale factor to make the values look reasonable.

I don't recommend using this model in the HTML5 version, and suggest that we investigate a new model that is physically accurate and uses `P = NkT/V`.

**Comment by arouinfar** [comment]
>I don't recommend using the Java model in the HTML5 version, and suggest that we investigate a new model that is physically accurate and uses `P = NkT/V`, or some other physically accurate relationship.

I completely agree @pixelzoom. It's important that the pressure model is physical, though there's still some decisions to be made about what exactly that entails. @pixelzoom and I discussed these possibilities for taking wall collisions into account:

(1) Each particle has a flag for wall collisions. Once a particle has collided with the wall, it is counted in the pressure calculation.

(2) Similar to (1), but the wall collision flag would be time-dependent. If a particle hasn't collided with the wall for some amount of time, it would be removed from the pressure calculation.

This is definitely something that should be discussed as a team before @pixelzoom spends time working on this, so I'll tag for design meeting.

**Comment by pixelzoom** [comment]
The Java model was not useful for considering work done by the left (movable) wall on particles in the Energy screen.  I followed the approach recommended in [this thread from Physics Stack Exchange](https://physics.stackexchange.com/questions/19589/simple-question-about-a-gas-in-a-box-with-a-moving-wall), specially the post that contains "Consider it in the wall's frame of reference."

**Comment by pixelzoom** [comment]
HTML5 model is complete, nothing left to be gleaned from the Java model.  In summary, the only thing that was reused from Java was the basic collision model.

Closing.
