### ISSUE TITLE
how to draw a large number of animating particles

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#38]
This issue is for tracking various approaches to drawing a large number of animating particles.

I was planning on using CanvasNode to draw the entire system of particles.  And that is demonstrated in [1.0.0-dev.3](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.3/phet/gas-properties_en_phet.html).

But Wave Interference has similar requirements for sound particles, ran into performance problems using CanvasNode on iPad Air2 + iOS 12, and had to switch to `renderer: 'webgl'`. See https://github.com/phetsims/wave-interference/issues/322, `WavesScreenView`, `SoundParticleImageLayer` (for mobile Safari), and `SoundParticleCanvasLayer` (for all other platforms).

**Comment by pixelzoom** [comment]
CanvasNode is working great.  It would be relatively easy to implement the same approach as Wave Interference.  And with any luck, iPad Air2 may no longer be supported, or iOS13 may resolve performance issues (or create new ones) by the time this sim approaches completion.  So I'm going to stick with CanvasNode for now and defer this issue.

**Comment by pixelzoom** [comment]
`CanvasRenderingContext2D.drawImage` is working nicely. I haven't tested on iPad Air2 yet, but performance is great on MacBook Pro and iPad6, very smooth animation.   

I also experimented with flat circles using `CanvasRenderingContext2D.arc`, but references like [this one on Stackoverflow](https://stackoverflow.com/questions/12254415/canvas-arc-vs-drawimage) indicate that `drawImage` is much faster than `arc` on all platforms.

**Comment by pixelzoom** [comment]
When the first (Ideal) screen is feature complete, I'd like to have QA evaluate performance, especially on iPad Air2 + iOS 12.

**Comment by pixelzoom** [comment]
Discussed the issue of CanvasNode size with @jonathanolson via Zoom today.  It pays to make the CanvasNode only as big as necessary, as it will affect both performance and memory footprint.  So...

- [ ] In _Diffusion_ screen, size CanvasNode to fit the container bounds.

- [ ] In other screens, size CanvasNode to fit the portion of the window bounds that is above the bottom of the container.

**Comment by pixelzoom** [comment]
Particles animation is running very nicely on iPad6 + iOS 12.2 + Safari.  It's so-so on iPad2 + iOS 9.3 + Safari; when particles are added/removed, there's a bit of a hiccup, but then it runs smoothly. 

@KatieWoe could you please spot check performance of the particles on any platforms that you think might be problematic?  I'm especially interested in iPad Air + iOS 12, the platform that was a problem for Wave Interference.  You can use [1.0.0-dev.20](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.20/phet/gas-properties_en_phet.html).  No need to test anything other than adding/removing particles, and the performance/smoothness of the particle animation.

**Comment by KatieWoe** [comment]
Tested the requested iOS device as well as IE and Edge.  Edge seemed the fastest of the three, but all were perfectly acceptable.

**Comment by pixelzoom** [comment]
Excellent news, thanks @KatieWoe.

Next step is for design team to sign off on performance.  I'll defer that until we're feature complete.

**Comment by pixelzoom** [comment]
I thought of another optimization involving CanvasNode:

- [ ] Split GasPropertiesParticlesNode into 2 instances of CanvasNode, 1 for inside container, 1 for outside container.

**Comment by pixelzoom** [comment]
Closing.  We'll get performance sign-off in #1.
