### ISSUE TITLE
leverage SwingJS port?

### ISSUE THREAD

**Issue by samreid** [phetsims/gas-properties#4]
Bob Hansen ported this simulation to JS using an automatic code conversion strategy known as SwingJS.  Should we attempt to leverage any of this code for our HTML5 port?  For instance, model code?

https://chemapps.stolaf.edu/swingjs/phet/site/swingjs/examples/phet/GasProperties.htm?j2sLang=en

![image](https://cloud.githubusercontent.com/assets/679486/22123376/a20da046-de48-11e6-86b1-617c60e2d942.png)

**Comment by pixelzoom** [comment]
This was a very early Java sim, based on phetgraphics and other "vintage" approaches.  Any leverage provided by the Hansen port is going to be a port of sub-standard code, and maintenance costs for the end result would probably gobble up any up-front savings.  So if I were porting this sim, it would be a rewrite.

**Comment by pixelzoom** [comment]
1/11/18 design meeting:   Because the Java implementation is so "vintage", we will not leverage the SwingJS port.  Closing.
