### ISSUE TITLE
initial velocity for groups of particles

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#42]
This issue was factored out of https://github.com/phetsims/gas-properties/issues/19.

The current HTML5 implementation adds each particle with an initial velocity magnitude that corresponds to the temperature in the container (or 300K if the container is empty), regardless of whether the particle is released via the pump or spinners.  The relevant equations from [model.md](https://github.com/phetsims/gas-properties/blob/master/doc/model.md) are:

* KE = (3/2)kT = (1/2) * m * |v|<sup>2</sup>
* |v| = sqrt( 3kT / m )

Particles added via the pump or coarse spinners are currently all given identical velocities, so their movement is wave-like:

<img width="494" alt="screenshot_1113" src="https://user-images.githubusercontent.com/3046552/54797376-8291d700-4c19-11e9-9ef4-8eb7fe0d9ced.png">

If this wave-like look is not desirable, the alternative is to add slight randomization of the velocities such that the average velocity corresponds to the desired temperature.  

We will evaluate this when the first (Ideal) screen is feature complete.

**Comment by pixelzoom** [comment]
The first screen is not feature complete.  But it's far enough along that we should be able to make a decision about how groups of particles look when added to the container.  See master or [1.0.0-dev.8](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.8/phet/gas-properties_en_phet.html).

**Comment by pixelzoom** [comment]
Notes from 4/9/19 discussion with @arouinfar:

The desired behavior is:
* When particle-particle collisions are on, randomize the velocity magnitude, such that the average for the group is `|v| = sqrt( 3kT / m )`.  (I might also causing particle-particle collisions when Particle `previousLocation === null`.)  
 * When particle-particle collisions are off, wave-like behavior.

**Comment by pixelzoom** [comment]
I ran into problems with using a Gaussian distribution for speed values.  Temperature in the container is  is `T = (2/3)KE/k`, and `KE = (1/2) * m * |v|<sup>2</sup>`.  Since there's a square involved here, deviation in speed doesn't not produce the desired temperature in the container

@arouinfar had the great idea of using a Gaussian distribution for the temperature values that are used to compute initial speed.  That seems to be working very nicely.   The mean temperature is computed as it was before: 300K for an empty container, temperature of the container for a non-empty container, or temperature set by the user in the Energy screen.  The deviation is currently set to `0.2 * meanTemperature`, which I subjectively decided "looks nice".

@arouinfar please review in master.  Let me know if you'd like any changes, or if you'd like a query parameter to be able to experiment with the temperature deviation.

**Comment by arouinfar** [comment]
@pixelzoom the behavior in master is looking really great to me! I'm glad the Gaussian distributions of temperatures worked out. :)

I don't have any changes to suggest, so closing.
