### ISSUE TITLE
choose scale factor for heat/cool

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#44]
Applying heat/cool to the container scales the speed of all particles in the container.  The scale computation is:

```js
speedScale = 1 + heatCoolProperty.value / GasPropertiesQueryParameters.heatCool;
```

`heatCoolProperty.value` comes from (and is controlled by) `SCENERY_PHET/HeaterCoolerNode`.  Value is in the range [-1,1], where 0 is off, > 0 is heat, < 0 is cool.

`GasPropertiesQueryParameters.heatCool` is a query parameter. It's range is [100,100000], with default 1000. 

Please experiment with the `heatCool` query parameter, and decide on an appropriate value.

**Comment by arouinfar** [comment]
@pixelzoom thanks for creating this query parameter, it was very helpful! Let's reduce `heatCool` a bit to 800, which seems closer to the Java behavior.

**Comment by pixelzoom** [comment]
Done!
