### ISSUE TITLE
when to redistribute particles in the container

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#45]
When resizing the container, the design document says to redistribute the particles after releasing the resize handle.   That looked a little odd/unintuitive to me, so I implemented 2 behaviors, controlled by the `redistribute` query parameter:

`drag` - redistribute continuously while dragging the resize handle (the default) 
`end` - redistribute when the resize handle is released (as in the design doc)

@arouinfar liked the `drag` behavior when we reviewed this at our 4/2/19 meeting.

@kathy-phet had reservations about `drag` when I demonstrated at a recent (3/21?) status meeting, and said we might need interviews to decide.

**Comment by arouinfar** [comment]
As @pixelzoom said, I quite like the `drag` behavior. I'll tag this issue for design meeting, so we can review it as a group.

**Comment by pixelzoom** [comment]
Notes from 4/9/19 discussion with @arouinfar:

Change the default to "end", keep the query parameter for interviews.

**Comment by arouinfar** [comment]
A few notes from my discussion with @ariel-phet about the `drag` behavior.

* Looks natural, but that goes against the goal of the magical, non-work-doing wall.
* Scaling the particles to fit the new volume could create the illusion of compressing (doing work on) the gas.

I've asked @pixelzoom to keep the `drag` behavior around as a query parameter until we've finished interviews, just in case issues arise with the `end` behavior.

**Comment by arouinfar** [comment]
@pixelzoom once you swap the default back to `end` can you reassign to me?

**Comment by pixelzoom** [comment]
Done, back to you @arouinfar.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! I'll mark as `status:on-hold` for now.

**Comment by pixelzoom** [comment]
@arouinfar Apologies, but at some point, the `redistribute: 'drag'` option stopped working. It's not the default and hasn't been getting tested.  It's going to take some work to restore it.  How strongly do you feel about needing to interview on this?   Or can we just decide that the current default behavior (what was specified in the design doc) is OK?

**Comment by pixelzoom** [comment]
Slack:

Chris Malley [2:10 PM]
How do you feel about this? https://github.com/phetsims/gas-properties/issues/45#issuecomment-493567219  I’m working in a piece of code now where I ran into this, and would love to just remove it, if it’s no longer needed.

Amy Rouinfar [2:12 PM]
No need to maintain/fix it. I wasn’t planning on interviewing on it unless the `end` behavior turns out to be unintuitive or pedagogically problematic for students (unlikely).

Chris Malley [2:12 PM]
OK.  Then I’ll remove the code and :crossed_fingers:
👍

**Comment by pixelzoom** [comment]
To summarize the state of this issue...

Particles freeze when a drag starts, and are redistributed when the drag ends (as specified in the design doc.)  @arouinfar will look for any problems with this during interviews.   If there are none, then we're done.  If there are problems, then we'll decide how to address, including whether to resurrect/reimplement the `redistribute: 'drag'` behavior described in https://github.com/phetsims/gas-properties/issues/45#issue-428359932.

**Comment by arouinfar** [comment]
Since there isn't anything that needs to be done in the interviews, I'm going to go ahead and close this issue. If there are flow issues in the interviews that would necessitate the reviving the `redistribute: 'drag'` behavior, we can reopen.
