### ISSUE TITLE
revisit "Control Temperature" UX

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#46]
This accordion box appears in the Energy screen:

<img width="230" alt="screenshot_1120" src="https://user-images.githubusercontent.com/3046552/55424990-a967db80-553e-11e9-8766-6e27c5b3de9d.png">

<img width="231" alt="screenshot_1121" src="https://user-images.githubusercontent.com/3046552/55425296-5cd0d000-553f-11e9-986b-dbb15f7d69ec.png">

The temperature part of this UX seems potentially confusing.  It's not obvious what temperature is being controlled when "Control Temperature" is checked - it's the _initial temperature_ of particles as they are added to the container.  And it's not clear what's happening when  "Control Temperature" is not checked - they are added based on what's currently in the container.

In our 4/2/19 meeting, @arouinfar and I considered relabeling the checkbox with "Initial Temperature", but that doesn't completely address the problem.

**Comment by pixelzoom** [comment]
This UX is also a little odd because it makes it look like we're setting a "particle temperature".  What we're really doing is setting a temperature that will be used to compute a particle's initial velocity, using **|v| = sqrt( 3kT / m )**.

**Comment by pixelzoom** [comment]
Added meeting:design label, would be good to discuss this while I'm on vacation.

**Comment by arouinfar** [comment]
A more descriptive checkbox label would be something like, "Control Initial Temperature" or "Set Initial Temperature". These are lengthy strings, and would likely pose i18n issues. "Initial Temperature" doesn't seem like an ideal checkbox label, because it doesn't really describe the associated action, which is why we initially chose "Control Temperature". 

> it makes it look like we're setting a "particle temperature". What we're really doing is setting a temperature that will be used to compute a particle's initial velocity

It's true the model is setting the particle's initial velocity to match the desired temperature. However, the the learning goals around this feature are more focused on mixing gases of different <i>temperatures</i>, which is how it would be framed in most classrooms.

An alternative to the "Control Temperature" checkbox would be to use an AquaRadioButtonGroup instead, which would allow us to be a bit more explicit. The options could be "Match Temperature" (default) and "Set Temperature" which would activate the associated NumberControl.

<img src="https://user-images.githubusercontent.com/8419308/57421929-179d5f00-71cb-11e9-9b50-e67cfce257da.png" width=300>

**Comment by arouinfar** [comment]
Unfortunately, we didn't have time to get to this issue in the last two design meetings. The sim is nearly feature complete, so we should make a decision about this soon. @ariel-phet can you review?

**Comment by pixelzoom** [comment]
Thanks for moving this forward @arouinfar.  Also @kathy-phet if you have input, please comment.

**Comment by pixelzoom** [comment]
I'm not the subject-matter expert. But I'm a bit troubled by the notion of "particle temperature" that this UI conveys.  Individual particles do not have temperature.  Temperature is a property of the system, a measure of KE.  This control is setting the `T` used to compute a particle's speed, `|v| = sqrt( 3kT / m )`.  So would it be better to provide a control that set's the particle's initial speed?

**Comment by ariel-phet** [comment]
@pixelzoom @arouinfar here is my suggestion

1. We change "Particle Counts" to just be "Particles" on all screens

2. We move the "Collisions" checkbox into the "Particles Panel"

3. We relabel "Particle Tools" to something like "Injection Temperature" or something that conveys temperature of the particles in the Pump

4. We use the radio buttons suggested above to be "match container" and "Control" or "Set" or something like that

My reasoning is that the collisions on or off is really a more advanced tool and really associated with particles in the container. With a clearer label we can talk about the particles in the pump or "to be injected". I think that is a more natural parsing of the controls and gives us more clarification room.

**Comment by pixelzoom** [comment]
I like @ariel-phet's suggestion.  I think it cleans up the UI nicely, and it addresses my concern about "particle temperature".    @arouinfar let me know if you'd like me to proceed with making it so.

**Comment by arouinfar** [comment]
Great suggestions @ariel-phet, thanks! @pixelzoom let's proceed with https://github.com/phetsims/gas-properties/issues/46#issuecomment-494154279.

**Comment by pixelzoom** [comment]
Changes completed, test drive in master or [1.0.0-dev.25](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.25/phet/gas-properties_en_phet.html).   Screenshot below.   For the NumberControl, I removed the "Temperature" title because it seemed redundant.   Let me know if you'd like to change any of the labels, etc.

<img width="859" alt="screenshot_1206" src="https://user-images.githubusercontent.com/3046552/58056025-f0288980-7b1c-11e9-9505-570c6b01f34e.png">

**Comment by ariel-phet** [comment]
All looks good to me. Although I like "Injection Temperature" perhaps "Pump Temperature" would be clearer. @kathy-phet input would be nice.

Seems like it would be good to have sign off on this at design meeting (and to other pixel polish issues)

**Comment by pixelzoom** [comment]
I considered "Pump Temperature".  But particles are not added solely via the pump.

**Comment by arouinfar** [comment]
@pixelzoom @ariel-phet I think master is looking really nice! While "Injection Temperature"  is perhaps the most accurate, the string is also a bit long which may pose i18n challenges.  Unfortunately, I don't have any better suggestions right now.

> I considered "Pump Temperature". But particles are not added solely via the pump.

The particles added via the FineCoarseSpinners do travel through the pump. However, I worry that it "Pump Temperature" could create the expectation that "Set to" only applies to particles added by pumping the BicylclePumpNode. 

Talking to @DianaTavares, she thought that "Injection Temperature" made a bit more sense, and was preferable for localization.

**Comment by pixelzoom** [comment]
Assigned to @kathy-phet for feedback.

**Comment by pixelzoom** [comment]
5/23/19 design meeting @arouinfar @ariel-phet @kathy-phet 

UI approved.  We'd like something other than "Injection Temperature", but no one had any better ideas.  It's the correct word, just long/techincal.
