### ISSUE TITLE
NSTA milestone?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#47]
The sole milestone in the design document is:
>  January 2020: Grant report is due, so sim must be published

But NSTA (April 11-14) has been mentioned more than once, see below.  If that's something that you want to do, I need to know in the next 48 hours.

---

Discussion about Gas Properties milestones took place in a SOM issue.

@arouinfar on 11/27/18 https://github.com/phetsims/states-of-matter/issues/217#issuecomment-442282755:
> @pixelzoom we don't necessarily need to show this sim to anyone outside of PhET. Occasionally, we like to show feature-complete (ideally close to rc) sims off at conferences. The only such conferences would be NSTA (April 11-14) or ISTE (June 23-26). I don't think it's a particularly realistic expectation for this sim to be feature complete by then. However, if you feel the first two screens would be ready, then you can use either of those conferences as a target for BicyclePumpNode.

@pixelzoom on 3/23/19 in https://github.com/phetsims/states-of-matter/issues/217#issuecomment-475902704
> Given where it's at now, that's still a possibility.

@kathy-phet on 3/29/19 in https://github.com/phetsims/states-of-matter/issues/217#issuecomment-478083539
> :) ... Happy to hear its still possible to show off the first 2 screens by these upcoming conferences!

**Comment by pixelzoom** [comment]
@chrisklus FYI

**Comment by kathy-phet** [comment]
I think being able to show of the sim would get a lot of "yippees" from teachers at NSTA, so it would be great. But it is nothing we "promised" to do. I would say - go-for-it - if you feel comfortable with it as a stretch goal, but I don't think its worth cutting corners to get working that will be undone and cost more in the long run.

**Comment by arouinfar** [comment]
Agreed with @kathy-phet. It'd be nice to show the first two screens off at NSTA, if the sim is in a good state. If that happens, great, but it's not worth cutting any corners. Teachers will be plenty excited to hear that GasProps will be released sometime in the coming months, even without seeing its current state.

**Comment by pixelzoom** [comment]
@arouinfar I'm not clear on what "in a good state" is.  Based on master, can you describe what would need to be completed in order to show at NSTA?

**Comment by arouinfar** [comment]
> Based on master, can you describe what would need to be completed in order to show at NSTA?

For the Ideal screen, I'd want the Hold Constant modes working. The BicyclePumpNode would be nice to have too, but I might consider demoing this screen without it. Blowing the lid and the pressure calibration aren't necessary for NSTA, as I plan to frame the sim as a prototype that isn't feature complete.

For the Explore screen, changing the volume shouldn't freeze/magically move the particles, as it does on Ideal. For example, reducing V results in increased T because the wall will collide with the particles and change their velocity (which is the behavior in Java). This doesn't seem feasible for NSTA.

**Comment by pixelzoom** [comment]
Hold Constant is will not be done  by April 11. So I will not plan on creating a dev version that is specific to NSTA.   If you'd like to show whatever the latest dev version is at that time, check with me for status.
