### ISSUE TITLE
Bugs seen in SwingJS development

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gas-properties#5]
@samreid said:

> Bob: it is clear you have taken a close look and found some long-outstanding issues in the sim and our common libraries.  I looked through and commented on each issue in the Google Doc.
> 
> Ariel: several of the issues Bob pointed out have to do with the behavior or design of the sim.  I was not on this sim design or implementation team, so am unsure why certain decisions were made (or if they were not carefully considered).  We should discuss these issues further, as they pertain to (a) undesirable behavior in our published Java sim (b) changes for the proposed SwingJS publication and (c) for an eventual HTML5 rewrite of the simulation.

Bugs are reported here:
https://docs.google.com/document/d/1aGmLksuZrlVZf6GgeSJdIm4CcHHofqICzP5V4PNKhCQ/edit

**Comment by ariel-phet** [comment]
@amyh-phet it would be good to look over the reported bugs and see if any are relevant, we will not fix anything in the Java sim, but we should decide if there is anything we need to attend to for the port.

**Comment by amyh-phet** [comment]
Logged relevant issues in design doc for HTML5 version of simulation.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> Logged relevant issues in design doc for HTML5 version of simulation.

I can't find these in the design document, can someone point me to them?  Bug reports also do not belong in the design document, it makes them difficult to manage/track. They should be captured in GitHub (or Unfuddle) issue, which are then linked to in the design document.

**Comment by amanda-phet** [comment]
^ that was @amyh-phet not me.

**Comment by arouinfar** [comment]
@pixelzoom looks like these were pasted into the [Bug Reports](https://docs.google.com/document/d/1HOCO6vXfqlHIf3MrdldaiZTPFKYWTzS9Jm8fw-b25EU/edit#heading=h.d94oxdbmfuwu) section at the end of the design doc, which references a [seemingly-orphaned Google doc](https://docs.google.com/document/d/1aGmLksuZrlVZf6GgeSJdIm4CcHHofqICzP5V4PNKhCQ/edit). 

I agree -- the design doc is not the appropriate place for this information. I was scratching my head over this until @phet-steele filled in some of the gaps and directed me to this issue. It looks like Amy H made some notes for design discussion in the doc, so I'll convert them over to GitHub issues.

**Comment by arouinfar** [comment]
I removed the "Bug Reports" section from the design doc, and have converted many of the items in the [SwingJS doc](https://docs.google.com/document/d/1aGmLksuZrlVZf6GgeSJdIm4CcHHofqICzP5V4PNKhCQ/edit
) to issues. There are a few remaining items in the doc that would be good for @pixelzoom to review, and convert to issues, if relevant:
- [ ] 3
- [ ] 13 -- I'm pretty sure that the particles are deliberately given the same energies when pumped in, so I don't think this is actually an issue.
- [ ] 14

There following items were not converted to issues, as they didn't seem relevant.
* 6, 12: Balloons & Buoyancy 
* 15-18: Legacy look-and-feel issues that are totally irrelevant in HTML5 or would be automatically addressed by our modern design principles (e.g. space between value and unit; consistent abbreviations).
* 19-21: Reversible Reactions

**Comment by pixelzoom** [comment]
@arouinfar said:
> There are a few remaining items in the doc that would be good for @pixelzoom to review and convert to issues, if relevant: ...

3 - will not be an issue for HTML5 version
13 - https://github.com/phetsims/gas-properties/issues/19
14 -  will not be an issue for HTML5 version 

> The following items were not converted to issues, as they didn't seem relevant. ...

I skimmed those issues, agree that they're not relevant to the port.

**Comment by pixelzoom** [comment]
@arouinfar I wasn't clear on whether there's anything else to be done here. So back to you.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! I don't think there's anything that needs to be done for Gas Properties. 

I'm not sure what to do about the Balloons & Buoyancy and Reversible Reactions issues. The SwingJS doc is likely to get forgotten by the time those sims get ported. Perhaps I should convert those issues to Unfuddle tickets so we rediscover them when doing the customary Unfuddle review. Does that sound reasonable @pixelzoom?

**Comment by pixelzoom** [comment]
Rather than converting remaining SwingJS issue to individual Unfuddle tickets... I would create 2 Unfuddle tickets:  "SwingJS issues in Balloons & Buoyancy" and "SwingJS issues in Reversible Reactions".  Refer to the SwingJS document, and (if possible) identify which issues in that document are relevant to each sim.  If you think the SwingJS document might go missing (or just don't want to look at it again), copy the SwingJS issues to the Unfuddle ticket.

**Comment by arouinfar** [comment]
Great suggestion @pixelzoom. I've opened two Unfuddle tickets, one for each sim:
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3761
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3762
