### ISSUE TITLE
pressure model

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#50]
In https://github.com/phetsims/gas-properties/issues/37#issuecomment-481338435 (investigate Java model), I investigated the Java model for pressure, summarized in some notes and conclusions.   See that comment for the full narrative. The conclusions were:

> Conclusions:
>
> (1) The Java pressure model has nothing to do with collisions between particles and the container.
> 
> (2) The Java pressure model has nothing to do with `P = NkT/V`. It's not physically correct. It's a "Hollywood" model that relies on a scale factor to make the values look reasonable.
> 
> I don't recommend using the Java model in the HTML5 version, and suggest that we investigate a new model that is physically accurate and uses `P = NkT/V`, or some other physically accurate relationship.

So we need to decide what the desired behavior is for the pressure model, and how to best implement that.

**Comment by arouinfar** [comment]
Moving https://github.com/phetsims/gas-properties/issues/37#issuecomment-481400046 here

>I don't recommend using the Java model in the HTML5 version, and suggest that we investigate a new model that is physically accurate and uses `P = NkT/V`, or some other physically accurate relationship.

I completely agree @pixelzoom. It's important that the pressure model is physical, though there's still some decisions to be made about what exactly that entails. @pixelzoom and I discussed these possibilities for taking wall collisions into account:

(1) Each particle has a flag for wall collisions. Once a particle has collided with the wall, it is counted in the pressure calculation.

(2) Similar to (1), but the wall collision flag would be time-dependent. If a particle hasn't collided with the wall for some amount of time, it would be removed from the pressure calculation.

This is definitely something that should be discussed as a team before @pixelzoom spends time working on this, so I'll tag for design meeting.

**Comment by pixelzoom** [comment]
A couple of other notes...

* The model implemented in [1.0.0-dev.9]() uses `P = NkT/V`.  The computation considers the entire contents of the container, and does not include anything related to particle-container collisions.

* @arouinfar and I noted that the pressure values in the HTML5 version are not even close to those in the Java version.  HTML5 values are roughly 100x larger.   We suspect that the Java version is incorrect; @arouinfar's computations indicate that the container in the Java version would have to be incredibly deep in order for the values to make sense.

**Comment by arouinfar** [comment]
> @arouinfar's computations indicate that the container would need to be incredibly deep (~100nm) in order for the values to make sense. (The container is at most 9nm wide.)

I checked my notebook, and my calculation shows an even larger depth.

With a default container width (6.6 nm), I set up the following situation:
N = 100 
T = 300 K
P = 0.52 atm (52689 Pa)

Using  `V = NkT/P`, the corresponding volume would be 7863 nm^3. Assuming a square container, the depth would need to be ~180 nm, which is 20 times larger than the max width of the container.

**Comment by pixelzoom** [comment]
Discussed a bit on Zoom today with @ariel-phet.  Notes...

* Pressure is currently computed as `P = NkT/V`.  Temperature is `T = (2/3)KE/k`.  All particles in the container contribute to N and T.
* What is the desired depth of the container? It's currently 1nm. Changing depth is one way to adjust the pressure values.
* When do particles contribute to the pressure?  After they have collided with the container? When they have collided with the container within some time interval?
* If particles in the container don't contribute to pressure, should they also not contribute to temperature? `P = NkT/V`.
* Should we add a bit of noise to the pressure value (based on number of particles?), so that the gauge fluctuates a bit?
* Is "mean free path" relevant? 

And feel free to discuss this while I'm on vacation.

**Comment by pixelzoom** [comment]
4/25/19 design meeting:

* When container is empty, wait for first particle-container collision before showing non-zero pressure.

* Add noise to pressure gauge, based on number of particles.  More particles results in less jitter in the gauge needle.

**Comment by pixelzoom** [comment]
@arouinfar @ariel-phet @kathy-phet Changes to the pressure model requested in https://github.com/phetsims/gas-properties/issues/50#issuecomment-486841641 have been completed.  Please review in [1.0.0-dev.14](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.14/phet/gas-properties_en_phet.html)

When particles are added to an empty container, the pressure is zero until 1 particle has collided with the container. 

The pressure gauge has a bit of jitter that is inversely proportional (linearly) to the pressure. There are 2 query parameters that you can use to tune the jitter.  Be sure to examine both the kPa and atm scales - the jitter will be less evident in the atm scale.

* `minJitter` sets the minimum amount of jitter.  Since the gauge gets more stable as the pressure increases, this is the jitter present when the pressure gauge is at its _maximum_.  Default is 0 kPa, must be >= 0 and < `maxJitter`. 

* `maxJitter` sets the maximum amount of jitter. This is the jitter present when the pressure gauge is closest to zero, when it would have the most difficultly reading a consistent pressure.  Default is 50 kPa, must be > 0 and > `minJitter`.  

A couple of other query parameters relevant to the pressure model:

* `containerDepth` is the depth of the container.  Use a larger value to decrease the pressure values. Default is 1 nm, must be > 0.

* `maxPressure` is the pressure at which the lid blows off, and the max pressure of the gauge. Default is 50000 kPa, must be > 0.

Please let me know how you'd like these parameters set.

**Comment by ariel-phet** [comment]
@pixelzoom before tuning these...

Currently (testing on Chrome) the behavior at low pressure (a pump or two of the pump) looks good, the numbers "bounce" around in a nice way around the ideal pressure.

At high pressure however, the numbers move so fast as to be difficult to read (in kPA). Perhaps the "noise" should not be added every time step or such?  Or is there some way to not have the numbers be so flickery at high pressures but more "meander" around?

**Comment by pixelzoom** [comment]
@ariel-phet I've added this query parameter:

* `pressureGaugeSamplePeriod` controls how often the pressure gauge is update. Default is 0.25 ps, must be > 0.

**Comment by ariel-phet** [comment]
I saw something around these parameters work well

`?pressureGaugeSamplePeriod=.75&maxJitter=200&containerDepth=2&maxPressure=20000`

I think keeping max pressure to around 20000 kPa makes lots of physical sense. Compressed gas cyclinders are at around 2500-3000 psi so I think we may not want to exceed this limit. 

The jitter with 0.75 looks very good to me.

**Comment by pixelzoom** [comment]
Thanks @ariel-phet, those values look good to me too. 

@arouinfar @kathy-phet ?

**Comment by pixelzoom** [comment]
I'm going to change the default to the values suggested by @ariel-phet in https://github.com/phetsims/gas-properties/issues/50#issuecomment-488049818.  If you would like something different, please come to 5/2/19 design meeting prepared to discuss.

**Comment by arouinfar** [comment]
Thanks @ariel-phet. After testing things out a bit, I also like those values.

One thing I find a bit difficult is how large the pressure values are in kPa, which makes the fluctuations a bit more distracting. I'm wondering if MPa might be more appropriate. Even at small values, one decimal place might be enough to show non-zero pressures in MPa for most cases.

**Comment by pixelzoom** [comment]
5/2/19 design meeting @arouinfar @ariel-phet @kathy-phet:

- [ ] Make atm the default selection in pressure gauge
- [ ] add 1 decimal place to atm

`pressureGaugeSamplePeriod` may change based on #54.

**Comment by pixelzoom** [comment]
@arouinfar requested changes made above, please review, feel free to close.

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom!

**Comment by pixelzoom** [comment]
Reopening.   We need to decide whether the gauge has jitter when pressure is being held constant in the Ideal screen.   

Today's Slack discussion with @arouinfar:

Chris Malley [2:31 PM]
GP question… When we’re holding pressure constant in the Ideal screen, should there be jitter in the pressure gauge?

Amy Rouinfar [2:39 PM]
Oh, that’s a good question, and I could probably make an argument either way. In Java, holding the pressure constant doesn’t lock down the needle — there are still some fluctuations, but that would come down to the actual fluctuations in the model. It does seem kind of nice to remove the jitter when P is constant (and would better emphasize P being constant), but I don’t know if that would unnecessarily complicate things.
Seems like something that might be nice to put on the agenda for tomorrow.

Chris Malley [2:40 PM]
Removing the jitter when P is constant is easy.  Using a different jitter would not be easy.

Amy Rouinfar [2:40 PM]
I think we would either keep the same jitter, or remove it entirely. No need to complicate the jitter.

**Comment by pixelzoom** [comment]
On second thought... Moving https://github.com/phetsims/gas-properties/issues/50#issuecomment-492887935 to https://github.com/phetsims/gas-properties/issues/73.
