### ISSUE TITLE
tune the Particle Flow Rate indicators

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#51]
The particle flow rate feature in the Diffusion screen requires tuning.  There are 2 related query parameters:

* `flowRateSamplePeriod` is the sample period for particle flow rate, in ps.  It determines how often the vectors are updated. Default is 1 ps, and it must be > 0.

* `flowRateScale` is the length of a 1 particle/ps flow rate vector. It determines how long the vectors will be. Default is 25, and it must be > 0.

Please experiment with these parameters in master or [1.0.0-dev.12](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.12/phet/gas-properties_en_phet.html), and let me know what values you'd like.

**Comment by pixelzoom** [comment]
Make sure that `flowRateSamplePeriod` value behaves well when the sim is paused and the Step button is used to advance the sim.

**Comment by pixelzoom** [comment]
@arouinfar I added query parameter `maxInitialNumber`, so that you can experiment with larger numbers of particles in the Diffusion screen.  Default is 100, and it must be > 0.

**Comment by pixelzoom** [comment]
5/2/19 design meeting @arouinfar @ariel-phet @kathy-phet:

* Try a running average.

**Comment by pixelzoom** [comment]
Particle Flow Rate now uses a running average, and can be tuned using these query parameters:

* `flowRateSamples` is the number of samples in the running average, default is 50
* `flowRateScale` is the length of a 1 particle/ps vector, default is 25

A sample consists of 3 things: 
* dt value, in ps
* the number of particles that crossed from left to right
* the number of particles that crossed from right to left 

Each time the simulation steps:
* a sample is taken
* if there are more than `flowRateSamples`, then the oldest sample is dropped
* averages are computed for the current set of samples 
* the view is updated to show the averages

@arouinfar @ariel-phet @kathy-phet please experiment with [1.0.0-dev.18](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.18/phet/gas-properties_en_phet.html) and provide feedback.

**Comment by pixelzoom** [comment]
5/9/19 design meeting @arouinfar @ariel-phet @KatieWoe 

Running average is the right way to go, looking better.  @arouinfar will play around with query parameters.  Bigger `flowRateSamples` (e.g. 300) seems nice.   Will also need to examine larger number of particles since we increased max to 200.

**Comment by pixelzoom** [comment]
@arouinfar also be sure to test with "slow" radio button selected.  It's not looking too good in slow mode to me.

**Comment by pixelzoom** [comment]
Raising priority to high.

**Comment by arouinfar** [comment]
I've spent quite a bit of time testing `?flowRateSamples=300`, experimenting with N, mass, radius, and T.  I think using using 300 samples smooths the data enough, but it's not so many that the data appears to lag behind the other visuals in the sim.

> @arouinfar also be sure to test with "slow" radio button selected. It's not looking too good in slow mode to me.

Slow motion doesn't look amazing, but I think the data is still interpretable at `?flowRateSamples=300`. A larger number of samples would further smooth out the slow motion, but I'm a bit wary of increasing it any further.

@pixelzoom can you update `flowRateSamples` to 300?

**Comment by pixelzoom** [comment]
`flowRateSamples` has been changed to 300 in master.

**Comment by pixelzoom** [comment]
@arouinfar Did you play around with `flowRateScale`?   If I set things up like this, then I get a really big vector immediately after "Remove Divider" button is pressed:

<img width="1011" alt="screenshot_1212" src="https://user-images.githubusercontent.com/3046552/58216183-91007b80-7cba-11e9-9326-23da3af09c6b.png">

**Comment by pixelzoom** [comment]
5/23/19 design meeting @arouinfar @ariel-phet @kathy-phet 

Current settings look good.  OK for vectors to be long in extreme case.  

I will remove query parameters.

**Comment by pixelzoom** [comment]
Query parameters removed. Closing.
