### ISSUE TITLE
revise histograms

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#52]
In 4/25/19 design meeting with @arouinfar @kathy-phet @ariel-phet, we identified that the histograms in the _Energy_ screen require tuning.   I've added 4 related query parameters:

* `speedBins` is the number of bins in the Speed histogram.  Default is 10, must be > 0.

* `speedBinWidth` is the width of a bin in the Speed histogram, in nm/ps.  Default is 0.25 nm/ps, must be > 0.

* `keBins` is the number of bins in the Kinetic Energy histogram.  Default is 10, must be > 0. 

* `keBinWidth` is the width of a bin in the Kinetic Energy histogram, in AMU * nm<sup>2</sup> / ps<sup>2</sup>.  Default is 1 AMU * nm<sup>2</sup> / ps<sup>2</sup>, must be > 0.

@arouinfar please play around with these parameters in master, let me know what values achieve the desired behavior.   Let me know if you need additional query parameters.

**Comment by pixelzoom** [comment]
Other design question related to the histograms:

* What do you want to do when there is data that is outside the range of the histogram? Java showed '>>', HTML5 currently shows '...'

* How do you want auto-scale to behave for the y axes?  When do they scale? How much do they scale?  Do both histograms have the same scale? 

* How often do you want the histograms to update, in ps?  They currently update every time the simulation clock ticks.

**Comment by pixelzoom** [comment]
Please come to 5/2/19 design meeting with feedback on how you'd like these parameters set, and any other thoughts on how you'd like the histograms changed.

**Comment by pixelzoom** [comment]
5/2/19 design meeting @arouinfar @ariel-phet @kathy-phet

* Add sample period that applies to the 2 histograms
* Fix up y scale

**Comment by pixelzoom** [comment]
5/2/19 design meeting @arouinfar @ariel-phet @kathy-phet

* @ariel-phet proposed making the histograms wider, and covering part of the container. 
* need to play around with query parameters more
* will probably need another meeting on this

In the meantime, @pixelzoom TODO:
* Add sample period that applies to the 2 histograms & Average Speed
* Fix up y scale

**Comment by pixelzoom** [comment]
Changes requested on https://github.com/phetsims/gas-properties/issues/52#issuecomment-488847233 have been completed.  These changes are present in [1.0.0-dev.17]( https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.17/phet/gas-properties_en_phet.html).

`histogramSamplePeriod` (default 1 ps) controls how often Average Speed, Speed histogram, and KE histogram are updated. 

Since we adjusted the y-axis to be 0.2 * numberOfParticles, I've added an "out of range" indicator for the y axis, similar to the x axis (green ellipsis "...")

Assigning to design team for feedback.

**Comment by pixelzoom** [comment]
As noted in https://github.com/phetsims/gas-properties/issues/61, units for length and position have been changed from nm to ps.    So keep that in mind when setting `speedBinWidth` and `keBinWidth`.  Their defaults are now `250 pm/ps` and `1E6 AMU * pm^2 / ps^2` respectively.

**Comment by ariel-phet** [comment]
This seemed to be a pretty good setting

https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.17/phet/gas-properties_en_phet.html?keBinWidth=8e5&speedBinWidth=170&keBins=19&speedBins=19

But I have another idea I will discuss at design...

**Comment by pixelzoom** [comment]
5/8/19 design meeting @arouinfar @ariel-phet @KatieWoe 

- [ ]  change defaults to @ariel-phet's values: 
`?keBinWidth=8e5&speedBinWidth=170&keBins=19&speedBins=19`

- [x] increase container depth to 4000 pm, so more difficult to blow lid off

- [ ] scale y axis of both histograms based on 95% of max bin count of Speed histogram

- [  ] hide out-of-range indicators behind a query parameter, change to an arrow

- [ ] use 'white' for Speed bars, use PhetColorScheme.KINETIC_ENERGY for KE bars

**Comment by pixelzoom** [comment]
I'm down to one item:

> - [ ]  scale y axis of both histograms based on 95% of max bin count of Speed histogram

... and I'm realizing that histograms have gotten to be a bit of a mess.  So I'm going to be doing a serious overhaul before addressing that item.

**Comment by pixelzoom** [comment]
Histograms have been mostly rewritten.

Query parameters:
* `?bins` is the number of bins in each histogram, default is 19
* `?speedBinWidth` is the bin width for the Speed histogram, default is 170 pm/ps
* `?keBinWidth` is the bin width for the Kinetic Energy histogram, default is 8E5 AMU * pm^2 / ps^2
* `?histogramSamplePeriod` is the sample period, default is 1 ps

Other information: 
* Horizontal lines are spaced at intervals of 20 particles.
* The minimum y scale is 20 particles.
* The y scale is 1.05 * the largest bin count _in both histograms_, to ensure a bit of space above the tallest bar, and to ensure that both histograms have the same y scale.
* Any issues related to when the histograms update while the sim is paused will be addressed in #60. They currently update when the sample period has been reached.

@arouinfar please test drive and let me know what you think.  Keep an eye out for anything that looks wrong, since this is new code.

**Comment by pixelzoom** [comment]
I noticed that with the max number of particles in the container, the horizontal lines can become pretty dense.  See screenshot below.  Maybe this is OK because it indicates "a lot of particles".   Or maybe we want to increase the spacing of the horizontal lines.

<img width="1018" alt="screenshot_1231" src="https://user-images.githubusercontent.com/3046552/58967264-1d0dab00-8771-11e9-9ce2-16267c6d0ee4.png">

**Comment by arouinfar** [comment]
@pixelzoom I think the horizontal lines will need to be pretty dense when the container is full so that the scale is still useful for lower N. 

That said, I think increasing the spacing to 25 particles would improve things a bit.

**Comment by pixelzoom** [comment]
@arouinfar spacing of 25 doesn't look significantly better to me.  50 seems better for large N (see screenshot), and still seems to work for small N.  I've added the following query parameter for you to experiment with, default is 25.

```js
    /**
     * Spacing between horizontal lines in the histograms, in number of particles.
     * For internal use only.
     */
    histogramLineSpacing: {
      type: 'number',
      isValidValue: value => ( value > 20 ),
      defaultValue: 25
    }
```

<img width="1014" alt="screenshot_1233" src="https://user-images.githubusercontent.com/3046552/58978613-6cf86c00-8789-11e9-9ac5-5b7c175e721d.png">

**Comment by arouinfar** [comment]
@pixelzoom thanks for setting up the query parameter. I agree -- 50 looks great, and it's still reasonable for low N, so let's go with 50.

**Comment by pixelzoom** [comment]
Changed spacing to 50 and deleted `histogramLineSpacing` query parameter. 

@arouinfar anything else here?  I wasn't sure if this was the only tweak, or if you have more to review.

**Comment by arouinfar** [comment]
Looks good to me @pixelzoom
