### ISSUE TITLE
specify requirements for smoothing quantities

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#54]
Discussed a bit with @arouinfar and decided to create an issue.   We need to:

(1) Identify which quantifies need to be smoothed by averaging over some sample period.

(2) Identify what the sample period is for those quantities, and whether there are any issues with having different sample periods for different quantities.

(3) Determine how the Step button is related to smoothing.  Are quantities smoothed while the user is manually stepping the sim, or are quantities updated each time the Step button is pressed?

**Comment by pixelzoom** [comment]
Please specify smoothing and Step behavior for the following elements:

* Stopwatch
* Collision Counter
* Thermometer
* Pressure Gauge
* Average Speed accordion box
* Speed histogram
* Kinetic Energy histogram
* Data accordion box
* Center of Mass indicators
* Particle Flow Rate indicators

**Comment by pixelzoom** [comment]
@arouinfar can you take a pass at this before 5/2/19 design meeting?

**Comment by pixelzoom** [comment]
5/2/19 design meeting @arouinfar @ariel-phet @kathy-phet:

* We may have one universal sample period for the sim, but not yet.
* Average Speed, Speed histogram, KE histogram will share a sample period
* Pressure gauge has a sample period, `?pressureGaugeSamplePeriod`
* Particle Flow Rate will use a running average

Other things will update on every time step:
* Particles
* Thermometer
* Data accordion box
* Center of Mass indicators

When the sim is paused, nothing special will be done for the Step button.  So the view may or may not update on each press of the Step button, depending on what the sample periods are.

@arouinfar Let me know if I've summarized the above correct.  Indicate any corrections, then please assign back to me.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! Summary looks great, so back to you.

**Comment by pixelzoom** [comment]
This is fully implemented, here are the current query parameters:

> * Average Speed, Speed histogram, KE histogram will share a sample period

See `histogramSamplePeriod` (default 1 ps) in https://github.com/phetsims/gas-properties/issues/52#issuecomment-489796634.

> * Pressure gauge has a sample period, `?pressureGaugeSamplePeriod`

`pressureGaugeSamplePeriod`, default is still 0.75 ps

> Particle Flow Rate will use a running average

See `flowRateSamples` (default 50) in https://github.com/phetsims/gas-properties/issues/51#issuecomment-490314790.

@arouinfar Back to you to decide what the values should be, and whether we should have one universal sample period for the sim.

**Comment by arouinfar** [comment]
@pixelzoom I think we can pass on the universal sample period. The `pressureGagueSamplePeriod` also seems fine as-is. Since there are separate issues for `histogramSamplePeriod` and `flowRateSamples`, we can tune the sample periods there. I'll go ahead and close this issue.
