### ISSUE TITLE
revisit Collision Counter design

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#56]
This was mentioned at an earlier design meeting.  Creating an issue so that it's on our radar.  If it's no longer necessary, feel free to close.

**Comment by pixelzoom** [comment]
Having used the Collision Counter a few thousand times now....  It's biggest deficiency is that it's not obvious when the counting has completed.  The button icon change is the clue, and it's a bit subtle.  Maybe the button should also be `red` while it's counting?  Something to clearly indicate that the counter is 'on'.

**Comment by pixelzoom** [comment]
Maybe something like this?

<img width="186" alt="screenshot_1164" src="https://user-images.githubusercontent.com/3046552/56931111-203fb800-6a9c-11e9-9398-65654ef6c191.png"> <img width="181" alt="screenshot_1165" src="https://user-images.githubusercontent.com/3046552/56931115-23d33f00-6a9c-11e9-9647-394edc2eeac0.png">

**Comment by arouinfar** [comment]
> The button icon change is the cue, but it's a bit subtle. 

Agreed that the cue is a bit subtle @pixelzoom. I do like the direction you've taken, but I think the colors might be a bit strong. Perhaps we can color the icons instead of the buttons? Let's see what the team thinks.

**Comment by arouinfar** [comment]
Another thing we should iron out is the sample periods. At 2.5 ps per real-time second, most of the sample periods are quite long. Perhaps options for 5 ps, 10 ps, 20 ps would be more appropriate?

**Comment by pixelzoom** [comment]
@arouinfar said:
> ... Perhaps we can color the icons instead of the buttons?

Done in master, please review.

> Another thing we should iron out is the sample periods. ...

I've added query parameter `collisionCounterSamplePeriods`, default `10,25,50,100`, values must be integers.   If you want to try the values that you proposed, use `?collisionCounterSamplePeriods=5,10,20`.

**Comment by arouinfar** [comment]
> Done in master, please review. Screenshots:

Looks great! I believe the team saw the updated icons in the 5/9 design meeting, and also liked the look of the colorized icons.

> I've added query parameter `collisionCounterSamplePeriods`

Thanks @pixelzoom. This was super helpful in testing out various sample periods. 

I still quite like the 5 ps, 10 ps, and 20 ps options (with 10 ps being the default). This way, the collision counter will run 2-8 actual seconds, which felt like a reasonable range of times. While the 5 ps sampling period may seem short, I didn't notice too much noise in the measurement.

Tagging for design meeting for design team sign-off.

**Comment by pixelzoom** [comment]
> I still quite like the 5 ps, 10 ps, and 20 ps options (with 10 ps being the default)

Done in master.

**Comment by pixelzoom** [comment]
5/16/19 design meeting @arouinfar @kathy-phet 

Buttons icons and sample periods approved.  Closing.
