### ISSUE TITLE
icons for Collision Counter and Stopwatch

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#57]
This was mentioned in an earlier design meeting.

Icons currently look like this:

<img width="233" alt="screenshot_1163" src="https://user-images.githubusercontent.com/3046552/56930557-45cbc200-6a9a-11e9-9121-19b77620d746.png">

We probably want something that is less detailed, but can still be created programmatically.

**Comment by arouinfar** [comment]
The TimerNode has less going on, so I think something as simple as hiding the `0.00 ps` readout (leaving the field empty) would go a long way to decluttering the icon. If the empty readout looks too strange, we could try displaying a noValue character such as an emdash instead.

The Collision Counter icon is trickier, and I'm not sure I have a great idea, but here are a few possibilities:

1. Remove `Wall Collisions` and `Sample Period` strings, but leave layout unchanged.
![image](https://user-images.githubusercontent.com/8419308/57655243-67957080-7593-11e9-8c4c-89c28cfceb72.png)


2. Really iconify things, and just show the counter field and play button centered in the icon.
![image](https://user-images.githubusercontent.com/8419308/57655119-19806d00-7593-11e9-8873-ea9dd2538215.png)

I prefer option (1), as seems more reasonable and doesn't look too bad at 100% zoom. Tagging for design meeting to get team feedback, and to see if folks have any other suggestions.

**Comment by pixelzoom** [comment]
I should have clarified. The goal here is to avoid having to create full-blown model + view in order to create icons.  Neither of the above gets us there. If we're going to provide that much detail, we should continue to use what we have.  It's going to be too complicated to create something that detailed, for little gain. 

I had something much more simplified in mind, see below.  Or maybe we should drop the icons?

![screenshot_969](https://user-images.githubusercontent.com/3046552/57658329-c52dbb00-759b-11e9-9752-930c3c976115.png)

**Comment by pixelzoom** [comment]
The simplified icons shown in https://github.com/phetsims/gas-properties/issues/57#issuecomment-492009797 are in master, if you want to see in context.

**Comment by arouinfar** [comment]
Ah, thanks for the clarification @pixelzoom. I really like your proposed icons!

Looks like we have 3 options to discuss with the team. In descending order of my personal preference...

1. Go truly iconic with the silhouette proposed in https://github.com/phetsims/gas-properties/issues/57#issuecomment-492009797
2. Icon is a scaled-down version of the tool, text and all
3. No icon

Having an icon next to the checkboxes will make them a bit more attention grabbing, so students are more likely to find the tool or interact with it a bit earlier in the flow. I would prefer to keep an icon of some sort. Looking at master, the simple icon looks quite nice. It's still attention-grabbing, but it doesn't look busy with all of the text/buttons.

**Comment by pixelzoom** [comment]
I would also prefer to have an icon.  And (for me) the most important features of the icon are its general shape and color.

**Comment by pixelzoom** [comment]
5/16/19 design meeting:  Simplified icons approved. Closing.
