### ISSUE TITLE
screen icons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#58]
It's time to start thinking about screen icons.

**Comment by arouinfar** [comment]
I've drafted some screen icons. As mentioned in previous design meetings, I'm struggling a bit with how to distinguish between the Ideal and Explore screens, so any ideas would be appreciated. @ariel-phet can you review?

### Ideal

There was some talk of showing the ideal gas law on the screen icon, but that may be too literal. Other drawbacks include:
* Icon would give away too much information.
* The model uses `PV = NkT` but the form `PV = nRT` would be more familiar to students.
* Screen icon would not be localizable. 

Instead, I've tried to cue some of the variables in the equation, and here are a few options:

<img src="https://user-images.githubusercontent.com/8419308/58443104-13b77b00-80ad-11e9-8fd4-7c20d2077a86.png" width=373> <img src="https://user-images.githubusercontent.com/8419308/58443104-13b77b00-80ad-11e9-8fd4-7c20d2077a86.png" width=101>
<img src="https://user-images.githubusercontent.com/8419308/58443105-14501180-80ad-11e9-93ca-e771497abb53.png" width=373> <img src="https://user-images.githubusercontent.com/8419308/58443105-14501180-80ad-11e9-93ca-e771497abb53.png" width=101>

### Explore
<img src="https://user-images.githubusercontent.com/8419308/58443102-13b77b00-80ad-11e9-9d46-ee1351608815.png" width=373> <img src="https://user-images.githubusercontent.com/8419308/58443102-13b77b00-80ad-11e9-9d46-ee1351608815.png" width=101>

### Energy
<img src="https://user-images.githubusercontent.com/8419308/58443101-13b77b00-80ad-11e9-83b7-23e51e98b91a.png" width=373> <img src="https://user-images.githubusercontent.com/8419308/58443101-13b77b00-80ad-11e9-83b7-23e51e98b91a.png" width=101>

### Diffusion
<img src="https://user-images.githubusercontent.com/8419308/58443099-13b77b00-80ad-11e9-8689-65874ba90a9e.png" width=373> <img src="https://user-images.githubusercontent.com/8419308/58443099-13b77b00-80ad-11e9-8689-65874ba90a9e.png" width=101>

**Comment by pixelzoom** [comment]
Explore and Diffusion icons seem a bit too similar to me.

**Comment by ariel-phet** [comment]
@arouinfar 

1. I like the Energy icon, perhaps give the histogram some unlabelled axes, just so it is not so disembodied

2. I like the first direction for Ideal, showing P, V, T (the iconized container with gauge and thermometer)

3. Perhaps for diffusion, show the ghosted separator and maybe the flow arrows? Do more like an iconized container as you did with the Ideal and flow arrows underneath?

**Comment by arouinfar** [comment]
> I like the Energy icon, perhaps give the histogram some unlabelled axes, just so it is not so disembodied

I originally tried that but the stroke needs to be pretty thick to be seen in the navbar icon. Here are a few options:
<img src="https://user-images.githubusercontent.com/8419308/58505088-5d55a380-8149-11e9-9435-27ec1655046d.png" width=373>   <img src="https://user-images.githubusercontent.com/8419308/58505088-5d55a380-8149-11e9-9435-27ec1655046d.png" width=101>
<img src="https://user-images.githubusercontent.com/8419308/58505935-5b8cdf80-814b-11e9-8e23-b4e2cbd5b6c7.png" width=373>   <img src="https://user-images.githubusercontent.com/8419308/58505935-5b8cdf80-814b-11e9-8e23-b4e2cbd5b6c7.png" width=101>

> I like the first direction for Ideal, showing P, V, T (the iconized container with gauge and thermometer)

Thanks! That's also my personal preference.

> Perhaps for diffusion, show the ghosted separator and maybe the flow arrows? Do more like an iconized container as you did with the Ideal and flow arrows underneath?

I think these ideas could all help differentiate the Explore and Diffusion screens. Here are few more iterations which include the divider, flow rate arrows, and/or container.

<img src="https://user-images.githubusercontent.com/8419308/58505903-43b55b80-814b-11e9-9d5b-1049054de16f.png" width=373>   <img src="https://user-images.githubusercontent.com/8419308/58505903-43b55b80-814b-11e9-9d5b-1049054de16f.png" width=101>
<img src="https://user-images.githubusercontent.com/8419308/58505902-431cc500-814b-11e9-9d93-582d845d79bc.png" width=373>   <img src="https://user-images.githubusercontent.com/8419308/58505902-431cc500-814b-11e9-9d93-582d845d79bc.png" width=101>
<img src="https://user-images.githubusercontent.com/8419308/58505904-43b55b80-814b-11e9-8411-a7d4e611d8d8.png" width=373>  <img src="https://user-images.githubusercontent.com/8419308/58505904-43b55b80-814b-11e9-8411-a7d4e611d8d8.png" width=101>


<img src="https://user-images.githubusercontent.com/8419308/58505089-5d55a380-8149-11e9-805b-930ab41751f6.png" width=373>   <img src="https://user-images.githubusercontent.com/8419308/58505089-5d55a380-8149-11e9-805b-930ab41751f6.png" width=101>

**Comment by ariel-phet** [comment]
@arouinfar 

1. I like the second option for Energy above (with x and y unlabelled axis)

2. For diffusion, I like option 3. I think the container and the flow arrows nicely communicate what is going on

**Comment by pixelzoom** [comment]
@ariel-phet said:
> I like the first direction for Ideal, showing P, V, T (the iconized container with gauge and thermometer)

A bit complicated to create programmatically, but doable.  

> I like the second option for Energy above (with x and y unlabelled axis)

Sine nothing like this appears in the sim, I can't programmatically generate this one without writing new code. 

> For diffusion, I like option 3. I think the container and the flow arrows nicely communicate what is going on

Me too.  And it's straightforward to create programmatically.

**Comment by pixelzoom** [comment]
I did a quick implementation of the Ideal and Energy icons.  The Energy icon reads pretty well, but I think all of the others have too much detail.   Test drive in master.  (Ideal icon only has a single particle for now.)

**Comment by pixelzoom** [comment]
I did a quick implementation of the Ideal and Energy icons.  The Energy icon reads pretty well, but I think all of the others have too much detail -- especially for the navigation bar.   Test drive in master.  (Ideal icon only has a single particle for now.)

**Comment by arouinfar** [comment]
@pixelzoom I am certainly happy to provide assets for any icon that is not feasibly drawn in code.

> I like the second option for Energy above (with x and y unlabelled axis)

Frankly, that's my least favorite option. I still prefer the look without axes at all -- it's an iconic representation, after all.

>> For diffusion, I like option 3. I think the container and the flow arrows nicely communicate what is going on
>
>Me too. And it's straightforward to create programmatically.

Agreed, glad to see we're on the same page. As @pixelzoom points out, it may have a bit too much detail for the navbar. Perhaps the 2nd option would scale down better?

<img src="https://user-images.githubusercontent.com/8419308/58505902-431cc500-814b-11e9-9d93-582d845d79bc.png" width=373>   <img src="https://user-images.githubusercontent.com/8419308/58505902-431cc500-814b-11e9-9d93-582d845d79bc.png" width=101>

> I did a quick implementation of the Ideal and Energy icons. The Energy icon reads pretty well, but I think all of the others have too much detail -- especially for the navigation bar. Test drive in master. (Ideal icon only has a single particle for now.)

I think these are both looking good @pixelzoom. For Energy, we might want to adjust the bar heights so there's a bigger decay after the 2nd bar, but I think it looks good otherwise. Even in the navbar, I think the Ideal icon has enough detail. The particle size you used looks good, but we probably won't need as many as in my original mockup. Maybe just 10 or so?

@kathy-phet can you take a look at the screen icon options and weigh in?

**Comment by pixelzoom** [comment]
@arouinfar said:
>  I am certainly happy to provide assets for any icon that is not feasibly drawn in code.

Yes, I appreciate that.  But then things have a tendency to get out of sync with reality.  For example colors, or the lighting direction in some of your mockups above.   If we use the same code that is used to draw the things that appear in the sim, then this problem is avoided. 

There's also the question of what to do in projector mode.  If you have an icon (like Diffusion) that shows a black container, do you want it to change to white in projector mode?  If so, then we can't currently do that with artwork.

>  As @pixelzoom points out, it may have a bit too much detail for the navbar. Perhaps the 2nd option would scale down better?

In general, I recommend fewer particles in the icons, as few as you can tolerate.

**Comment by pixelzoom** [comment]
Added `meeting:design` label for discussion at 5/30/19 design meeting.   Please review the mockups in this issue and come to the meeting with suggestions for icons.

**Comment by arouinfar** [comment]
> Yes, I appreciate that. But then things have a tendency to get out of sync with reality. For example colors, or the lighting direction in some of your mockups above. If we use the same code that is used to draw the things that appear in the sim, then this problem is avoided.

Understood. I'd also clean up colors and lighting before delivering assets. :)

> There's also the question of what to do in projector mode. If you have an icon (like Diffusion) that shows a black container, do you want it to change to white in projector mode? If so, then we can't currently do that with artwork.

No, I don't think it'd be necessary to adjust the icons in projector mode. Does joist even support adaptive screen icons?

**Comment by pixelzoom** [comment]
@arouinfar asked:
> Does joist even support adaptive screen icons?

No, not directly.  It's possible (but not pretty) to handle to switch images for screen icons in sim-specific code.

**Comment by kathy-phet** [comment]
For Ideal: 
I like what is in phettest but would put maybe 3 blue balls in the box
For Energy: 
I like what is there 

For Diffusion: 
I like the close up, but would keep the lower wall of the box. This idea: 
![image](https://user-images.githubusercontent.com/5096804/58658895-d89c8e00-82de-11e9-94a0-2a765597934b.png)

For Explore: 
Maybe close up of the left hand wall with the handle in a state where a few molecules are right against the wall and a few are visible a bit away

**Comment by pixelzoom** [comment]
5/30/19 design meeting @arouinfar @ariel-phet @kathy-phet 

* put 3 particles in Ideal icon 
* 10 more yMargin for Energy icon
* for Diffusion, try green solid line with 2 particles on left, 3 on right
* for Explore, try close up of handle, 2 particles against wall, 2 away from wall

**Comment by pixelzoom** [comment]
@arouinfar For the Energy icon, please let me know how many bins you'd like, and a value [0,1] for each bin.

**Comment by pixelzoom** [comment]
@arouinfar I've made a quick first pass at today's design decisions, see screenshot below and master.  Let me know what you'd like to change. 

<img width="929" alt="screenshot_1224" src="https://user-images.githubusercontent.com/3046552/58667769-312a5600-82f4-11e9-997f-d2b0eb731be3.png">

**Comment by pixelzoom** [comment]
I had used the wrong colors for particles in the Diffusion screen icon.  Fixed in the above commit and pushed to master.

**Comment by pixelzoom** [comment]
@arouinfar Also note that the screen icons _do_ change in Projector mode.  You said that this wasn't a requirements, but by creating these icons programmatically, it came for free.  It can be turned off for the screen icons if desired, but as I play with it, it seems to make sense - especially since the icons depict what is shown on the screens.

**Comment by arouinfar** [comment]
@pixelzoom the icons are looking really nice! I think changing the icons in projector mode is also a nice touch.

For Energy, we had discussed using more bins with decaying heights, so let's try these values.

| Bin | Value |
| --- | --- |
| 1 | 0.80 |
| 2 | 1 | 
| 3 | 0.85 | 
| 4 | 0.53 | 
| 5 | 0.33 | 
| 6 | 0.21 | 
| 7 | 0.13 | 
| 8 | 0.08 | 
| 9 | 0.05 | 
| 10 | 0.03 | 

The barrier in the Diffusion icon looks a bit off-center. Can you center it @pixelzoom?
<img src="https://user-images.githubusercontent.com/8419308/58837708-985c4900-8619-11e9-9f9b-4d13a90aa71c.png" width=300>

**Comment by pixelzoom** [comment]
@arouinfar requested changes were made, please verify in master.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I think the icons are looking great.

@kathy-phet @ariel-phet any further thoughts?
![image](https://user-images.githubusercontent.com/8419308/58839655-dc524c80-861f-11e9-8f9d-344c634ac918.png)

**Comment by arouinfar** [comment]
Met with @kathy-phet and she gave these icons a 👍

**Comment by ariel-phet** [comment]
Looks good to me, closing!
