### ISSUE TITLE
branch: bicycle-pump

### ISSUE THREAD

**Issue by chrisklus** [phetsims/gas-properties#59]
This branch is for trying out the integration of BicyclePumpNode from https://github.com/phetsims/states-of-matter/issues/217.

**Comment by pixelzoom** [comment]
@chrisklus I've integrated BicyclePumpNode into master.  You can delete this branch if your'e done with it.

**Comment by chrisklus** [comment]
This branch has been deleted, closing.

**Comment by pixelzoom** [comment]
Due to https://github.com/phetsims/special-ops/issues/196#issuecomment-823486502, this branch was restored.  It will need to be deleted again.  Reopening and self assigning.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
