### ISSUE TITLE
requirements for behavior when paused

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#60]
The design document does not specify the behavior of the sim when it is paused.  And there are some significant issues here.  For example, in the Diffusion screen, if radius changes when mass is changed, do we see the change while the sim is paused?  If so, that will require (nontrivial) relocation of particles that are close to the container walls.

@arouinfar For the controls listed below, please add a table to the design document that specifies:

(1) Is the control enabled when the sim is paused?
(2) If so, what happens when the control is changed?
(3) If not, what does the control look like when disabled?

_Ideal_ screen:
* Container resize handle
* Container lid
* Heat/cool slider
* Temperature combo box
* Pressure combo box
* Hold Constant radio buttons
* Particle Counts spinners
* Bicycle pump

_Explore_ screen, same as _Ideal_ screen, plus
* Container resize handle that does work on particles

_Energy_ screen
* Heat/cool slider
* Particle Counts spinners

_Diffusion_ screen
* Number of Particles spinners
* Mass spinners
* Initial Temperature spinners
* Remove Divider button
* Center of Mass checkbox
* Particle Flow Rate checkbox

This is needed with high priority.

**Comment by pixelzoom** [comment]
@arouinfar can you take a pass at this before 5/2/19 design meeting?

**Comment by arouinfar** [comment]
Generally, I think disabling UI elements when paused can lead to buggy-feeling behavior, and should be avoided. There are a few cases (heat/cool slider & container handle on Explore) where it is not feasible to keep the sim paused. There, I think the more natural thing to do would be to unpause the sim, as was done with the wrench in Wave on a String.

| UI Element | Enabled? | Behavior |
| --- | --- | --- |
| Container resize handle (Ideal) | Yes | When container is resized the particles will shift accordingly, but their motion will remain paused. |
| Container resize handle (Explore) | Yes | Resizing container will unpause the simulation.  Here, there is no way to change volume while keeping the sim paused, as the velocity of the wall will affect the velocity of the particles colliding with it. |
| Container Lid | Yes | Lid can be moved, and particle motion will remain paused. |
| Heat/cool slider | Yes | Using slider will unpause the sim. Heat is not something that can be "queued up" like adding particles. | 
| Temperature combo box | Yes | Users can toggle between units, though value is static while paused. |
| Pressure combo box  | Yes | Users can toggle between units, though value is static while paused. |
| Hold Constant radio buttons | Yes | Hold constant mode is changed, and associated UI changes (e.g. removing container handle) will be made. |
| Particle Counts spinners | Yes | When adding particles, they will be queued up for when sim is unpaused/stepped forward. When removing particles, they will immediately disappear from the container. |
| Bicycle pump | Yes | Particles will be queued up for when the sim is unpaused/stepped forward. The indicator bars on the pump will go down accordingly. |
| Number of Particles spinners | Yes | Particles will be added/removed to/from container, but particle motion remains paused. |
| Mass spinners | Yes | Immediately change particle masses. If we decide that changing mass will also change the radius, I am fine with particle edges overlapping the container edge, so no need to spend time relocating particles. | 
| Initial Temperature spinners | Yes | Particle velocities are updated immediately in the model to match new T, though motion remains paused. |  
| Remove Divider button | Yes | Divider is removed, but particles remain paused. |  
| Center of Mass checkbox | Yes | Show COM marker. |
| Particle Flow Rate checkbox | Yes | Show particle flow rate vectors. |

**Comment by pixelzoom** [comment]
> Heat/cool slider: Using slider will unpause the sim. ...

And if the sim is paused because the container resize handle is being dragged, what do we do? Cancel interaction with the resize handle?

> Mass spinners: If we decide that changing mass will also change the radius, I am fine with particle edges overlapping the container edge, so no need to spend time relocating particles.

I am not at all fine with this. It look awful.  And it will cause the sim to fail - I went to great lengths to put in fail-safes to prevent particles from leaking out of the container, and this will trigger a leak failure.

**Comment by arouinfar** [comment]
> Heat/cool slider: Using slider will unpause the sim. ...
>> And if the sim is paused because the container resize handle is being dragged, what do we do? Cancel interaction with the resize handle?

This seems a bit different than just hitting the pause button. Dragging the container handle does pause the sim, but it also makes the play/pause group inactive/unpickable.  I believe we had also decided to make pretty much all other UI components unpickable when dragging the container handle?

> Mass spinners: If we decide that changing mass will also change the radius, I am fine with particle edges overlapping the container edge, so no need to spend time relocating particles.
>>I am not at all fine with this. It look awful.  And it will cause the sim to fail - I went to great lengths to put in fail-safes to prevent particles from leaking out of the container, and this will trigger a leak failure. 

I think the behavior should be the same for all spinners. If you can change one group of spinners while paused, you should be able to do the same with the other spinners. Since it looks like we will change the radii of the particles, I see two solutions

(1) Shift the particles when their size changes so that they stay within the bounds of the container.
(2) Unpause the sim if any of the spinners are changed.

Play/pause don't serve any pedagogical goals before the divider is removed, so I could live with (2). I prefer the UX of (1), but think this is something we should decide in tomorrow's design meeting.

**Comment by pixelzoom** [comment]
>  I believe we had also decided to make pretty much all other UI components unpickable when dragging the container handle?
 
I don't recall ever making that decision.  I do recall that we decided to pause the sim while dragging the resize handle, and to disable the Heat/Cool slider when the sim is paused.  That's what is currently implemented.

> Mass spinners: ... two solutions
> 
> (1) Shift the particles when their size changes so that they stay within the bounds of the container.
> (2) Unpause the sim if any of the spinners are changed.
> 
> Play/pause don't serve any pedagogical goals before the divider is removed, so I could live with (2).

Solution (2) does not make the problem any easier to solve.  I will still need to reposition particles before the next timestep, otherwise some particles may not be fully inside the container.

**Comment by pixelzoom** [comment]
5/2/19 design meeting @arouinfar @ariel-phet @kathy-phet:

* Disable Heat/Cool slider while sim is paused.
* OK to use Diffusion spinners while paused, handle radius overlap with container.

**Comment by pixelzoom** [comment]
With this exception of the resize handle in the Explore screen, this specification is fully implemented. I'll leave this assigned to me using I complete the Explore screen.

**Comment by pixelzoom** [comment]
@arouinfar The behavior of things that have a sample period feels a bit odd (to me) when stepping the sim.  

Currently we have:

* step button advances sim by 0.2 ps
* pressure gauge is updated every 0.75 ps
* histograms and Average Speed are updated every 1 ps

So when you're using the step button, you need to press it several times before these things update.  That may be OK, but I wanted to point it out.

**Comment by pixelzoom** [comment]
Histograms also have some update issues when the sim is paused.  To be addressed in the overhaul of histograms in #52.

**Comment by pixelzoom** [comment]
We originally thought that we could ignore changes to controls while the sim is paused, and just require the user to press the step button (possibly multiple times!) to update.  But while working on histograms #52, I noticed that it seemed odd that the histograms did not update if the container was emptied while the sim was paused.  Ditto for the Average Speed display, thermometer, and pressure gauge.  Discussing with @arouinfar, we realized that the view really needs to update whenever the Step button is pressed, or when the number of particles in the container changes while the sim is paused.    If we don't do this, then the model and view are out of sync, and there's the possibility for misconception.

This will be a major change, but I'm optimistic that it won't be destabilizing.

**Comment by pixelzoom** [comment]
Major changes in the above commits, here's a summary.

Step button: When the step button is pressed, any "sample period" or "refresh period" is ignored, and everything is updated immediately.  This include the thermometer, pressure gauge, Average Speed display, histograms, Data accordion box, and center-of-mass indicators. (The particle flow rate indicators already update on every step.)

Change in number of particles: I separated the main model into 2 pieces: particle system + things that depend on the particle system.  When the sim is playing, the particle system is stepped, then the things that depend on it are updated.  If there's a change in number of particles when the sim is paused, the particles are not stepped, and just the things that depend on the particle system are updated immediately. 

Reminder that, after adding particles to an empty container, the pressure gauge won't update until 1 particle has collided with the container.  So if you pump in a bunch of particles into an empty container with the sim paused, you'll see 0 pressure until 1 of them collides with the container.

@arouinfar please take a close look at [1.0.0-dev.35](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.35/phet/gas-properties_en_phet.html).

**Comment by pixelzoom** [comment]
@arouinfar while you're reviewing, it would also be good to verify the parts of the table in https://github.com/phetsims/gas-properties/issues/60#issuecomment-488393966 that are still relevant.  Thanks.

**Comment by pixelzoom** [comment]
@arouinfar I discovered another case that we hadn't considered.  If the container is resized while the size is paused, the model needs to be updated.  That is handled by the above commit.  Test drive in master or  [1.0.0-dev.36](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.36/phet/gas-properties_en_phet.html).

**Comment by arouinfar** [comment]
@pixelzoom things are generally looking really good. In the constant pressure modes, changing N can lead to some odd looking behavior.

In Pressure ↕T, changing N instantaneously changes T (as it should). However, the fire/ice animation will not begin until the simulation is stepped forward. I don't think this is particularly pedagogically problematic since the fire/ice animation will appear on the next time step.
![PvaryT](https://user-images.githubusercontent.com/8419308/59224315-56885100-8b8b-11e9-9d9d-76da6154907a.gif)

In Pressure ↕V, changing N instantaneously changes V (again, as it should). However, the particle positions do not shift until the next time step. This looks downright buggy to me.
![PvaryV](https://user-images.githubusercontent.com/8419308/59224316-56885100-8b8b-11e9-8f8e-02ffb5ba242c.gif)

The easiest solution would be to unpause the simulation whenever N is changed. However, this would prevent users from pausing the sim and setting up experiments with varying N.

An alternative could be for particles to be truly queued up and not added to the model until the next time step. Currently, particles added while paused will immediately appear at the end of the BicyclePumpNode hose, and will be added to the model.
![image](https://user-images.githubusercontent.com/8419308/59227247-1bd5e700-8b92-11e9-9fa4-d749920d30e6.png)

@pixelzoom thoughts?

**Comment by pixelzoom** [comment]
> In Pressure ↕T, changing N instantaneously changes T (as it should). However, the fire/ice animation will not begin until the simulation is stepped forward. I don't think this is particularly pedagogically problematic since the fire/ice animation will appear on the next time step.

The fire/ice currently can't run unless the sim clock is running.  I could move it to its own timer, but not sure what problems we'll encounter there.  If you're OK with the current behavior, then so am I.

> In Pressure ↕V, changing N instantaneously changes V (again, as it should). However, the particle positions do not shift until the next time step. This looks downright buggy to me.

How about if we simply redistribute the particles if the volume changes while the sim is paused? Just like when the user is dragging the container resize handle.  @arouinfar does that sound reasonable?

**Comment by arouinfar** [comment]
> The fire/ice currently can't run unless the sim clock is running. I could move it to its own timer, but not sure what problems we'll encounter there. If you're OK with the current behavior, then so am I.

I don't really want to go there. I'm OK with the current behavior. 

> How about if we simply redistribute the particles if the volume changes while the sim is paused? Just like when the user is dragging the container resize handle. @arouinfar does that sound reasonable?

That sounds like a good idea. For consistency, I think we'd also want the particles to redistribute when the volume changes while the sim is not paused, though.

**Comment by pixelzoom** [comment]
> That sounds like a good idea. For consistency, I think we'd also want the particles to redistribute when the volume changes while the sim is not paused, though.

Agreed.  Implemented in master, @arouinfar please verify.

**Comment by arouinfar** [comment]
Looks great @pixelzoom!
