### ISSUE TITLE
Particles added via the bicycle pump are not behaving properly

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#62]
Particles added via the bicycle pump are not behaving properly.  They have the wrong initial temperature, and some of them seem to get stuck at the point where the hose is attached to the container. They also have a "wave" look to them.   And the problem is intermittent.

Things seemed to be working OK in [1.0.0-dev.15](https://bayes.colorado.edu/dev/html/gas-properties/1.0.0-dev.15/phet/gas-properties_en_phet.html), so this may be related to the class hierarchy refactoring that took place after that.  Or it could be related to BicyclePumpNode changes.  

@kathy-phet FYI, since you remarked on this in 5/2/19 design meeting.

**Comment by pixelzoom** [comment]
It's also broken in 1.0.0-dev.15.    To reproduce:

1. Start sim
2. Intro screen
3. Pull the pump handle up a little, then push down. Temperature will be 300K.
2. Reset All
3. Pull the pump handle all the way up, push all the way down.  The temperature will not be 300K, and will be some much lower value.

**Comment by pixelzoom** [comment]
The other odd thing that I've discovered about BicyclePumpNode is that it will only add particles one at a time.   That's going to be generally problematic in this sim, because we want to add groups of particles simultaneous, with a gaussian distribution of initial temperature values, so that we don't end up with "waves" of particles.

**Comment by chrisklus** [comment]
>some of them seem to get stuck at the point where the hose is attached to the container

I've been observing that occasionally as well, not sure what could be causing it.

**Comment by pixelzoom** [comment]
Temperature issue was fixed via https://github.com/phetsims/states-of-matter/issues/217#issuecomment-490652719.  

Now we have the issue of 1 particle getting stuck where it enters the container at the hose.

**Comment by pixelzoom** [comment]
I made a little progress on this, but still perplexed.   If I add assert and console.log as shown below, I see that `meanTemperature` is `null` -- and it should never be `null`.   I did not commit this, will come back to it.

```js
           // Current temperature in the non-empty container
           meanTemperature = this.temperatureProperty.value;
194        assert && assert( typeof meanTemperature === 'number', `bad meanTemperature: ${meanTemperature}` );
         }
196      console.log( `add ${n} particles at ${meanTemperature} K` ); //XXX
```

**Comment by pixelzoom** [comment]
I'm seeing 2 calls to `addParticles` without a `step` call between them.  That means that the temperature isn't being computed, and is still `null` when the second `addParticles` call occurs.

**Comment by pixelzoom** [comment]
I believe we that this is fixed. Instead of looking at `numberOfParticles` to determine whether to use the container's temperature, it makes more sense to look at `temperatureProperty.value`.   I added an assertion for a valid `meanTemperature`, tested a few dozen times, and the problem appears to be resolved.  Closing.
