### ISSUE TITLE
lid animation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#64]
When the lid blows off the container, it animated.  The current animation is what @arouinfar and I decided to start with.  If something else is desired, let's discuss.

**Comment by arouinfar** [comment]
Currently, the lid floats away, keeping the same central x-coordinate.
![blown_lid](https://user-images.githubusercontent.com/8419308/57408047-de9cc480-71a1-11e9-97a6-1934e97dc7c6.gif)

In Java, the lid animation looks more like an explosion. The lid rotates, and its central x-coordinate moves a bit to the left as the lid exits the screen. 
![blown_lid_java](https://user-images.githubusercontent.com/8419308/57408234-57038580-71a2-11e9-856d-5b635746adf6.gif)

I think the current behavior is a good place holder, but it would be nice to make the animation a bit more exciting. We don't have to exactly replicate the Java behavior, but I think some rotation and movement to the left would make it look a bit more like the lid had blown off. 

Leaving tagged for design meeting to see if the team agrees.

**Comment by pixelzoom** [comment]
I mentioned this before...  I'll be happy to add rotation.  But because the lid is much wider than the Java version, and the distance between the lid and top of the screen is relatively small, you are not going to see much (if any) of the rotation.   Movement to the left also implies a force on the lid that is incorrect.

**Comment by pixelzoom** [comment]
5/9/19 design meeting @arouinfar @ariel-phet @KatieWoe:

Make the right edge move N pixels for every 1 pixel that the left edge moves up, while the entire lid is moving up and to the left a bit.

Hook up lid animation to time clock, so it's paused when it should be.

**Comment by pixelzoom** [comment]
Lid animation has been revised in [1.0.0-dev.24](), and can be tweaked via the query parameters shown below.  Rotation is about the center of mass.   The current default values were set so that speeds are similar to SOM (which imo feels way too slow).

@arouinfar @ariel-phet Please review with lids of various sizes.  Let me know what default values you'd like, and whether there is anything else that needs to be changed.

```
    /**
     * x component of the lid's animation speed, in pixels/second. Positive x is to the right.
     * For internal use only, not public facing.
     */
    lidSpeedX: {
      type: 'number',
      defaultValue: -50
    },

    /**
     * y component of the lid's animation speed, in pixels/second. Positive y is down.
     * For internal use only, not public facing.
     */
    lidSpeedY: {
      type: 'number',
      isValidValue: value => ( value < 0 ),  // value must be negative, because lid must move upward
      defaultValue: -150
    },

    /**
     * The lid's rotation speed, in degrees/second. Positive rotation is clockwise.
     * For internal use only, not public facing.
     */
    lidSpeedTheta: {
      type: 'number',
      defaultValue: -90
    }
```

**Comment by pixelzoom** [comment]
Btw... Recommended to test with `?maxPressure=1000` so that it's easy to blow the lid off.

**Comment by ariel-phet** [comment]
@pixelzoom @arouinfar all looks pretty nice to me with `lidSpeedTheta=-50` 

Nice behavior for default and smaller lid (IMO), and looks fine with full size lid

**Comment by arouinfar** [comment]
Thanks for setting up the query parameters @pixelzoom!

I think the default speeds look quite nice -- fast enough to look exciting, but not too fast to be seen. I tried adjusting the relative x/y speeds a bit, but I ended up liking the default more. I think the animation tends to look a bit odd with a high rotational speed, so I like @ariel-phet's suggestion to go with `lidSpeedTheta=-50`.

**Comment by pixelzoom** [comment]
Master is now `lidSpeedTheta=-50`.   Back to @arouinfar, feel free to close if there's nothing left to do.

**Comment by arouinfar** [comment]
👍
