### ISSUE TITLE
change pressure gauge jitter as temperature decreases

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#67]
5/9/19 design meeting @arouinfar @ariel-phet @KatieWoe 

At low temperature, there is a little too much jitter in the pressure gauge.  Reduce jitter linearly from 50K to 5K

temperature (K) to jitter multiplier: `new LinearFunction( 5, 50, 0, 1 )`

**Comment by pixelzoom** [comment]
@arouinfar Ready for review.  Jitter scales down linearly when temperature is <= 50K, and jitter becomes 0 kPa when temperature <= 5K.   As a reminder, the current defaults are `minJitter=0` and `maxJitter=200` kPa.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. It's looking really nice!
