### ISSUE TITLE
behavior of Step for things that have a sample period

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#68]
Currently we have:

* step button advances sim by 0.2 ps
* pressure gauge is updated every 0.75 ps
* histograms and Average Speed are updated every 1 ps

So when you're using the Step button, you need to press it several times before these things update.  That may be OK, but I wanted to point it out.

**Comment by arouinfar** [comment]
Thanks for checking @pixelzoom. We touched on this briefly in a recent design meeting, and the consensus was that it was fine for some quantities to update every Nth step forward.
