### ISSUE TITLE
Questions for port

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gas-properties#7]
1. Will we need to support Reversible Reactions/ Balloons and Buoyancy?

2. What is the timeline for publishing? (Fall 2019?)

3. Wishlist for milestones/public availability

4. Do we need to show progress by a certain date?

5. Likely to be more of a rewrite because Java version's view is based on phetgraphics (not Piccolo, so little or nothing to be reused), model may need "some love"

6. WAG would be on the order of a year long project

**Comment by pixelzoom** [comment]
@ariel-phet I think this issue is something for you to review with @kathy-phet.  Assign back to me when you have answers, thanks.

**Comment by pixelzoom** [comment]
Assigning @arouinfar so that she's in the loop.

**Comment by kathy-phet** [comment]
> Will we need to support Reversible Reactions/ Balloons and Buoyancy?

These would not be part of the deliverables. During the design process, I would like to look into the learning goals addressed by these variants, and look at the usage. It may be decided that it would be good to generalize the model to allow for support of these variants in the future, but they are a much lower priority and would be potentially years(?) down the road. 

Most likely though the current sim will become 2 sims -- with one that supports the advanced features in the current Gas Properties sims -- and one that is more introductory chem level. Only the intro chem level one would be required, but I think we would choose to do both at this time.

> What is the timeline for publishing? (Fall 2019?)

Goal would be to have at least something demonstrable (some subset of functionality) by end of January 2019, with publication to the website in 2019 -- hopefully it would not take until Fall 2019, but this would be acceptable too in terms of grant obligations. We would report it as published in a January 2020 grant report.
Obviously this depends on when Equality Explorer wraps up, and other work.

> Wishlist for milestones/public availability

January 2019 - Something demonstrable to show, but doesn't need all functionality. 
End of Spring or Early Summer 2019 - Preferable publication date so can advertise at summer conferences

> Do we need to show progress by a certain date?

Yes - January 2019 (report due end of January).
January 2020 - need to report published to the website.

> Likely to be more of a rewrite because Java version is based of PhETgraphics (so little or nothing to be reused), model may need "some love"

Agreed

> WAG would be on the order of a year long project

What does WAG mean?

**Comment by pixelzoom** [comment]
@kathy-phet asked:
> What does WAG mean?

WAG is an acronym.  It's PG13, so I'll leave it up to you to do the Google search. It means "an off-the-cuff estimate for something, when there is insufficient data available to support a more informed estimation."

**Comment by kathy-phet** [comment]
I agree about a year.

**Comment by arouinfar** [comment]
Thanks for keeping me in the loop @pixelzoom. I've requested time at this week's design meeting for the team to get reacquainted with the sim's current status (luckily the design doc appears to be in great shape) and have a big picture discussion about what's next. Since it doesn't look like there's anything else in this issue that needs work from me, I'll go ahead and unassign myself.

**Comment by pixelzoom** [comment]
Sorry to assign you again so soon @arouinfar.  But the milestones identified in this issue need to go in a Milestones section of the design doc.

**Comment by arouinfar** [comment]
No problem @pixelzoom! I've added a Milestones section to the design doc with the following: 
> January 2019:  Something demonstrable to show, but doesn't need all functionality. Needs to be included in a grant report due at the end of the month.
Late Spring/Early Summer 2019: Preferable publication date so we can advertise the sim at summer conferences
January 2020: Grant report is due, so sim must be published

By the way, @pixelzoom and I had read-only access to the sim folder, so I went ahead and gave us edit privileges.

**Comment by pixelzoom** [comment]
Closing, since this info has been moved into the Milestones section of the design doc.
