### ISSUE TITLE
divider color in projector mode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#72]
The divider color in projector mode (taken from the design doc) seems odd.  See screenshot below.  It's not at all related to the yellow "Remove Divider" toggle button.  And it's a bit similar to the red particle color.  Could we use a shade of yellow that still works on white background?

<img width="881" alt="screenshot_1186" src="https://user-images.githubusercontent.com/3046552/57805614-79ede680-771a-11e9-8daa-98fd61ad2bc5.png">

**Comment by arouinfar** [comment]
I don't think I had considered the misalignment of the divider and button color in projector mode. I couldn't find a good shade of yellow that worked for the divider on in projector mode (which is how I suspect it ended up being magenta), but I did find a green that could work in both modes.

Here are some mockups using `rgb(60, 180, 75)` for the divider and button. (Button is a flat rectangle because it was quicker to experiment with in Illustrator -- not suggesting a new button style here.)
![image](https://user-images.githubusercontent.com/8419308/57813301-d9ed8880-772c-11e9-8d48-9fd69303008e.png)
![image](https://user-images.githubusercontent.com/8419308/57813311-e70a7780-772c-11e9-8923-bb2905e255d4.png)

**Comment by pixelzoom** [comment]
I switched to `rgb(60, 180, 75)` for the divider and button, you can test drive in master.  The black text is a tad lost on green. It tried white text, and it gets washed out when the button highlights on mouse over.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. The [WebAIM Color Contrast Checker](https://webaim.org/resources/contrastchecker/?fcolor=000000&bcolor=3CB44B) shows a contrast of 7.82:1 for black text on this green background (hex equivalent of `#3CB44B`), which exceeds the WCAG AAA standard. That said, fully saturated yellow `#FFFF00` has much higher contrast, with a ratio of 19.55:1.

It's quite tricky to find a a color that isn't too similar to the particles, has sufficient contrast against a black/white background, and sufficient contrast against black text. Let's review with the team.

**Comment by arouinfar** [comment]
I played with the color a bit more and bumped up the brightness ~10%, to `rgb(70, 205, 85)` which improves the contrast ratio for the button text to [10.12:1](https://webaim.org/resources/contrastchecker/?fcolor=000000&bcolor=3CB44B). 

@pixelzoom let's try this green instead.

**Comment by pixelzoom** [comment]
Changed in master, the new green looks like a nice improvement to me.  

Do you want to use the same color for the vertical separator in the Data accordion box, as a visual cue?  I've push that to master also, easy to revert, see screenshot below.

<img width="1078" alt="screenshot_1195" src="https://user-images.githubusercontent.com/3046552/57944532-85651d00-7894-11e9-9673-f56f4bcf33e0.png">

**Comment by pixelzoom** [comment]
Might also consider making the vertical Data separator the same thickness as the divider (also pushed to master, easy to revert).   Screenshot below.  Note that the Data separator doesn't change to a dashed line when the divider is removed, but could without much work.

<img width="1087" alt="screenshot_1196" src="https://user-images.githubusercontent.com/3046552/57944744-2a7ff580-7895-11e9-979d-f0cbf863b060.png">

**Comment by pixelzoom** [comment]
Another note... The original Data separator in https://github.com/phetsims/gas-properties/issues/72#issuecomment-492846251 is difficult to see in "normal" color mode. Using color and lineWidth of the divider makes it nicely visible.

**Comment by pixelzoom** [comment]
See also the suggestion in https://github.com/phetsims/gas-properties/issues/48#issuecomment-493544987, which would strengthen the argument for making the Data separator look like the divider.

**Comment by arouinfar** [comment]
@pixelzoom I think the brighter green is looking great! Changing the color of the divider in the Data panel to match the barrier is also a really nice touch, though I think matching the stroke weight of the barrier may be a bit much. Perhaps we can instead thicken up the Data separator by 1 pt, and see if that's enough to improve the visibility in Projector Mode.

**Comment by pixelzoom** [comment]
> ... Perhaps we can instead thicken up the Data separator by 1 pt, and see if that's enough to improve the visibility in Projector Mode.

The default separator lineWidth is 1.  I've set it to 2.   Please review in master.

**Comment by arouinfar** [comment]
Looks great, thanks @pixelzoom!
