### ISSUE TITLE
does the gauge have jitter when Pressure is held constant?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#73]
Moved this issue out of https://github.com/phetsims/gas-properties/issues/50#issuecomment-492887935.

We need to decide whether the gauge has jitter when pressure is being held constant in the Ideal screen.   

Today's Slack discussion with @arouinfar:

Chris Malley [2:31 PM]
GP question… When we’re holding pressure constant in the Ideal screen, should there be jitter in the pressure gauge?

Amy Rouinfar [2:39 PM]
Oh, that’s a good question, and I could probably make an argument either way. In Java, holding the pressure constant doesn’t lock down the needle — there are still some fluctuations, but that would come down to the actual fluctuations in the model. It does seem kind of nice to remove the jitter when P is constant (and would better emphasize P being constant), but I don’t know if that would unnecessarily complicate things.
Seems like something that might be nice to put on the agenda for tomorrow.

Chris Malley [2:40 PM]
Removing the jitter when P is constant is easy.  Using a different jitter would not be easy.

Amy Rouinfar [2:40 PM]
I think we would either keep the same jitter, or remove it entirely. No need to complicate the jitter.

**Comment by pixelzoom** [comment]
The implementation in master is currently "no jitter when pressure is held constant".   I tried the other option, and I found it difficult to convince myself that pressure was being held constant.

**Comment by arouinfar** [comment]
@pixelzoom I think removing the jitter will be the way to go, but let's review with the team.

**Comment by pixelzoom** [comment]
5/16/19 design meeting @arouinfar @kathy-phet 

No jitter when pressure is held constant.  Nothing to do, so closing.
