### ISSUE TITLE
Oops! dialog messages

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#74]
`OopsDialog` has been integrated into Gas Properties.  

When "Hold Pressure: Pressure ↕V" would result in a container width that violates the range `(5000, 15000) pm`, an `OopsDialog` is displayed, and the setting is changed to "Hold Constant: Nothing" .

The design document says "Dialog contents TBD", so I've implemented the ability to have different messages based on whether the min or max range would be exceeded.  The current placeholder messages are shown below.  If you'd prefer one message for both cases, that's easy to do too.  

@arouinfar please let me know what you'd like here.

<img width="643" alt="screenshot_1190" src="https://user-images.githubusercontent.com/3046552/57823267-1385ba00-7754-11e9-8f86-240e75609743.png">

<img width="656" alt="screenshot_1191" src="https://user-images.githubusercontent.com/3046552/57823273-17194100-7754-11e9-8604-8f2d608a9a1f.png">

**Comment by arouinfar** [comment]
@pixelzoom dialog looks good, but I would swap out "Container" for "Volume".

It also seems a bit buggy currently. If I am at the min/max volume, simply switching to Constant P, vary V will trigger the dialog. At max V, I could still remove heat or add particles and V would shrink to maintain constant P.

**Comment by pixelzoom** [comment]
Yes, the "Hold Constant" feature has some known problems, which I'm working on and don't require an issue at this point.   This issue is about the messages.  I'll replace "Container" with "Volume".

**Comment by pixelzoom** [comment]
Revised messages are shown below.  Back to @arouinfar to decide whether to review at design meeting or close.

<img width="641" alt="screenshot_1192" src="https://user-images.githubusercontent.com/3046552/57867283-174e2680-77be-11e9-8838-2d4ebdd44793.png">

<img width="630" alt="screenshot_1193" src="https://user-images.githubusercontent.com/3046552/57867289-1a491700-77be-11e9-84fa-11ddd331936f.png">

**Comment by arouinfar** [comment]
Thanks for updating the string. I'll leave this tagged for design meeting since the team hasn't seen it yet.

**Comment by pixelzoom** [comment]
5/16/19 design meeting @arouinfar @kathy-phet 

Messages look good. Closing.
