### ISSUE TITLE
model.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#79]
Describe the model in [model.md](https://github.com/phetsims/gas-properties/blob/master/doc/model.md).

**Comment by veillette** [comment]
While performing the code-review in #109, we noticed that there are a number of TODOs in model.md. These should be revisited.

**Comment by pixelzoom** [comment]
Thanks @veillette, agreed.  As noted in #109:
> ... but keep in mind that model.md and implementation-notes.md are not completed.

**Comment by pixelzoom** [comment]
I've made a first pass at model.md, adding what I felt to be the highlights of the model. With a couple of exceptions, I've purposely avoided using specific value (e.g "the container is 4000 pm deep") because those details are in the code, and could change, making the document out-of-sync.

@arouinfar please review, let me know what you'd like to add/subtract/modify.

**Comment by arouinfar** [comment]
Nicely done @pixelzoom. The documentation is very thorough, and I cannot think of anything else to add.
