### ISSUE TITLE
triage Unfuddle issues

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gas-properties#8]
Before this sim comes up for design meeting again, the Unfuddle issues should be reviewed and triaged.

- for any issues/suggestions we will fix or implement, those should be made into github issues and the unfuddle issue closed with a comment that it will be addressed in the HTML5 version

- for any issues that will never be addressed they should be closed

- any that should be discussed should be brought to design meeting

**Comment by pixelzoom** [comment]
I note design doc, I see:

> **Relevant Unfuddle Tickets**
There are currently 22 open tickets related to the ideal-gas family. Those suggesting improvements to the design have been pasted below.

I don't think we should be pasting the text of Unfuddle issues into the design doc, it duplicates information and will quickly become out of sync.  Comments and decisions on the Unfuddle issues belong in those issues (per @ariel-phet above), not in the design doc.  So let's replace with links to the Unfuddle issues.

**Comment by pixelzoom** [comment]
As of 1/10/18, I see 48 issues in Unfuddle for ideal-gas (the component that Gas Properties is a part of).  The URL is https://phet.unfuddle.com/a#/projects/9404/ticket_reports/349638

**Comment by pixelzoom** [comment]
I reviewed the 22 tickets in Unfuddle, and added a comment about my review to each issue.

These tickets require review by a designer.  They are feature requests, conceptual issues, or possible bugs that haven't been clearly identified:

https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/18
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/563
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/578
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/690
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2268
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2667
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2754
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3493
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3645
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3662
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3685
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2549
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2699
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2700
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3520

This is a translation ticket that will be addressed as a normal part of porting:

https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/1374

These tickets require followup.  Some can be closed, some are fixed but not reviewed/deployed, etc.

https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/1573
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/1702
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3239
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3344
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3644

This TODO list needs to be reviewed, to identify any relevant issues to address in the port:

https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/333

**Comment by arouinfar** [comment]
@pixelzoom thank you for reviewing the Unfuddle tickets!

> I don't think we should be pasting the text of Unfuddle issues into the design doc, it duplicates information and will quickly become out of sync. 

I completely agree! I think it would be helpful to have table in the design doc that links to relevant Unfuddle Tickets, the corresponding GitHub issue, and a short description of the original ticket. I've added a blank table to the design doc [here](https://docs.google.com/document/d/1HOCO6vXfqlHIf3MrdldaiZTPFKYWTzS9Jm8fw-b25EU/edit#heading=h.cwjvdkvq3ytk), and I'll report back once its completed. I'll also covert Unfuddle tickets over to GitHub issues, as necessary.

**Comment by pixelzoom** [comment]
I'll triage the TODO list:
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/333

**Comment by arouinfar** [comment]
Relevant Unfuddle tickets have been converted to GitHub issues. The [Suggestions from Unfuddle](https://docs.google.com/document/d/1HOCO6vXfqlHIf3MrdldaiZTPFKYWTzS9Jm8fw-b25EU/edit#heading=h.cwjvdkvq3ytk) table in the design doc summarizes the issues and links the the Unfuddle and corresponding GitHub issues. Closing.
