### ISSUE TITLE
labels for "Hold Constant" radio buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#81]
A subtle deviation from the design doc that has been in place for a long time, but which I haven't previously pointed out...   Design doc on left, implementation on the right:

<img width="170" alt="screenshot_1198" src="https://user-images.githubusercontent.com/3046552/57955425-2bc01b00-78b3-11e9-869d-04825984f993.png">  <img width="182" alt="screenshot_1199" src="https://user-images.githubusercontent.com/3046552/57955428-2ebb0b80-78b3-11e9-823d-936cb6fa963d.png">

We previously decided to swap the order of the last two radio buttons, to match the order of "Volume (V)" and "Temperature (T)".  That's not the deviation that I'm referring to here.

The deviation is in the use of parenthesis. "Volume (V)" and "Temperature (T)" are appropriate, because what's in parenthesis is the abbreviation of the quantity.   "↕V" and "↕T", on the other hand, should _not_ be in parenthesis; they are not abbreviations for Pressure, they are uses of the abbreviations for other quantities.  So I've removed the parenthesis that were present in the design doc mockups.

@arouinfar let me know if this is OK, or if you want something changed.

**Comment by arouinfar** [comment]
> "↕V" and "↕T", on the other hand, should not be in parenthesis; they are not abbreviations for Pressure, they are uses of the abbreviations for other quantities. 

Completely agree @pixelzoom. Thank you for making this change.
