### ISSUE TITLE
thickness of container walls, lid, and divider

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#83]
The container's walls and lid in the Java version are significantly thicker than the HTML5 version. 

Compare:

<img width="920" alt="screenshot_1208" src="https://user-images.githubusercontent.com/3046552/58059365-c9248480-7b29-11e9-807b-6b88472f55c1.png">

<img width="857" alt="screenshot_1207" src="https://user-images.githubusercontent.com/3046552/58059369-cb86de80-7b29-11e9-8cff-4906220be671.png">

If you'd like to tweak the thickness of the  container walls, lid, and divider, you can use these query parameters:

```js
    /**
     * Thickness of the container's walls, in pm.
     * For internal use only, not public facing.
     */
    wallThickness: {
      type: 'number',
      isValidValue: value => ( value > 0 ),
      defaultValue: 50
    },

    /**
     * Thickness of the container's lid, in pm.
     * For internal use only, not public facing.
     */
    lidThickness: {
      type: 'number',
      isValidValue: value => ( value > 0 ),
      defaultValue: 150
    },

    /**
     * Thickness of the container's vertical divider, in pm.
     * For internal use only, not public facing.
     */
    dividerThickness: {
      type: 'number',
      isValidValue: value => ( value > 0 ),
      defaultValue: 100
    }
```

**Comment by arouinfar** [comment]
I don't think the walls/lid need to be particularly thick, but bumping it up a bit to 
`?wallThickness=75&lidThickness=175` looks pretty good.

![Gas Properties screenshot](https://user-images.githubusercontent.com/8419308/58192165-59bfa980-7c7d-11e9-95a2-4f955b84664c.png)

Tagging for design meeting for a quick check in with @kathy-phet and @ariel-phet.

**Comment by pixelzoom** [comment]
Default values changed and pushed to master.

**Comment by pixelzoom** [comment]
Assigned to @ariel-phet and @kathy-phet for feedback.

**Comment by ariel-phet** [comment]
All looks good to me in terms of thickness for 1.0.0-dev.26. The one tweak I might make is that when the divider is removed on the diffusion screen, that the opacity of the dotted line is turned down a bit (that green has very nice contrast, so I think we could get away with a lighter green, making it feel a bit more like a marker than any possibility of a solid boundary).

**Comment by arouinfar** [comment]
> The one tweak I might make is that when the divider is removed on the diffusion screen, that the opacity of the dotted line is turned down a bit (that green has very nice contrast, so I think we could get away with a lighter green, making it feel a bit more like a marker than any possibility of a solid boundary).

I like this idea! I think 50% opacity could work (mockups below) but we might also consider bumping the opacity up a bit to 60%.

![image](https://user-images.githubusercontent.com/8419308/58266422-d797b980-7d3e-11e9-95ef-40f338a28595.png)
![image](https://user-images.githubusercontent.com/8419308/58266531-0f9efc80-7d3f-11e9-8b5e-0d049561469d.png)

**Comment by pixelzoom** [comment]
The dashed divider is now `opacity: 0.5` in master.

I also wanted to point out (in case it hasn't been noticed) that the dashed lineWidth (50pm) is currently half of solid lineWidth (100pm).   This is something we can tweak too, if desired.

**Comment by pixelzoom** [comment]
5/23/19 dev @arouinfar @ariel-phet @kathy-phet 

Looks great.  I will remove query parameters.

**Comment by pixelzoom** [comment]
Query parameters removed. Closing.
