### ISSUE TITLE
Oops dialog when N goes to zero while holding  "Pressure ↕T" constant

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#84]
When pressure is being held constant, what happens when `N` (the number of particles in the container) goes to zero?  

For "Pressure ↕V", `V = NkT/P`. So volume will become zero, and we've addressed what happens in that case (Oops! dialog and switch to "Nothing" mode).

But for "Pressure ↕T", `T = PV/Nk`. So we'll get a divide-by-zero error.  In this case, it also seems like we need to switch to “Nothing” mode.  Is there an Oops! dialog involved?  I don’t see this addressed in the design doc.

**Comment by arouinfar** [comment]
> But for "Pressure ↕T", T = PV/Nk. So we'll get a divide-by-zero error. In this case, it also seems like we need to switch to “Nothing” mode. Is there an Oops! dialog involved? I don’t see this addressed in the design doc.

Great questions. Yes, I think we'll need to switch to "Nothing". The change to "Nothing" might be too subtle without an Oops! dialog, so I think it would be preferable trigger one with this message:

```
Oops!

Pressure cannot be held constant.
Container is empty.
```

**Comment by pixelzoom** [comment]
Moved to #88, closing.
