### ISSUE TITLE
Oops dialog when N goes to zero while holding T constant

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#86]
We'll need an Oops dialog when N goes to zero while holding T constant.  Something like:

```
Oops! 

Temperature cannot be held constant.
Container is empty.
```

@arouinfar Does this message look OK?

**Comment by arouinfar** [comment]
Looks good!

**Comment by pixelzoom** [comment]
Moving this into https://github.com/phetsims/gas-properties/issues/87.  Closing.
