### ISSUE TITLE
Hold Constant: Temperature (T)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#87]
Requirements:

- [x] disable "Temperature (T)" radio button when container is empty
- [x] hide slider on heat/cool bucket
- [x] if N goes to zero, switch to "Nothing" and display dialog:

```
Oops! 

Temperature cannot be held constant
when the container is empty.
```

**Comment by pixelzoom** [comment]
Implementation of "Temperature (T)" requirements is completed. Ready for review @arouinfar.

**Comment by arouinfar** [comment]
Looks great @pixelzoom. Not sure if you want this issue left open for eventual QA testing, so reassigning it back to you.

**Comment by pixelzoom** [comment]
@arouinfar You bring up a good point - how to communicate the rather complicated behavior of the "Hold Constant" feature to QA so that they know what they are testing.   I don't think describing it in issues (like this one) is the way to go.  Perhaps this is a case where the design document should be brought up to date?   There is information in this issue, #88, and #89 that is not in the design doc.   Thoughts?

**Comment by arouinfar** [comment]
@pixelzoom the [Hold Constant](https://docs.google.com/document/d/1HOCO6vXfqlHIf3MrdldaiZTPFKYWTzS9Jm8fw-b25EU/edit#heading=h.4n0cz0dsk5gj) section of the design doc describes each mode including
* When it is disabled
* UI Changes
* What happens when N, T, or V is changed
* Oops dialog behavior (where applicable)

**Comment by pixelzoom** [comment]
OK, sounds good. I'll plan to refer the QA team to the design document for information on how to test this feature.
