### ISSUE TITLE
Hold Constant: Pressure ↕T

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#88]
Requirements:

- [x] disable "Pressure ↕T" radio button when there is zero pressure in the container
- [x] hide slider on heat/cool bucket
- [x] as N or V is changed, animate heat/cool bucket (Hollywood'ed)
- [x] as N or V changes, adjust particle velocities
- [x] When N goes to zero, switch to "Nothing" and display dialog:

```
Oops!

Pressure cannot be held constant
when the container is empty.
```

**Comment by pixelzoom** [comment]
FYI, particle speeds are adjusted based on their contribution to KE.  In pseudo-code:

```
desiredT = (PV)/(Nk)
desiredAverageKE = ( 3 / 2 ) * desiredT * BOLTZMANN; // KE = (3/2)Tk
actualAverageKE = compute for particles in container
ratio = desiredAverageKE / actualAverageKE
for each particle in the container {
  actualParticleKE = particle.getKineticEnergy();
  desiredParticleKE = ratio * actualParticleKE;
  particle.speed = Math.sqrt( 2 * desiredParticleKE / particle.mass ); // |v| = Math.sqrt( 2 * KE / m )
}
```

The actual code is `adjustParticleVelocitiesForTemperature` in `GasPropertiesModel`.

**Comment by pixelzoom** [comment]
@arouinfar It would be good to have you verify the algorithm described in https://github.com/phetsims/gas-properties/issues/88#issuecomment-495049797, and the resulting behavior in [1.0.0-dev.27](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.27/phet/gas-properties_en_phet.html).

**Comment by pixelzoom** [comment]
5/23/19 design meeting @arouinfar @ariel-phet @kathy-phet 

For bucket animation:
- show flame/ice going up/down in bucket
- make amount of flame/ice proportional to temperature (or KE) change

**Comment by pixelzoom** [comment]
@arouinfar said that https://github.com/phetsims/gas-properties/issues/88#issuecomment-495049797 looks correct.

**Comment by pixelzoom** [comment]
@arouinfar @ariel-phet @kathy-phet animation of the heat/cool bucket is ready for review in master and [1.0.0-dev.31]().

Described below are 4 query parameters that can be used to tune this feature.  Let me know what you'd like to adjust.

```js
    /**
     * Related to animation of heat/cool bucket for 'Pressure T' mode, #88.
     * Temperature changes below this value (in K) are considered zero and result in no animation of flame/ice.  
     * This is required to avoid spurious animation due to floating-point errors.
     * For internal use only.
     */
    minDeltaT: {
      type: 'number',
      isValidValue: value => ( value >= 0 ),
      defaultValue: 0.1
    },

    /**
     * Related to animation of heat/cool bucket for 'Pressure T' mode, #88.
     * Temperature changes >= this value (in K) result in flame/ice being fully on.
     * For internal use only.
     */
    maxDeltaT: {
      type: 'number',
      isValidValue: value => ( value > 0 ),
      defaultValue: 100
    },

    /**
     * Related to animation of heat/cool bucket for 'Pressure T' mode, #88.
     * Smallest percentage of the flame/ice that is raised out of the bucket for any temperature change.
     * For internal use only.
     */
    minHeatCoolFactor: {
      type: 'number',
      isValidValue: value => ( value > 0 && value < 1 ),
      defaultValue: 0.2
    },

    /**
     * Related to animation of heat/cool bucket for 'Pressure T' mode, #88.
     * Animation duration in seconds, split evenly between raising and lowering the flame/ice.
     * For internal use only.
     */
    heatCoolDuration: {
      type: 'number',
      isValidValue: value => ( value > 0 ),
      defaultValue: 1.5
    }
```

**Comment by pixelzoom** [comment]
Also note that the heat/cool bucket animation is currently tied to the simulation timer.  If you pause the simulation, you'll need to press the step button to advance the animation.

**Comment by pixelzoom** [comment]
Added `meeting:design` label for discussion at 5/30/19 design meeting.  Please come to the meeting with the feedback requested in https://github.com/phetsims/gas-properties/issues/88#issuecomment-496725073.

**Comment by pixelzoom** [comment]
Design meeting 5/30/19 @arouinfar @ariel-phet @kathy-phet 

* make heatCoolFactor proportional to `N * deltaT`.  Print `N * deltaT` to console, decide how to scale. 
* other aspects and default values look good

**Comment by pixelzoom** [comment]
The change request identified in https://github.com/phetsims/gas-properties/issues/88#issuecomment-497465179 has been implemented.  Some background information:

The heat/cool bucket shows flame/ice based on a number in the range [-1,1], were +1 is full flame, -1 is full ice, and 0 shows no flame or ice.  This number is referred to as the `heatCoolFactor`.  

When Hold Constant is set to "Pressure T", the `heatCoolFactor` is computed as a linear function of `deltaT * N`, where `deltaT` is change in temperature, and `N` is the number of particles in the container.   

Any non-zero `deltaT * N` will result in a minimum of 20% of the flame/ice visible.

Query parameter `maxDeltaTN` is the `| delta * N |` that results in 100% flame/ice visible. It currently defaults to `10000`.

When the temperature changes in "Pressure T" mode, the values of `deltaT`, `N`, and the computed `heatCoolFactor` are printed to the browser console.

@arouinfar @ariel-phet @kathy-phet please test-drive [1.0.0-dev.33](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.33/phet/gas-properties_en_phet.html) and let me know what value of `maxDeltaTN` you'd like to use.

**Comment by pixelzoom** [comment]
Also note that as of 1.0.0-dev.33,`maxDeltaTN` is the only relevant query parameter for this issue .  The other query parameters described in https://github.com/phetsims/gas-properties/issues/88#issuecomment-496725073 have been removed.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. @kathy-phet and I reviewed briefly, and the general behavior is looking good. I still need to tune `maxDeltaTN`, and it would be helpful to see `| deltaT * N |` printed to the console too. Can you push that to master?

**Comment by pixelzoom** [comment]
@arouinfar `| deltaT * N |` has been added to the console output.

**Comment by ariel-phet** [comment]
I am fine with whatever final decision @arouinfar makes here.

**Comment by arouinfar** [comment]
@pixelzoom let's double `maxDeltaTN` to 20000. 

When testing things out at the default, I noticed a bit of a ceiling effect where `heatCoolFactor` was often 1. Increasing `maxDeltaTN` to 20000 allows for more dynamic range, and I haven't seen much saturation on the low or high end of `heatCoolFactor.`

**Comment by pixelzoom** [comment]
I've increased to `maxDeltaTN: 20000`, and deleted the query parameter.  Looks nice to me.

@arouinfar please review in master.  Feel free to close if all is well.

**Comment by arouinfar** [comment]
👍
