### ISSUE TITLE
Hold Constant: Pressure ↕V

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#89]
Requirements:

- [x] disable "Pressure ↕V" radio button when there is zero pressure in the container
- [x] hide resize handle on container
- [x]  as N or T is changed, adjust V (container width)
- [x] When N goes to zero, switch to "Nothing" and display dialog:

```
Oops!

Pressure cannot be held constant
when the container is empty.
```

- [x] if V exceeds range, display dialog:

```
Oops!

Pressure cannot be held constant.
Volume would be too [large|small].
```

**Comment by pixelzoom** [comment]
Implementation of "Pressure ↕V" requirements is completed.  Ready for review @arouinfar.

**Comment by arouinfar** [comment]
@pixelzoom this is generally looking pretty good. The only issue I found was that the Oops dialog can be improperly triggered if Pressure ↕V mode is selected when V is already at the max or min.

Simply being at max/min volume shouldn't be enough to trigger the dialog.  Suppose I start Pressure ↕V at maximum volume, and then remove some particles. The volume would shrink accordingly. However, if I had instead added some particles, the volume limit would have been exceeded, triggering the Oops dialog.

**Comment by pixelzoom** [comment]
Thanks @arouinfar.  There's a floating-point error that's causing this.  The container width's range is [5000,15000] pm.  Before switching to "Pressure ↕V", the actual container width is 15000 pm.  The computation for desired container width is producing 15000.000000000005 pm.

**Comment by pixelzoom** [comment]
@arouinfar I pushed a fix to master, please verify.

**Comment by arouinfar** [comment]
Looks good @pixelzoom
