### ISSUE TITLE
Musings on how to implement the particle model

### ISSUE THREAD

**Issue by jbphet** [phetsims/gas-properties#9]
From looking at how the particles in original (Java) version the Gas Properties sim interact, I believe the simulation was implemented using a hard sphere model for the particles.  The States of Matter simulation uses a different approach - it calculates particle interactions using a Lennard-Jones potential.  I was recently talking with Paul Beale about whether the States of Matter model would be appropriate to use as the basis for the new HTML5 version of Gas Properties, and he suggested instead using something called the Weeks-Chandler-Andersen potential.  Paul described this as essentially the same as the Lennard-Jones potential, but without the attractive part, so you don't end up with liquid and solid phases at low temperatures.  This sounded pretty promising to me, so I thought I'd log an issue to investigate it.

Paul also said he'd be more than happy to consult with PhET on the implementation of this sim.

I wasn't able to find a ton of information on this particular potential, but here is one link: http://www.sklogwiki.org/SklogWiki/index.php/Weeks-Chandler-Andersen_perturbation_theory.

**Comment by arouinfar** [comment]
@pixelzoom in SOM, the particles have intermolecular attractions, so the Lennard-Jones potential is appropriate there. It looks like Weeks-Chandler-Anderson is a variant of (or at least builds on) the Lennard-Jones potential. 

An ideal gas assumes that the particles do not experience any sort of intermolecular attractions, and that the collisions between particles are perfectly elastic (momentum conserved). A hard sphere model would be most appropriate for Gas Properties.

**Comment by pixelzoom** [comment]
OK, then I'm going to proceed with using the model in the Java implementation.  And I'll close this issue.
