### ISSUE TITLE
speed limit for movable wall

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#90]
This issue was pulled out of https://github.com/phetsims/gas-properties/issues/71#issuecomment-493213748.   We need a speed limit for the movable wall, ala SOM, so that the lid isn't so easily blown off of the container.

TODO:

- [x] add speed limit for the movable (left) wall
- [x] no speed limit on _Ideal screen_, but possible to add one
- [x] query parameter for speed limit, `wallSpeedLimit`, default 1000 pm/ps

Slack discussion about SOM implementation:

Chris Malley [10:33 AM]
Can you point me to where the speed limit is implemented for the SOM lid?

John Blanco [10:43 AM]
It's in `MultipleParticleModel`.  Start at `setTargetParticleContainerHeight`, then look in `stepInternal` where the target is checked and the container height is updated, at line 799 right now (it's a big file).

John Blanco [10:49 AM]
I was just looking at the code, and there is a countdown timer for the height change, but it doesn't look like it is being used, so you can ignore that.  I might have been used for the particle injection, which was recently changed, but I'll look into it and possibly remove it.

**Comment by pixelzoom** [comment]
Slack discussion about SOM implementation:

Chris Malley [10:33 AM]
Can you point me to where the speed limit is implemented for the SOM lid?

John Blanco [10:43 AM]
It's in `MultipleParticleModel`.  Start at `setTargetParticleContainerHeight`, then look in `stepInternal` where the target is checked and the container height is updated, at line 799 right now (it's a big file).

John Blanco [10:49 AM]
I was just looking at the code, and there is a countdown timer for the height change, but it doesn't look like it is being used, so you can ignore that.  I might have been used for the particle injection, which was recently changed, but I'll look into it and possibly remove it.

**Comment by pixelzoom** [comment]
Speed limit is implemented for the Explore screen, default is `?wallSpeedLimit=1000` pm.

@arouinfar please review.

**Comment by arouinfar** [comment]
@pixelzoom the speed limit behavior is looking great. I think it's still a bit too easy to blow the lid, so can you bump the speed limit down to 800 pm/ps and publish a dev version for the design team to test out?

Starting at default V & T, with `wallSpeedLimit=800` it's possible to
* expand the volume without changing T (for heavy particles)
* fully compress up to 250 heavy particles
* fully compress up to 500 light particles

**Comment by pixelzoom** [comment]
Default has been changed to `wallSpeedLimit=800` in master and [1.0.0-dev.30](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.30/phet/gas-properties_en_phet.html).  @ariel-phet @kathy-phet please test drive.

**Comment by ariel-phet** [comment]
Works for me. I think this is OK to close if @kathy-phet does not weigh in soon.

**Comment by pixelzoom** [comment]
Added `meeting:design` label for discussion at 5/29/19 design meeting.  

We are waiting on feedback from @kathy-phet.

**Comment by pixelzoom** [comment]
5/30/19 design meeting @arouinfar @ariel-phet @kathy-phet 

* @kathy-phet suggested having no speed limit for making the container larger
* `wallSpeedLimit=800` looks good for making the container smaller

**Comment by pixelzoom** [comment]
Speed limit now applies only when making the container smaller.  @arouinfar please review in master.

**Comment by arouinfar** [comment]
Looks great, thanks @pixelzoom!
