### ISSUE TITLE
erase button for container

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#91]
5/23/19 design meeting @arouinfar @ariel-phet @kathy-phet 

There was a feeling that an eraser button to clear particles from the container would be useful on the first 3 screens.   We couldn't decide on a great place for it.   I will add this button in a reasonable place, and then we can (a) decide if it's useful, and (b) decide where to put it.

**Comment by pixelzoom** [comment]
This button has been added to the first 3 screens in [1.0.0-dev.28](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.28/phet/gas-properties_en_phet.html).

The button is placed in proximity to the pump and container, which not interfering with the container width indicator.   I experimented with other locations (above hose, tucked in below hose,...) and this location seemed to be the least problematic. 

The button color is the same gray that we used to deemphasize it in Unit Rates.  If you'd like to play with the color, see `eraseButtonColor` in gas-properties-colors.html.

@arouinfar @ariel-phet @kathy-phet please review and let me know what you'd like to change.

**Comment by kathy-phet** [comment]
I like it. Seems like nice flow as I shift from pumping to clearing to pumping.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. The erase button is definitely a convenient addition, and its location is reasonable. I'd be in favor of keeping it.

**Comment by pixelzoom** [comment]
@ariel-phet if everything looks good to you, feel free to close this.

**Comment by ariel-phet** [comment]
@pixelzoom @arouinfar I think the eraser button position and such works well.

I would however give it a slightly darker background color when active (the white background just feels washed out to me)

Here it is with 139, 139, 139 and I think that matches the sim a bit better without "popping" so much that it would be too attractive in the flow (for instance I would not want the normal yellow background)

![eraser button color](https://user-images.githubusercontent.com/4051174/58504932-f7691c00-8148-11e9-8589-2bd7b4efc327.PNG)

**Comment by pixelzoom** [comment]
@ariel-phet And does the same color apply for projector mode?  All colors need to be specified for both modes.

**Comment by ariel-phet** [comment]
@pixelzoom thanks for pointing that out. That color is a bit too much contrast in projector mode. For projector mode I suggest 188, 188, 188

**Comment by pixelzoom** [comment]
Here's the modified color profile for the eraser button:

```js
    // eraser button that is used to clear particles from the container
    eraserButtonColor: {
      default: 'rgb( 139, 139, 139 )',
      projector: 'rgb( 188, 188, 188 )'
    },
```

@ariel-phet @arouinfar please verify in master.

**Comment by ariel-phet** [comment]
@pixelzoom this all looks good to me in master (color wise).

However, when you hit the erase button if you are in one of the Constant modes (Pressure or Temp) you get an "oops dialog" when you hit the eraser. I think we could forgo this dialog in the case where the eraser has been hit the mode has been automatically switched back to nothing. I think this dialog is appropriate if you are dialing the particles to zero by hand or if the lid is left open, but with the erase button it seems unnecessary to me.

**Comment by pixelzoom** [comment]
@ariel-phet suggested:
> ... I think we could forgo this dialog in the case where the eraser has been hit the mode 

That sounds like a design decision for @arouinfar.   My 2 cents: I think it's instructive to have the Oops! dialog for _any_ case where the container becomes empty as the result of a user interaction.  The user may not notice that Hold Constant has been silently switched to "Nothing".  And finally (and least important), the model currently has no idea why the number of particles became zero, and giving it that info is going to be some really ugly code.

**Comment by arouinfar** [comment]
@ariel-phet @pixelzoom I have a slight preference for the lighter gray button, but could live the darker option currently in master.

> I think we could forgo this dialog in the case where the eraser has been hit the mode has been automatically switched back to nothing. 

Actually, I don't think we want to do that. Temperature and Pressure cannot be held constant when the container is empty, and the corresponding radio options are inactive until N > 0 or P > 0, respectively. The sim will need to switch to "Nothing" when the erase button is used, and it feels buggy not to show an Oops dialog in that case.

**Comment by pixelzoom** [comment]
@arouinfar said:
> I have a slight preference for the lighter gray button, but could live the darker option currently in master.

If we're voting, I also prefer a lighter gray.  Dark gray is great for the panels, but the dark gray button feels a little lost to me.

**Comment by pixelzoom** [comment]
`rgb( 220, 220, 220 )` looks pretty good to me in both modes (not checked in):

<img width="1018" alt="screenshot_1220" src="https://user-images.githubusercontent.com/3046552/58590083-89902380-8220-11e9-97fc-ea60ba5554ba.png">

<img width="1008" alt="screenshot_1221" src="https://user-images.githubusercontent.com/3046552/58590089-8d23aa80-8220-11e9-98cf-e13da584b7aa.png">

**Comment by pixelzoom** [comment]
Added meeting:design label for discussion at 5/29/19 design meeting.    There appears to be consensus on location of the button.   For discussion is the button color, in both modes.  Please come prepared with your color preference.

**Comment by ariel-phet** [comment]
I know my preference, but happy to be outvoted :)

**Comment by arouinfar** [comment]
I like @pixelzoom's suggestion of `rgb( 220, 220, 220 )`. Seems like a reasonable compromise.

**Comment by pixelzoom** [comment]
5/30/19 design meeting @ariel-phet @arouinfar @kathy-phet 

`rgb( 220, 220, 220 )` works.

**Comment by pixelzoom** [comment]
Done, closing.
