### ISSUE TITLE
tune pressure gauge jitter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#92]
5/23/19 design meeting @arouinfar @ariel-phet @kathy-phet 

@kathy-phet was concerned that there is too much jitter.

@kathy-phet suggested a "friendly" public-facing query parameter to remove jitter.  Let me know what you'd like to call it.

Jitter is configurable via these query parameters:

```
    // Minimum amount of jitter in the pressure gauge, in kPa.
    // For internal use only, not public facing.
    minJitter: {
      type: 'number',
      isValidValue: value => ( value >= 0 ),
      defaultValue: 0
    },

    // Maximum amount of jitter in the pressure gauge, in kPa.
    // For internal use only, not public facing.
    maxJitter: {
      type: 'number',
      isValidValue: value => ( value > 0 ),
      defaultValue: 200
    },
```

**Comment by arouinfar** [comment]
> @kathy-phet was concerned that there is too much jitter.

Currently, the maximum amount of jitter is 200 kPa. Cutting `maxJitter` down to 100 kPa would results in a maximum fluctuation of ~1 atm which makes it much easier to read a pressure from the gauge. If we wanted to be even more aggressive, we could take `maxJitter` down to 50 kPa, which would make the visible jitter in the needle much more subtle, but would tighten up the pressure readout quite a bit.

@kathy-phet please try out these options, and let us know what you think.

* [maxJitter=100](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.28/phet/gas-properties_en_phet.html?screens=1&maxJitter=100)
* [maxJitter=50](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.28/phet/gas-properties_en_phet.html?screens=1&maxJitter=50)

> @kathy-phet suggested a "friendly" public-facing query parameter to remove jitter. Let me know what you'd like to call it.

Here are some options for the name, in decreasing order of my personal preference.
`noPressureNoise`
`pressureNoiseOff`
`removePressureNoise`

**Comment by pixelzoom** [comment]
`noPressureNoise` can be parsed ambiguously.   I prefer `?pressureNoiseOff`, so I've added it.  Easy to change.  Test drive it here:

https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.29/phet/gas-properties_en_phet.html?pressureNoiseOff

**Comment by pixelzoom** [comment]
@ariel-phet if you have any strong feelings, please weigh in on what the public-facing query parameter should be named for disabling jitter in the pressure gauge.  It's currently named `pressureNoiseOff`.

**Comment by ariel-phet** [comment]
@pixelzoom no strong feelings, I think `pressureNoiseOff` is plenty clear

**Comment by pixelzoom** [comment]
Add `meeting:design` label for discussion at 5/29/19 design meeting.  We are waiting on feedback from @kathy-phet, specifically:

(1) Respond to @arouinfar's request for feedback on jitter values in https://github.com/phetsims/gas-properties/issues/92#issuecomment-495797423.

(2) Weight in on preference for the query parameter name.  It's currently `pressureNoiseOff`.

**Comment by ariel-phet** [comment]
BTW, I would be fine with either jitter value, both add some jitter, which feels important to me, but I am fine with either level, but probably no more agressive than `?maxJitter=50`

**Comment by pixelzoom** [comment]
5/30/19 design meeting @arouinfar @ariel-phet @kathy-phet 

* change default to `maxJitter=50`
* `pressureNoiseOff` is good

**Comment by pixelzoom** [comment]
There was discussion about a "Basics" version of this sim, and that led to the realization that `pressureNoiseOff` should not be a flag.   Change to boolean `pressureNoise`, default `true.`

**Comment by pixelzoom** [comment]
Changes are done in master.  Summary:

* changed `maxJitter` to 50
* delete `maxJitter` and `minJitter` query parameters
* changed `pressureNoiseOff` (flag) to `pressureNoise` (boolean), default `true`
* added "Pressure Noise" checkbox to Options dialog, defaults to `?pressureNoise`

@arouinfar please review.

**Comment by arouinfar** [comment]
Everything's looking good @pixelzoom, thanks!
