### ISSUE TITLE
disable "Remove Divider" button when container is empty?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#94]
On the _Diffusion_ screen... Should the "Remove Divider" button be disabled when the container is empty?  If you remove the divider with an empty container, the sim doesn't do anything.  And the button is very inviting.

**Comment by arouinfar** [comment]
Great idea @pixelzoom. Let's disable the Remove Divider button when the container is empty.

**Comment by pixelzoom** [comment]
@arouinfar Done in master, please review.  

When disabled, the button is currently the default "disabled gray" for sun buttons, which is`rgb( 220, 220, 220 )`.   That works for me (it's not inviting :), but let me know if you'd prefer a different color.

**Comment by arouinfar** [comment]
Looks good to me @pixelzoom. I think "disabled gray" is the right way to go.
