### ISSUE TITLE
always put "checkbox group" in its own panel?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#96]
Somewhat relevant to #30 PhET-iO Design.

In the _Explore_ and _Energy_ screens, "the checkbox group" is in its own panel.

Explore:

<img width="238" alt="screenshot_1215" src="https://user-images.githubusercontent.com/3046552/58447126-b299a280-80c0-11e9-8b25-cfe6219c4241.png">

Energy:

<img width="240" alt="screenshot_1216" src="https://user-images.githubusercontent.com/3046552/58447130-b62d2980-80c0-11e9-87e0-ab2fc1b913c8.png">

In _Ideal_ and _Diffusion_ screens, the "checkbox group" is integrated into a larger panel, preceded by a horizontal separator.

Ideal:

<img width="245" alt="screenshot_1217" src="https://user-images.githubusercontent.com/3046552/58447197-e70d5e80-80c0-11e9-83bc-78e63473784f.png">

Diffusion:

<img width="319" alt="screenshot_1218" src="https://user-images.githubusercontent.com/3046552/58447210-effe3000-80c0-11e9-8d7a-a1d7c7409b5e.png">

I'm wondering if the checkbox group should always be in its own panel.  The most compelling argument for this would be for PhET-iO consistency, if we think that clients may wish to hide the entire checkbox group.   Doing that in the _Ideal_ and _Diffusion_ screens will currently leave a big blank area in the panels.

**Comment by pixelzoom** [comment]
And I do realize that the original design goal was to put the checkbox group in a panel vs an accordion box, because there's no need to hide them.   I'm just questioning whether they should be in their own panel, so that the entire panel can be hidden via PhET-iO without leaving a blank space in a panel.

**Comment by pixelzoom** [comment]
Added meeting:design label for discussion at 5/30/19 design meeting.

**Comment by ariel-phet** [comment]
From an aesthetic point of view, I really like the separator look as used in this sim. I think too many panels can start to look "choppy" for lack of a better word.

My understanding is that we have also accepted that iO clients will potentially make choices that compromise the aesthetic ideal of the sim (from out point of view). So I am personally not overly concerned about the potential blank space in the panel. I sort of see it as those places in a car dashboard that have blank plastic where an option in a more expensive model clearly goes. You know something is missing, and it is kind of an unfortunate look, but it is easily gotten over.

**Comment by arouinfar** [comment]
Thanks for the suggestion @pixelzoom.

> From an aesthetic point of view, I really like the separator look as used in this sim. I think too many panels can start to look "choppy" for lack of a better word.

Agreed @ariel-phet! I definitely prefer the look of fewer panels. It's a bit hard in this sim because there's a need for a lot of independent accordion boxes, so I'd be hesitant to make <i>even more</i> panels.

Currently there are 5 checkboxes appearing in 3 different groupings. It might make more sense to combine them into a separate panel if the checkboxes were the same across all screens.

**Comment by pixelzoom** [comment]
Aesthetically, I also prefer the current implementation.

**Comment by pixelzoom** [comment]
5/30/19 design meeting @arouinfar @ariel-phet @kathy-phet 

Consensus is to leave as is.  If they want to hide checkboxes, they can live with blank spaces.
