### ISSUE TITLE
performance sign-off

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#98]
This is an item from the [Master Checklist](https://github.com/phetsims/gas-properties/issues/1), to be completed by the Lead Designer.

**Comment by pixelzoom** [comment]
@arouinfar This is ready for your review.  You can use master or [1.0.0-dev.36](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.36/phet/gas-properties_en_phet.html).  

The worst-case scenario is shown below: the _Energy_ screen with 2000 particles, all accordion boxes expanded, all 4 "species histogram" checkboxes checked (histograms are updated only when visible), and the stopwatch running.  

Please identify any platforms where we might need to squeeze out more performance.  

<img width="1016" alt="screenshot_1238" src="https://user-images.githubusercontent.com/3046552/59005715-d86b2980-87db-11e9-95cd-c19176cddd53.png">

**Comment by arouinfar** [comment]
@pixelzoom performance is looking pretty smooth, even in the worst-case scenario described in https://github.com/phetsims/gas-properties/issues/98#issuecomment-499338186.

According to @KatieWoe we no longer support iOS 9 or iOS 10, so I tested dev.36 on these devices:
* Chadwick, Chromebook running latest Chrome (74.0.3729.159)
* Pauling, iPad Air 2, iOS 11.3
* Leibniz, iPair Air 2, iOS 12

The iPads had a pretty low frame rate (~15 FPS) in the worst-case scenario, but the particle animation still looked reasonable and UI elements all remained responsive with no noticeable lag.
